//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const keyboardButton = struct {
    pub const constructor_id: u32 = 0x2f67a72f;
    style: ?api.KeyboardButtonStyle = null,
    text: []const u8,
    type_: api.ButtonType,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.style != null) flags |= 1 << 10;
        try w.writeUInt(flags);
        if (self.style) |v| {
            try v.serialize(w);
        }
        try w.writeString(self.text);
        try self.type_.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        if ((flags >> 10) & 1 != 0) {
            self.style = try api.KeyboardButtonStyle.deserialize(allocator, r);
        } else {
            self.style = null;
        }
        self.text = try r.readString();
        self.type_ = try api.ButtonType.deserialize(allocator, r);
        return self;
    }
};

pub const keyboardButtonRow = struct {
    pub const constructor_id: u32 = 0x77608b83;
    buttons: []api.KeyboardButton,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.buttons.len);
        for (self.buttons) |elem_1826| {
            try elem_1826.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1827 = try r.readVectorLength();
        const vec_1828 = allocator.alloc(api.KeyboardButton, len_1827) catch return error.OutOfMemory;
        for (vec_1828) |*elem_1829| {
            elem_1829.* = try api.KeyboardButton.deserialize(allocator, r);
        }
        self.buttons = vec_1828;
        return self;
    }
};

pub const replyKeyboardHide = struct {
    pub const constructor_id: u32 = 0xa03e5b85;
    selective: bool = false,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.selective) flags |= 1 << 2;
        try w.writeUInt(flags);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.selective = (flags >> 2) & 1 != 0;
        _ = allocator;
        return self;
    }
};

pub const replyKeyboardForceReply = struct {
    pub const constructor_id: u32 = 0x86b40b08;
    single_use: bool = false,
    selective: bool = false,
    placeholder: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.single_use) flags |= 1 << 1;
        if (self.selective) flags |= 1 << 2;
        if (self.placeholder != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        if (self.placeholder) |v| {
            try w.writeString(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.single_use = (flags >> 1) & 1 != 0;
        self.selective = (flags >> 2) & 1 != 0;
        if ((flags >> 3) & 1 != 0) {
            self.placeholder = try r.readString();
        } else {
            self.placeholder = null;
        }
        _ = allocator;
        return self;
    }
};

pub const replyKeyboardMarkup = struct {
    pub const constructor_id: u32 = 0x85dd99d1;
    resize: bool = false,
    single_use: bool = false,
    selective: bool = false,
    persistent: bool = false,
    force_reply: bool = false,
    rows: []api.KeyboardButtonRow,
    placeholder: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.resize) flags |= 1 << 0;
        if (self.single_use) flags |= 1 << 1;
        if (self.selective) flags |= 1 << 2;
        if (self.persistent) flags |= 1 << 4;
        if (self.force_reply) flags |= 1 << 5;
        if (self.placeholder != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.rows.len);
        for (self.rows) |elem_1830| {
            try elem_1830.serialize(w);
        }
        if (self.placeholder) |v| {
            try w.writeString(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.resize = (flags >> 0) & 1 != 0;
        self.single_use = (flags >> 1) & 1 != 0;
        self.selective = (flags >> 2) & 1 != 0;
        self.persistent = (flags >> 4) & 1 != 0;
        self.force_reply = (flags >> 5) & 1 != 0;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1831 = try r.readVectorLength();
        const vec_1832 = allocator.alloc(api.KeyboardButtonRow, len_1831) catch return error.OutOfMemory;
        for (vec_1832) |*elem_1833| {
            elem_1833.* = try api.KeyboardButtonRow.deserialize(allocator, r);
        }
        self.rows = vec_1832;
        if ((flags >> 3) & 1 != 0) {
            self.placeholder = try r.readString();
        } else {
            self.placeholder = null;
        }
        return self;
    }
};

pub const replyInlineMarkup = struct {
    pub const constructor_id: u32 = 0xb2b15770;
    force_reply: bool = false,
    rows: []api.KeyboardInlineButtonRow,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.force_reply) flags |= 1 << 5;
        try w.writeUInt(flags);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.rows.len);
        for (self.rows) |elem_1834| {
            try elem_1834.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.force_reply = (flags >> 5) & 1 != 0;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1835 = try r.readVectorLength();
        const vec_1836 = allocator.alloc(api.KeyboardInlineButtonRow, len_1835) catch return error.OutOfMemory;
        for (vec_1836) |*elem_1837| {
            elem_1837.* = try api.KeyboardInlineButtonRow.deserialize(allocator, r);
        }
        self.rows = vec_1836;
        return self;
    }
};

pub const keyboardButtonStyle = struct {
    pub const constructor_id: u32 = 0x4fdd3430;
    bg_primary: bool = false,
    bg_danger: bool = false,
    bg_success: bool = false,
    icon: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.bg_primary) flags |= 1 << 0;
        if (self.bg_danger) flags |= 1 << 1;
        if (self.bg_success) flags |= 1 << 2;
        if (self.icon != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        if (self.icon) |v| {
            try w.writeLong(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.bg_primary = (flags >> 0) & 1 != 0;
        self.bg_danger = (flags >> 1) & 1 != 0;
        self.bg_success = (flags >> 2) & 1 != 0;
        if ((flags >> 3) & 1 != 0) {
            self.icon = try r.readLong();
        } else {
            self.icon = null;
        }
        _ = allocator;
        return self;
    }
};

pub const buttonTypeDefault = struct {
    pub const constructor_id: u32 = 0xc9dd90e9;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const buttonTypeRequestPhone = struct {
    pub const constructor_id: u32 = 0xdf3d36f9;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const buttonTypeRequestGeoLocation = struct {
    pub const constructor_id: u32 = 0x9beee140;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const buttonTypeRequestPoll = struct {
    pub const constructor_id: u32 = 0xaacfff84;
    quiz: ?bool = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.quiz != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.quiz) |v| {
            try w.writeBool(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        if ((flags >> 0) & 1 != 0) {
            self.quiz = try r.readBool();
        } else {
            self.quiz = null;
        }
        _ = allocator;
        return self;
    }
};

pub const buttonTypeRequestPeer = struct {
    pub const constructor_id: u32 = 0x4f58a237;
    button_id: i32,
    peer_type: api.RequestPeerType,
    max_quantity: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        const flags: u32 = 0;
        try w.writeUInt(flags);
        try w.writeInt(self.button_id);
        try self.peer_type.serialize(w);
        try w.writeInt(self.max_quantity);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        _ = flags;
        self.button_id = try r.readInt();
        self.peer_type = try api.RequestPeerType.deserialize(allocator, r);
        self.max_quantity = try r.readInt();
        return self;
    }
};

pub const inputButtonTypeRequestPeer = struct {
    pub const constructor_id: u32 = 0x3fe268fe;
    name_requested: bool = false,
    username_requested: bool = false,
    photo_requested: bool = false,
    button_id: i32,
    peer_type: api.RequestPeerType,
    max_quantity: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.name_requested) flags |= 1 << 0;
        if (self.username_requested) flags |= 1 << 1;
        if (self.photo_requested) flags |= 1 << 2;
        try w.writeUInt(flags);
        try w.writeInt(self.button_id);
        try self.peer_type.serialize(w);
        try w.writeInt(self.max_quantity);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.name_requested = (flags >> 0) & 1 != 0;
        self.username_requested = (flags >> 1) & 1 != 0;
        self.photo_requested = (flags >> 2) & 1 != 0;
        self.button_id = try r.readInt();
        self.peer_type = try api.RequestPeerType.deserialize(allocator, r);
        self.max_quantity = try r.readInt();
        return self;
    }
};

pub const buttonTypeSimpleWebView = struct {
    pub const constructor_id: u32 = 0xc01a597a;
    url: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inlineButtonTypeUrl = struct {
    pub const constructor_id: u32 = 0xeca4f8d4;
    url: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inlineButtonTypeUrlAuth = struct {
    pub const constructor_id: u32 = 0xbfd02da2;
    fwd_text: ?[]const u8 = null,
    url: []const u8,
    button_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.fwd_text != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.fwd_text) |v| {
            try w.writeString(v);
        }
        try w.writeString(self.url);
        try w.writeInt(self.button_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        if ((flags >> 0) & 1 != 0) {
            self.fwd_text = try r.readString();
        } else {
            self.fwd_text = null;
        }
        self.url = try r.readString();
        self.button_id = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const inputInlineButtonTypeUrlAuth = struct {
    pub const constructor_id: u32 = 0x9961bcb4;
    request_write_access: bool = false,
    fwd_text: ?[]const u8 = null,
    url: []const u8,
    bot: ?api.InputUser = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.request_write_access) flags |= 1 << 0;
        if (self.fwd_text != null) flags |= 1 << 1;
        if (self.bot != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        if (self.fwd_text) |v| {
            try w.writeString(v);
        }
        try w.writeString(self.url);
        if (self.bot) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.request_write_access = (flags >> 0) & 1 != 0;
        if ((flags >> 1) & 1 != 0) {
            self.fwd_text = try r.readString();
        } else {
            self.fwd_text = null;
        }
        self.url = try r.readString();
        if ((flags >> 2) & 1 != 0) {
            self.bot = try api.InputUser.deserialize(allocator, r);
        } else {
            self.bot = null;
        }
        return self;
    }
};

pub const inlineButtonTypeWebView = struct {
    pub const constructor_id: u32 = 0x3bcab5b4;
    url: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inlineButtonTypeCallback = struct {
    pub const constructor_id: u32 = 0x2955bc38;
    requires_password: bool = false,
    data: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.requires_password) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeBytes(self.data);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.requires_password = (flags >> 0) & 1 != 0;
        self.data = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const inlineButtonTypeGame = struct {
    pub const constructor_id: u32 = 0x5cd3709d;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inlineButtonTypeBuy = struct {
    pub const constructor_id: u32 = 0x48bad7a5;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inlineButtonTypeSwitchInline = struct {
    pub const constructor_id: u32 = 0x93773ff5;
    same_peer: bool = false,
    query: []const u8,
    peer_types: ?[]api.InlineQueryPeerType = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.same_peer) flags |= 1 << 0;
        if (self.peer_types != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeString(self.query);
        if (self.peer_types) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_1838| {
                try elem_1838.serialize(w);
            }
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.same_peer = (flags >> 0) & 1 != 0;
        self.query = try r.readString();
        if ((flags >> 1) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_1839 = try r.readVectorLength();
            const vec_1840 = allocator.alloc(api.InlineQueryPeerType, len_1839) catch return error.OutOfMemory;
            for (vec_1840) |*elem_1841| {
                elem_1841.* = try api.InlineQueryPeerType.deserialize(allocator, r);
            }
            self.peer_types = vec_1840;
        } else {
            self.peer_types = null;
        }
        return self;
    }
};

pub const inlineButtonTypeUserProfile = struct {
    pub const constructor_id: u32 = 0x3fa33fcf;
    user_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.user_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.user_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputInlineButtonTypeUserProfile = struct {
    pub const constructor_id: u32 = 0x53f3ce5a;
    user_id: api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.user_id.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.user_id = try api.InputUser.deserialize(allocator, r);
        return self;
    }
};

pub const inlineButtonTypeCopy = struct {
    pub const constructor_id: u32 = 0xb41d3272;
    copy_text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.copy_text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.copy_text = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inlineButtonTypeDisabled = struct {
    pub const constructor_id: u32 = 0xa438619d;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const keyboardInlineButton = struct {
    pub const constructor_id: u32 = 0x11c1a322;
    style: ?api.KeyboardButtonStyle = null,
    text: []const u8,
    type_: api.InlineButtonType,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.style != null) flags |= 1 << 10;
        try w.writeUInt(flags);
        if (self.style) |v| {
            try v.serialize(w);
        }
        try w.writeString(self.text);
        try self.type_.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        if ((flags >> 10) & 1 != 0) {
            self.style = try api.KeyboardButtonStyle.deserialize(allocator, r);
        } else {
            self.style = null;
        }
        self.text = try r.readString();
        self.type_ = try api.InlineButtonType.deserialize(allocator, r);
        return self;
    }
};

pub const keyboardInlineButtonRow = struct {
    pub const constructor_id: u32 = 0x19420af6;
    buttons: []api.KeyboardInlineButton,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.buttons.len);
        for (self.buttons) |elem_1842| {
            try elem_1842.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1843 = try r.readVectorLength();
        const vec_1844 = allocator.alloc(api.KeyboardInlineButton, len_1843) catch return error.OutOfMemory;
        for (vec_1844) |*elem_1845| {
            elem_1845.* = try api.KeyboardInlineButton.deserialize(allocator, r);
        }
        self.buttons = vec_1844;
        return self;
    }
};

pub const richButtonStyle = struct {
    pub const constructor_id: u32 = 0x03c610bd;
    bg_primary: bool = false,
    bg_danger: bool = false,
    bg_success: bool = false,
    link: bool = false,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.bg_primary) flags |= 1 << 0;
        if (self.bg_danger) flags |= 1 << 1;
        if (self.bg_success) flags |= 1 << 2;
        if (self.link) flags |= 1 << 3;
        try w.writeUInt(flags);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.bg_primary = (flags >> 0) & 1 != 0;
        self.bg_danger = (flags >> 1) & 1 != 0;
        self.bg_success = (flags >> 2) & 1 != 0;
        self.link = (flags >> 3) & 1 != 0;
        _ = allocator;
        return self;
    }
};

pub const KeyboardButton = union(enum) {
    keyboardButton: api.keyboardButton,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.keyboardButton.constructor_id => return .{ .keyboardButton = try api.keyboardButton.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const KeyboardButtonRow = union(enum) {
    keyboardButtonRow: api.keyboardButtonRow,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.keyboardButtonRow.constructor_id => return .{ .keyboardButtonRow = try api.keyboardButtonRow.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const ReplyMarkup = union(enum) {
    replyKeyboardHide: api.replyKeyboardHide,
    replyKeyboardForceReply: api.replyKeyboardForceReply,
    replyKeyboardMarkup: api.replyKeyboardMarkup,
    replyInlineMarkup: api.replyInlineMarkup,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.replyKeyboardHide.constructor_id => return .{ .replyKeyboardHide = try api.replyKeyboardHide.deserialize(allocator, r) },
            api.replyKeyboardForceReply.constructor_id => return .{ .replyKeyboardForceReply = try api.replyKeyboardForceReply.deserialize(allocator, r) },
            api.replyKeyboardMarkup.constructor_id => return .{ .replyKeyboardMarkup = try api.replyKeyboardMarkup.deserialize(allocator, r) },
            api.replyInlineMarkup.constructor_id => return .{ .replyInlineMarkup = try api.replyInlineMarkup.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const KeyboardButtonStyle = union(enum) {
    keyboardButtonStyle: api.keyboardButtonStyle,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.keyboardButtonStyle.constructor_id => return .{ .keyboardButtonStyle = try api.keyboardButtonStyle.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const ButtonType = union(enum) {
    buttonTypeDefault: api.buttonTypeDefault,
    buttonTypeRequestPhone: api.buttonTypeRequestPhone,
    buttonTypeRequestGeoLocation: api.buttonTypeRequestGeoLocation,
    buttonTypeRequestPoll: api.buttonTypeRequestPoll,
    buttonTypeRequestPeer: api.buttonTypeRequestPeer,
    inputButtonTypeRequestPeer: api.inputButtonTypeRequestPeer,
    buttonTypeSimpleWebView: api.buttonTypeSimpleWebView,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.buttonTypeDefault.constructor_id => return .{ .buttonTypeDefault = try api.buttonTypeDefault.deserialize(allocator, r) },
            api.buttonTypeRequestPhone.constructor_id => return .{ .buttonTypeRequestPhone = try api.buttonTypeRequestPhone.deserialize(allocator, r) },
            api.buttonTypeRequestGeoLocation.constructor_id => return .{ .buttonTypeRequestGeoLocation = try api.buttonTypeRequestGeoLocation.deserialize(allocator, r) },
            api.buttonTypeRequestPoll.constructor_id => return .{ .buttonTypeRequestPoll = try api.buttonTypeRequestPoll.deserialize(allocator, r) },
            api.buttonTypeRequestPeer.constructor_id => return .{ .buttonTypeRequestPeer = try api.buttonTypeRequestPeer.deserialize(allocator, r) },
            api.inputButtonTypeRequestPeer.constructor_id => return .{ .inputButtonTypeRequestPeer = try api.inputButtonTypeRequestPeer.deserialize(allocator, r) },
            api.buttonTypeSimpleWebView.constructor_id => return .{ .buttonTypeSimpleWebView = try api.buttonTypeSimpleWebView.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InlineButtonType = union(enum) {
    inlineButtonTypeUrl: api.inlineButtonTypeUrl,
    inlineButtonTypeUrlAuth: api.inlineButtonTypeUrlAuth,
    inputInlineButtonTypeUrlAuth: api.inputInlineButtonTypeUrlAuth,
    inlineButtonTypeWebView: api.inlineButtonTypeWebView,
    inlineButtonTypeCallback: api.inlineButtonTypeCallback,
    inlineButtonTypeGame: api.inlineButtonTypeGame,
    inlineButtonTypeBuy: api.inlineButtonTypeBuy,
    inlineButtonTypeSwitchInline: api.inlineButtonTypeSwitchInline,
    inlineButtonTypeUserProfile: api.inlineButtonTypeUserProfile,
    inputInlineButtonTypeUserProfile: api.inputInlineButtonTypeUserProfile,
    inlineButtonTypeCopy: api.inlineButtonTypeCopy,
    inlineButtonTypeDisabled: api.inlineButtonTypeDisabled,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inlineButtonTypeUrl.constructor_id => return .{ .inlineButtonTypeUrl = try api.inlineButtonTypeUrl.deserialize(allocator, r) },
            api.inlineButtonTypeUrlAuth.constructor_id => return .{ .inlineButtonTypeUrlAuth = try api.inlineButtonTypeUrlAuth.deserialize(allocator, r) },
            api.inputInlineButtonTypeUrlAuth.constructor_id => return .{ .inputInlineButtonTypeUrlAuth = try api.inputInlineButtonTypeUrlAuth.deserialize(allocator, r) },
            api.inlineButtonTypeWebView.constructor_id => return .{ .inlineButtonTypeWebView = try api.inlineButtonTypeWebView.deserialize(allocator, r) },
            api.inlineButtonTypeCallback.constructor_id => return .{ .inlineButtonTypeCallback = try api.inlineButtonTypeCallback.deserialize(allocator, r) },
            api.inlineButtonTypeGame.constructor_id => return .{ .inlineButtonTypeGame = try api.inlineButtonTypeGame.deserialize(allocator, r) },
            api.inlineButtonTypeBuy.constructor_id => return .{ .inlineButtonTypeBuy = try api.inlineButtonTypeBuy.deserialize(allocator, r) },
            api.inlineButtonTypeSwitchInline.constructor_id => return .{ .inlineButtonTypeSwitchInline = try api.inlineButtonTypeSwitchInline.deserialize(allocator, r) },
            api.inlineButtonTypeUserProfile.constructor_id => return .{ .inlineButtonTypeUserProfile = try api.inlineButtonTypeUserProfile.deserialize(allocator, r) },
            api.inputInlineButtonTypeUserProfile.constructor_id => return .{ .inputInlineButtonTypeUserProfile = try api.inputInlineButtonTypeUserProfile.deserialize(allocator, r) },
            api.inlineButtonTypeCopy.constructor_id => return .{ .inlineButtonTypeCopy = try api.inlineButtonTypeCopy.deserialize(allocator, r) },
            api.inlineButtonTypeDisabled.constructor_id => return .{ .inlineButtonTypeDisabled = try api.inlineButtonTypeDisabled.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const KeyboardInlineButton = union(enum) {
    keyboardInlineButton: api.keyboardInlineButton,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.keyboardInlineButton.constructor_id => return .{ .keyboardInlineButton = try api.keyboardInlineButton.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const KeyboardInlineButtonRow = union(enum) {
    keyboardInlineButtonRow: api.keyboardInlineButtonRow,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.keyboardInlineButtonRow.constructor_id => return .{ .keyboardInlineButtonRow = try api.keyboardInlineButtonRow.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const RichButtonStyle = union(enum) {
    richButtonStyle: api.richButtonStyle,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.richButtonStyle.constructor_id => return .{ .richButtonStyle = try api.richButtonStyle.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

