//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const communityPeer = struct {
    pub const constructor_id: u32 = 0x76141ebd;
    can_view_history: bool = false,
    visible: ?bool = null,
    peer: api.Peer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.can_view_history) flags |= 1 << 2;
        if (self.visible != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.visible) |v| {
            try w.writeBool(v);
        }
        try self.peer.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.can_view_history = (flags >> 2) & 1 != 0;
        if ((flags >> 0) & 1 != 0) {
            self.visible = try r.readBool();
        } else {
            self.visible = null;
        }
        self.peer = try api.Peer.deserialize(allocator, r);
        return self;
    }
};

pub const communityPeerRequest = struct {
    pub const constructor_id: u32 = 0x7beafa85;
    visible: bool = false,
    peer: api.Peer,
    requested_by: i64,
    date: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.visible) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.peer.serialize(w);
        try w.writeLong(self.requested_by);
        try w.writeInt(self.date);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.visible = (flags >> 0) & 1 != 0;
        self.peer = try api.Peer.deserialize(allocator, r);
        self.requested_by = try r.readLong();
        self.date = try r.readInt();
        return self;
    }
};

pub const peerLinkRequests = struct {
    pub const constructor_id: u32 = 0x2244afad;
    total_count: i32,
    requests: []api.CommunityPeerRequest,
    next_offset: ?[]const u8 = null,
    chats: []api.Chat,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.next_offset != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeInt(self.total_count);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.requests.len);
        for (self.requests) |elem_2567| {
            try elem_2567.serialize(w);
        }
        if (self.next_offset) |v| {
            try w.writeString(v);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_2568| {
            try elem_2568.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_2569| {
            try elem_2569.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.total_count = try r.readInt();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2570 = try r.readVectorLength();
        const vec_2571 = allocator.alloc(api.CommunityPeerRequest, len_2570) catch return error.OutOfMemory;
        for (vec_2571) |*elem_2572| {
            elem_2572.* = try api.CommunityPeerRequest.deserialize(allocator, r);
        }
        self.requests = vec_2571;
        if ((flags >> 0) & 1 != 0) {
            self.next_offset = try r.readString();
        } else {
            self.next_offset = null;
        }
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2573 = try r.readVectorLength();
        const vec_2574 = allocator.alloc(api.Chat, len_2573) catch return error.OutOfMemory;
        for (vec_2574) |*elem_2575| {
            elem_2575.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_2574;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2576 = try r.readVectorLength();
        const vec_2577 = allocator.alloc(api.User, len_2576) catch return error.OutOfMemory;
        for (vec_2577) |*elem_2578| {
            elem_2578.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_2577;
        return self;
    }
};

pub const participantJoinedChats = struct {
    pub const constructor_id: u32 = 0x8d78512a;
    creator_chat_ids: []i64,
    joined_chat_ids: []i64,
    chats: []api.Chat,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.creator_chat_ids.len);
        for (self.creator_chat_ids) |elem_2579| {
            try w.writeLong(elem_2579);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.joined_chat_ids.len);
        for (self.joined_chat_ids) |elem_2580| {
            try w.writeLong(elem_2580);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_2581| {
            try elem_2581.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_2582| {
            try elem_2582.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2583 = try r.readVectorLength();
        const vec_2584 = allocator.alloc(i64, len_2583) catch return error.OutOfMemory;
        for (vec_2584) |*elem_2585| {
            elem_2585.* = try r.readLong();
        }
        self.creator_chat_ids = vec_2584;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2586 = try r.readVectorLength();
        const vec_2587 = allocator.alloc(i64, len_2586) catch return error.OutOfMemory;
        for (vec_2587) |*elem_2588| {
            elem_2588.* = try r.readLong();
        }
        self.joined_chat_ids = vec_2587;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2589 = try r.readVectorLength();
        const vec_2590 = allocator.alloc(api.Chat, len_2589) catch return error.OutOfMemory;
        for (vec_2590) |*elem_2591| {
            elem_2591.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_2590;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2592 = try r.readVectorLength();
        const vec_2593 = allocator.alloc(api.User, len_2592) catch return error.OutOfMemory;
        for (vec_2593) |*elem_2594| {
            elem_2594.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_2593;
        return self;
    }
};

pub const CommunityPeer = union(enum) {
    communityPeer: api.communityPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.communityPeer.constructor_id => return .{ .communityPeer = try api.communityPeer.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const CommunityPeerRequest = union(enum) {
    communityPeerRequest: api.communityPeerRequest,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.communityPeerRequest.constructor_id => return .{ .communityPeerRequest = try api.communityPeerRequest.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PeerLinkRequests = union(enum) {
    peerLinkRequests: api.communities.peerLinkRequests,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.communities.peerLinkRequests.constructor_id => return .{ .peerLinkRequests = try api.communities.peerLinkRequests.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const ParticipantJoinedChats = union(enum) {
    participantJoinedChats: api.communities.participantJoinedChats,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.communities.participantJoinedChats.constructor_id => return .{ .participantJoinedChats = try api.communities.participantJoinedChats.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

