//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const inputFile = struct {
    pub const constructor_id: u32 = 0xf52ff27f;
    id: i64,
    parts: i32,
    name: []const u8,
    md5_checksum: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeInt(self.parts);
        try w.writeString(self.name);
        try w.writeString(self.md5_checksum);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.parts = try r.readInt();
        self.name = try r.readString();
        self.md5_checksum = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inputFileBig = struct {
    pub const constructor_id: u32 = 0xfa4f0bb5;
    id: i64,
    parts: i32,
    name: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeInt(self.parts);
        try w.writeString(self.name);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.parts = try r.readInt();
        self.name = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inputFileStoryDocument = struct {
    pub const constructor_id: u32 = 0x62dc8b48;
    id: api.InputDocument,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.id.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try api.InputDocument.deserialize(allocator, r);
        return self;
    }
};

pub const inputFileLocation = struct {
    pub const constructor_id: u32 = 0xdfdaabe1;
    volume_id: i64,
    local_id: i32,
    secret: i64,
    file_reference: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.volume_id);
        try w.writeInt(self.local_id);
        try w.writeLong(self.secret);
        try w.writeBytes(self.file_reference);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.volume_id = try r.readLong();
        self.local_id = try r.readInt();
        self.secret = try r.readLong();
        self.file_reference = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const inputEncryptedFileLocation = struct {
    pub const constructor_id: u32 = 0xf5235d55;
    id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputDocumentFileLocation = struct {
    pub const constructor_id: u32 = 0xbad07584;
    id: i64,
    access_hash: i64,
    file_reference: []const u8,
    thumb_size: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeBytes(self.file_reference);
        try w.writeString(self.thumb_size);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.file_reference = try r.readBytes();
        self.thumb_size = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inputSecureFileLocation = struct {
    pub const constructor_id: u32 = 0xcbc7ee28;
    id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputTakeoutFileLocation = struct {
    pub const constructor_id: u32 = 0x29be5899;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputPhotoFileLocation = struct {
    pub const constructor_id: u32 = 0x40181ffe;
    id: i64,
    access_hash: i64,
    file_reference: []const u8,
    thumb_size: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeBytes(self.file_reference);
        try w.writeString(self.thumb_size);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.file_reference = try r.readBytes();
        self.thumb_size = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inputPhotoLegacyFileLocation = struct {
    pub const constructor_id: u32 = 0xd83466f3;
    id: i64,
    access_hash: i64,
    file_reference: []const u8,
    volume_id: i64,
    local_id: i32,
    secret: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeBytes(self.file_reference);
        try w.writeLong(self.volume_id);
        try w.writeInt(self.local_id);
        try w.writeLong(self.secret);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.file_reference = try r.readBytes();
        self.volume_id = try r.readLong();
        self.local_id = try r.readInt();
        self.secret = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputPeerPhotoFileLocation = struct {
    pub const constructor_id: u32 = 0x37257e99;
    big: bool = false,
    peer: *api.InputPeer,
    photo_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.big) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.peer.serialize(w);
        try w.writeLong(self.photo_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.big = (flags >> 0) & 1 != 0;
                const ptr_143 = allocator.create(api.InputPeer) catch return error.OutOfMemory;
        ptr_143.* = try api.InputPeer.deserialize(allocator, r);
        self.peer = ptr_143;
        self.photo_id = try r.readLong();
        return self;
    }
};

pub const inputStickerSetThumb = struct {
    pub const constructor_id: u32 = 0x9d84f3db;
    stickerset: api.InputStickerSet,
    thumb_version: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.stickerset.serialize(w);
        try w.writeInt(self.thumb_version);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.stickerset = try api.InputStickerSet.deserialize(allocator, r);
        self.thumb_version = try r.readInt();
        return self;
    }
};

pub const inputGroupCallStream = struct {
    pub const constructor_id: u32 = 0x0598a92a;
    call: api.InputGroupCall,
    time_ms: i64,
    scale: i32,
    video_channel: ?i32 = null,
    video_quality: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.video_channel != null) flags |= 1 << 0;
        if (self.video_quality != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.call.serialize(w);
        try w.writeLong(self.time_ms);
        try w.writeInt(self.scale);
        if (self.video_channel) |v| {
            try w.writeInt(v);
        }
        if (self.video_quality) |v| {
            try w.writeInt(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.call = try api.InputGroupCall.deserialize(allocator, r);
        self.time_ms = try r.readLong();
        self.scale = try r.readInt();
        if ((flags >> 0) & 1 != 0) {
            self.video_channel = try r.readInt();
        } else {
            self.video_channel = null;
        }
        if ((flags >> 0) & 1 != 0) {
            self.video_quality = try r.readInt();
        } else {
            self.video_quality = null;
        }
        return self;
    }
};

pub const fileUnknown = struct {
    pub const constructor_id: u32 = 0xaa963b05;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const filePartial = struct {
    pub const constructor_id: u32 = 0x40bc6f52;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const fileJpeg = struct {
    pub const constructor_id: u32 = 0x007efe0e;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const fileGif = struct {
    pub const constructor_id: u32 = 0xcae1aadf;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const filePng = struct {
    pub const constructor_id: u32 = 0x0a4f63c0;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const filePdf = struct {
    pub const constructor_id: u32 = 0xae1e508d;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const fileMp3 = struct {
    pub const constructor_id: u32 = 0x528a0677;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const fileMov = struct {
    pub const constructor_id: u32 = 0x4b09ebbc;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const fileMp4 = struct {
    pub const constructor_id: u32 = 0xb3cea0e4;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const fileWebp = struct {
    pub const constructor_id: u32 = 0x1081464c;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const file = struct {
    pub const constructor_id: u32 = 0x096a18d5;
    type_: api.storage.FileType,
    mtime: i32,
    bytes: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeInt(self.mtime);
        try w.writeBytes(self.bytes);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.storage.FileType.deserialize(allocator, r);
        self.mtime = try r.readInt();
        self.bytes = try r.readBytes();
        return self;
    }
};

pub const fileCdnRedirect = struct {
    pub const constructor_id: u32 = 0xf18cda44;
    dc_id: i32,
    file_token: []const u8,
    encryption_key: []const u8,
    encryption_iv: []const u8,
    file_hashes: []api.FileHash,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.dc_id);
        try w.writeBytes(self.file_token);
        try w.writeBytes(self.encryption_key);
        try w.writeBytes(self.encryption_iv);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.file_hashes.len);
        for (self.file_hashes) |elem_144| {
            try elem_144.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.dc_id = try r.readInt();
        self.file_token = try r.readBytes();
        self.encryption_key = try r.readBytes();
        self.encryption_iv = try r.readBytes();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_145 = try r.readVectorLength();
        const vec_146 = allocator.alloc(api.FileHash, len_145) catch return error.OutOfMemory;
        for (vec_146) |*elem_147| {
            elem_147.* = try api.FileHash.deserialize(allocator, r);
        }
        self.file_hashes = vec_146;
        return self;
    }
};

pub const dcOption = struct {
    pub const constructor_id: u32 = 0x18b7a10d;
    ipv6: bool = false,
    media_only: bool = false,
    tcpo_only: bool = false,
    cdn: bool = false,
    static: bool = false,
    this_port_only: bool = false,
    id: i32,
    ip_address: []const u8,
    port: i32,
    secret: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.ipv6) flags |= 1 << 0;
        if (self.media_only) flags |= 1 << 1;
        if (self.tcpo_only) flags |= 1 << 2;
        if (self.cdn) flags |= 1 << 3;
        if (self.static) flags |= 1 << 4;
        if (self.this_port_only) flags |= 1 << 5;
        if (self.secret != null) flags |= 1 << 10;
        try w.writeUInt(flags);
        try w.writeInt(self.id);
        try w.writeString(self.ip_address);
        try w.writeInt(self.port);
        if (self.secret) |v| {
            try w.writeBytes(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.ipv6 = (flags >> 0) & 1 != 0;
        self.media_only = (flags >> 1) & 1 != 0;
        self.tcpo_only = (flags >> 2) & 1 != 0;
        self.cdn = (flags >> 3) & 1 != 0;
        self.static = (flags >> 4) & 1 != 0;
        self.this_port_only = (flags >> 5) & 1 != 0;
        self.id = try r.readInt();
        self.ip_address = try r.readString();
        self.port = try r.readInt();
        if ((flags >> 10) & 1 != 0) {
            self.secret = try r.readBytes();
        } else {
            self.secret = null;
        }
        _ = allocator;
        return self;
    }
};

pub const encryptedFileEmpty = struct {
    pub const constructor_id: u32 = 0xc21f497e;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const encryptedFile = struct {
    pub const constructor_id: u32 = 0xa8008cd8;
    id: i64,
    access_hash: i64,
    size: i64,
    dc_id: i32,
    key_fingerprint: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeLong(self.size);
        try w.writeInt(self.dc_id);
        try w.writeInt(self.key_fingerprint);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.size = try r.readLong();
        self.dc_id = try r.readInt();
        self.key_fingerprint = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const inputEncryptedFileEmpty = struct {
    pub const constructor_id: u32 = 0x1837c364;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputEncryptedFileUploaded = struct {
    pub const constructor_id: u32 = 0x64bd0306;
    id: i64,
    parts: i32,
    md5_checksum: []const u8,
    key_fingerprint: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeInt(self.parts);
        try w.writeString(self.md5_checksum);
        try w.writeInt(self.key_fingerprint);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.parts = try r.readInt();
        self.md5_checksum = try r.readString();
        self.key_fingerprint = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const inputEncryptedFile = struct {
    pub const constructor_id: u32 = 0x5a17b5e5;
    id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputEncryptedFileBigUploaded = struct {
    pub const constructor_id: u32 = 0x2dc173c8;
    id: i64,
    parts: i32,
    key_fingerprint: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeInt(self.parts);
        try w.writeInt(self.key_fingerprint);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.parts = try r.readInt();
        self.key_fingerprint = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const inputWebFileLocation = struct {
    pub const constructor_id: u32 = 0xc239d686;
    url: []const u8,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputWebFileGeoPointLocation = struct {
    pub const constructor_id: u32 = 0x9f2221c9;
    geo_point: api.InputGeoPoint,
    access_hash: i64,
    w: i32,
    h: i32,
    zoom: i32,
    scale: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.geo_point.serialize(w);
        try w.writeLong(self.access_hash);
        try w.writeInt(self.w);
        try w.writeInt(self.h);
        try w.writeInt(self.zoom);
        try w.writeInt(self.scale);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.geo_point = try api.InputGeoPoint.deserialize(allocator, r);
        self.access_hash = try r.readLong();
        self.w = try r.readInt();
        self.h = try r.readInt();
        self.zoom = try r.readInt();
        self.scale = try r.readInt();
        return self;
    }
};

pub const inputWebFileAudioAlbumThumbLocation = struct {
    pub const constructor_id: u32 = 0xf46fe924;
    small: bool = false,
    document: ?api.InputDocument = null,
    title: ?[]const u8 = null,
    performer: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.small) flags |= 1 << 2;
        if (self.document != null) flags |= 1 << 0;
        if (self.title != null) flags |= 1 << 1;
        if (self.performer != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        if (self.document) |v| {
            try v.serialize(w);
        }
        if (self.title) |v| {
            try w.writeString(v);
        }
        if (self.performer) |v| {
            try w.writeString(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.small = (flags >> 2) & 1 != 0;
        if ((flags >> 0) & 1 != 0) {
            self.document = try api.InputDocument.deserialize(allocator, r);
        } else {
            self.document = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.title = try r.readString();
        } else {
            self.title = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.performer = try r.readString();
        } else {
            self.performer = null;
        }
        return self;
    }
};

pub const webFile = struct {
    pub const constructor_id: u32 = 0x21e753bc;
    size: i32,
    mime_type: []const u8,
    file_type: api.storage.FileType,
    mtime: i32,
    bytes: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.size);
        try w.writeString(self.mime_type);
        try self.file_type.serialize(w);
        try w.writeInt(self.mtime);
        try w.writeBytes(self.bytes);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.size = try r.readInt();
        self.mime_type = try r.readString();
        self.file_type = try api.storage.FileType.deserialize(allocator, r);
        self.mtime = try r.readInt();
        self.bytes = try r.readBytes();
        return self;
    }
};

pub const cdnFileReuploadNeeded = struct {
    pub const constructor_id: u32 = 0xeea8e46e;
    request_token: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeBytes(self.request_token);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.request_token = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const cdnFile = struct {
    pub const constructor_id: u32 = 0xa99fca4f;
    bytes: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeBytes(self.bytes);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.bytes = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const cdnPublicKey = struct {
    pub const constructor_id: u32 = 0xc982eaba;
    dc_id: i32,
    public_key: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.dc_id);
        try w.writeString(self.public_key);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.dc_id = try r.readInt();
        self.public_key = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const cdnConfig = struct {
    pub const constructor_id: u32 = 0x5725e40a;
    public_keys: []api.CdnPublicKey,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.public_keys.len);
        for (self.public_keys) |elem_148| {
            try elem_148.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_149 = try r.readVectorLength();
        const vec_150 = allocator.alloc(api.CdnPublicKey, len_149) catch return error.OutOfMemory;
        for (vec_150) |*elem_151| {
            elem_151.* = try api.CdnPublicKey.deserialize(allocator, r);
        }
        self.public_keys = vec_150;
        return self;
    }
};

pub const fileHash = struct {
    pub const constructor_id: u32 = 0xf39b035c;
    offset: i64,
    limit: i32,
    hash: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.offset);
        try w.writeInt(self.limit);
        try w.writeBytes(self.hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.offset = try r.readLong();
        self.limit = try r.readInt();
        self.hash = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const InputFile = union(enum) {
    inputFile: api.inputFile,
    inputFileBig: api.inputFileBig,
    inputFileStoryDocument: api.inputFileStoryDocument,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputFile.constructor_id => return .{ .inputFile = try api.inputFile.deserialize(allocator, r) },
            api.inputFileBig.constructor_id => return .{ .inputFileBig = try api.inputFileBig.deserialize(allocator, r) },
            api.inputFileStoryDocument.constructor_id => return .{ .inputFileStoryDocument = try api.inputFileStoryDocument.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputFileLocation = union(enum) {
    inputFileLocation: api.inputFileLocation,
    inputEncryptedFileLocation: api.inputEncryptedFileLocation,
    inputDocumentFileLocation: api.inputDocumentFileLocation,
    inputSecureFileLocation: api.inputSecureFileLocation,
    inputTakeoutFileLocation: api.inputTakeoutFileLocation,
    inputPhotoFileLocation: api.inputPhotoFileLocation,
    inputPhotoLegacyFileLocation: api.inputPhotoLegacyFileLocation,
    inputPeerPhotoFileLocation: api.inputPeerPhotoFileLocation,
    inputStickerSetThumb: api.inputStickerSetThumb,
    inputGroupCallStream: api.inputGroupCallStream,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputFileLocation.constructor_id => return .{ .inputFileLocation = try api.inputFileLocation.deserialize(allocator, r) },
            api.inputEncryptedFileLocation.constructor_id => return .{ .inputEncryptedFileLocation = try api.inputEncryptedFileLocation.deserialize(allocator, r) },
            api.inputDocumentFileLocation.constructor_id => return .{ .inputDocumentFileLocation = try api.inputDocumentFileLocation.deserialize(allocator, r) },
            api.inputSecureFileLocation.constructor_id => return .{ .inputSecureFileLocation = try api.inputSecureFileLocation.deserialize(allocator, r) },
            api.inputTakeoutFileLocation.constructor_id => return .{ .inputTakeoutFileLocation = try api.inputTakeoutFileLocation.deserialize(allocator, r) },
            api.inputPhotoFileLocation.constructor_id => return .{ .inputPhotoFileLocation = try api.inputPhotoFileLocation.deserialize(allocator, r) },
            api.inputPhotoLegacyFileLocation.constructor_id => return .{ .inputPhotoLegacyFileLocation = try api.inputPhotoLegacyFileLocation.deserialize(allocator, r) },
            api.inputPeerPhotoFileLocation.constructor_id => return .{ .inputPeerPhotoFileLocation = try api.inputPeerPhotoFileLocation.deserialize(allocator, r) },
            api.inputStickerSetThumb.constructor_id => return .{ .inputStickerSetThumb = try api.inputStickerSetThumb.deserialize(allocator, r) },
            api.inputGroupCallStream.constructor_id => return .{ .inputGroupCallStream = try api.inputGroupCallStream.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const FileType = union(enum) {
    fileUnknown: api.storage.fileUnknown,
    filePartial: api.storage.filePartial,
    fileJpeg: api.storage.fileJpeg,
    fileGif: api.storage.fileGif,
    filePng: api.storage.filePng,
    filePdf: api.storage.filePdf,
    fileMp3: api.storage.fileMp3,
    fileMov: api.storage.fileMov,
    fileMp4: api.storage.fileMp4,
    fileWebp: api.storage.fileWebp,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.storage.fileUnknown.constructor_id => return .{ .fileUnknown = try api.storage.fileUnknown.deserialize(allocator, r) },
            api.storage.filePartial.constructor_id => return .{ .filePartial = try api.storage.filePartial.deserialize(allocator, r) },
            api.storage.fileJpeg.constructor_id => return .{ .fileJpeg = try api.storage.fileJpeg.deserialize(allocator, r) },
            api.storage.fileGif.constructor_id => return .{ .fileGif = try api.storage.fileGif.deserialize(allocator, r) },
            api.storage.filePng.constructor_id => return .{ .filePng = try api.storage.filePng.deserialize(allocator, r) },
            api.storage.filePdf.constructor_id => return .{ .filePdf = try api.storage.filePdf.deserialize(allocator, r) },
            api.storage.fileMp3.constructor_id => return .{ .fileMp3 = try api.storage.fileMp3.deserialize(allocator, r) },
            api.storage.fileMov.constructor_id => return .{ .fileMov = try api.storage.fileMov.deserialize(allocator, r) },
            api.storage.fileMp4.constructor_id => return .{ .fileMp4 = try api.storage.fileMp4.deserialize(allocator, r) },
            api.storage.fileWebp.constructor_id => return .{ .fileWebp = try api.storage.fileWebp.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const File = union(enum) {
    file: api.upload.file,
    fileCdnRedirect: api.upload.fileCdnRedirect,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.upload.file.constructor_id => return .{ .file = try api.upload.file.deserialize(allocator, r) },
            api.upload.fileCdnRedirect.constructor_id => return .{ .fileCdnRedirect = try api.upload.fileCdnRedirect.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const DcOption = union(enum) {
    dcOption: api.dcOption,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.dcOption.constructor_id => return .{ .dcOption = try api.dcOption.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const EncryptedFile = union(enum) {
    encryptedFileEmpty: api.encryptedFileEmpty,
    encryptedFile: api.encryptedFile,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.encryptedFileEmpty.constructor_id => return .{ .encryptedFileEmpty = try api.encryptedFileEmpty.deserialize(allocator, r) },
            api.encryptedFile.constructor_id => return .{ .encryptedFile = try api.encryptedFile.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputEncryptedFile = union(enum) {
    inputEncryptedFileEmpty: api.inputEncryptedFileEmpty,
    inputEncryptedFileUploaded: api.inputEncryptedFileUploaded,
    inputEncryptedFile: api.inputEncryptedFile,
    inputEncryptedFileBigUploaded: api.inputEncryptedFileBigUploaded,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputEncryptedFileEmpty.constructor_id => return .{ .inputEncryptedFileEmpty = try api.inputEncryptedFileEmpty.deserialize(allocator, r) },
            api.inputEncryptedFileUploaded.constructor_id => return .{ .inputEncryptedFileUploaded = try api.inputEncryptedFileUploaded.deserialize(allocator, r) },
            api.inputEncryptedFile.constructor_id => return .{ .inputEncryptedFile = try api.inputEncryptedFile.deserialize(allocator, r) },
            api.inputEncryptedFileBigUploaded.constructor_id => return .{ .inputEncryptedFileBigUploaded = try api.inputEncryptedFileBigUploaded.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputWebFileLocation = union(enum) {
    inputWebFileLocation: api.inputWebFileLocation,
    inputWebFileGeoPointLocation: api.inputWebFileGeoPointLocation,
    inputWebFileAudioAlbumThumbLocation: api.inputWebFileAudioAlbumThumbLocation,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputWebFileLocation.constructor_id => return .{ .inputWebFileLocation = try api.inputWebFileLocation.deserialize(allocator, r) },
            api.inputWebFileGeoPointLocation.constructor_id => return .{ .inputWebFileGeoPointLocation = try api.inputWebFileGeoPointLocation.deserialize(allocator, r) },
            api.inputWebFileAudioAlbumThumbLocation.constructor_id => return .{ .inputWebFileAudioAlbumThumbLocation = try api.inputWebFileAudioAlbumThumbLocation.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const WebFile = union(enum) {
    webFile: api.upload.webFile,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.upload.webFile.constructor_id => return .{ .webFile = try api.upload.webFile.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const CdnFile = union(enum) {
    cdnFileReuploadNeeded: api.upload.cdnFileReuploadNeeded,
    cdnFile: api.upload.cdnFile,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.upload.cdnFileReuploadNeeded.constructor_id => return .{ .cdnFileReuploadNeeded = try api.upload.cdnFileReuploadNeeded.deserialize(allocator, r) },
            api.upload.cdnFile.constructor_id => return .{ .cdnFile = try api.upload.cdnFile.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const CdnPublicKey = union(enum) {
    cdnPublicKey: api.cdnPublicKey,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.cdnPublicKey.constructor_id => return .{ .cdnPublicKey = try api.cdnPublicKey.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const CdnConfig = union(enum) {
    cdnConfig: api.cdnConfig,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.cdnConfig.constructor_id => return .{ .cdnConfig = try api.cdnConfig.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const FileHash = union(enum) {
    fileHash: api.fileHash,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.fileHash.constructor_id => return .{ .fileHash = try api.fileHash.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

