//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const config = struct {
    pub const constructor_id: u32 = 0xcc1a241e;
    default_p2p_contacts: bool = false,
    preload_featured_stickers: bool = false,
    revoke_pm_inbox: bool = false,
    blocked_mode: bool = false,
    force_try_ipv6: bool = false,
    date: i32,
    expires: i32,
    test_mode: bool,
    this_dc: i32,
    dc_options: []api.DcOption,
    dc_txt_domain_name: []const u8,
    chat_size_max: i32,
    megagroup_size_max: i32,
    forwarded_count_max: i32,
    online_update_period_ms: i32,
    offline_blur_timeout_ms: i32,
    offline_idle_timeout_ms: i32,
    online_cloud_timeout_ms: i32,
    notify_cloud_delay_ms: i32,
    notify_default_delay_ms: i32,
    push_chat_period_ms: i32,
    push_chat_limit: i32,
    edit_time_limit: i32,
    revoke_time_limit: i32,
    revoke_pm_time_limit: i32,
    rating_e_decay: i32,
    stickers_recent_limit: i32,
    channels_read_media_period: i32,
    tmp_sessions: ?i32 = null,
    call_receive_timeout_ms: i32,
    call_ring_timeout_ms: i32,
    call_connect_timeout_ms: i32,
    call_packet_timeout_ms: i32,
    me_url_prefix: []const u8,
    autoupdate_url_prefix: ?[]const u8 = null,
    gif_search_username: ?[]const u8 = null,
    venue_search_username: ?[]const u8 = null,
    img_search_username: ?[]const u8 = null,
    static_maps_provider: ?[]const u8 = null,
    caption_length_max: i32,
    message_length_max: i32,
    webfile_dc_id: i32,
    suggested_lang_code: ?[]const u8 = null,
    lang_pack_version: ?i32 = null,
    base_lang_pack_version: ?i32 = null,
    reactions_default: ?api.Reaction = null,
    autologin_token: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.default_p2p_contacts) flags |= 1 << 3;
        if (self.preload_featured_stickers) flags |= 1 << 4;
        if (self.revoke_pm_inbox) flags |= 1 << 6;
        if (self.blocked_mode) flags |= 1 << 8;
        if (self.force_try_ipv6) flags |= 1 << 14;
        if (self.tmp_sessions != null) flags |= 1 << 0;
        if (self.autoupdate_url_prefix != null) flags |= 1 << 7;
        if (self.gif_search_username != null) flags |= 1 << 9;
        if (self.venue_search_username != null) flags |= 1 << 10;
        if (self.img_search_username != null) flags |= 1 << 11;
        if (self.static_maps_provider != null) flags |= 1 << 12;
        if (self.suggested_lang_code != null) flags |= 1 << 2;
        if (self.lang_pack_version != null) flags |= 1 << 2;
        if (self.base_lang_pack_version != null) flags |= 1 << 2;
        if (self.reactions_default != null) flags |= 1 << 15;
        if (self.autologin_token != null) flags |= 1 << 16;
        try w.writeUInt(flags);
        try w.writeInt(self.date);
        try w.writeInt(self.expires);
        try w.writeBool(self.test_mode);
        try w.writeInt(self.this_dc);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.dc_options.len);
        for (self.dc_options) |elem_1302| {
            try elem_1302.serialize(w);
        }
        try w.writeString(self.dc_txt_domain_name);
        try w.writeInt(self.chat_size_max);
        try w.writeInt(self.megagroup_size_max);
        try w.writeInt(self.forwarded_count_max);
        try w.writeInt(self.online_update_period_ms);
        try w.writeInt(self.offline_blur_timeout_ms);
        try w.writeInt(self.offline_idle_timeout_ms);
        try w.writeInt(self.online_cloud_timeout_ms);
        try w.writeInt(self.notify_cloud_delay_ms);
        try w.writeInt(self.notify_default_delay_ms);
        try w.writeInt(self.push_chat_period_ms);
        try w.writeInt(self.push_chat_limit);
        try w.writeInt(self.edit_time_limit);
        try w.writeInt(self.revoke_time_limit);
        try w.writeInt(self.revoke_pm_time_limit);
        try w.writeInt(self.rating_e_decay);
        try w.writeInt(self.stickers_recent_limit);
        try w.writeInt(self.channels_read_media_period);
        if (self.tmp_sessions) |v| {
            try w.writeInt(v);
        }
        try w.writeInt(self.call_receive_timeout_ms);
        try w.writeInt(self.call_ring_timeout_ms);
        try w.writeInt(self.call_connect_timeout_ms);
        try w.writeInt(self.call_packet_timeout_ms);
        try w.writeString(self.me_url_prefix);
        if (self.autoupdate_url_prefix) |v| {
            try w.writeString(v);
        }
        if (self.gif_search_username) |v| {
            try w.writeString(v);
        }
        if (self.venue_search_username) |v| {
            try w.writeString(v);
        }
        if (self.img_search_username) |v| {
            try w.writeString(v);
        }
        if (self.static_maps_provider) |v| {
            try w.writeString(v);
        }
        try w.writeInt(self.caption_length_max);
        try w.writeInt(self.message_length_max);
        try w.writeInt(self.webfile_dc_id);
        if (self.suggested_lang_code) |v| {
            try w.writeString(v);
        }
        if (self.lang_pack_version) |v| {
            try w.writeInt(v);
        }
        if (self.base_lang_pack_version) |v| {
            try w.writeInt(v);
        }
        if (self.reactions_default) |v| {
            try v.serialize(w);
        }
        if (self.autologin_token) |v| {
            try w.writeString(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.default_p2p_contacts = (flags >> 3) & 1 != 0;
        self.preload_featured_stickers = (flags >> 4) & 1 != 0;
        self.revoke_pm_inbox = (flags >> 6) & 1 != 0;
        self.blocked_mode = (flags >> 8) & 1 != 0;
        self.force_try_ipv6 = (flags >> 14) & 1 != 0;
        self.date = try r.readInt();
        self.expires = try r.readInt();
        self.test_mode = try r.readBool();
        self.this_dc = try r.readInt();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1303 = try r.readVectorLength();
        const vec_1304 = allocator.alloc(api.DcOption, len_1303) catch return error.OutOfMemory;
        for (vec_1304) |*elem_1305| {
            elem_1305.* = try api.DcOption.deserialize(allocator, r);
        }
        self.dc_options = vec_1304;
        self.dc_txt_domain_name = try r.readString();
        self.chat_size_max = try r.readInt();
        self.megagroup_size_max = try r.readInt();
        self.forwarded_count_max = try r.readInt();
        self.online_update_period_ms = try r.readInt();
        self.offline_blur_timeout_ms = try r.readInt();
        self.offline_idle_timeout_ms = try r.readInt();
        self.online_cloud_timeout_ms = try r.readInt();
        self.notify_cloud_delay_ms = try r.readInt();
        self.notify_default_delay_ms = try r.readInt();
        self.push_chat_period_ms = try r.readInt();
        self.push_chat_limit = try r.readInt();
        self.edit_time_limit = try r.readInt();
        self.revoke_time_limit = try r.readInt();
        self.revoke_pm_time_limit = try r.readInt();
        self.rating_e_decay = try r.readInt();
        self.stickers_recent_limit = try r.readInt();
        self.channels_read_media_period = try r.readInt();
        if ((flags >> 0) & 1 != 0) {
            self.tmp_sessions = try r.readInt();
        } else {
            self.tmp_sessions = null;
        }
        self.call_receive_timeout_ms = try r.readInt();
        self.call_ring_timeout_ms = try r.readInt();
        self.call_connect_timeout_ms = try r.readInt();
        self.call_packet_timeout_ms = try r.readInt();
        self.me_url_prefix = try r.readString();
        if ((flags >> 7) & 1 != 0) {
            self.autoupdate_url_prefix = try r.readString();
        } else {
            self.autoupdate_url_prefix = null;
        }
        if ((flags >> 9) & 1 != 0) {
            self.gif_search_username = try r.readString();
        } else {
            self.gif_search_username = null;
        }
        if ((flags >> 10) & 1 != 0) {
            self.venue_search_username = try r.readString();
        } else {
            self.venue_search_username = null;
        }
        if ((flags >> 11) & 1 != 0) {
            self.img_search_username = try r.readString();
        } else {
            self.img_search_username = null;
        }
        if ((flags >> 12) & 1 != 0) {
            self.static_maps_provider = try r.readString();
        } else {
            self.static_maps_provider = null;
        }
        self.caption_length_max = try r.readInt();
        self.message_length_max = try r.readInt();
        self.webfile_dc_id = try r.readInt();
        if ((flags >> 2) & 1 != 0) {
            self.suggested_lang_code = try r.readString();
        } else {
            self.suggested_lang_code = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.lang_pack_version = try r.readInt();
        } else {
            self.lang_pack_version = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.base_lang_pack_version = try r.readInt();
        } else {
            self.base_lang_pack_version = null;
        }
        if ((flags >> 15) & 1 != 0) {
            self.reactions_default = try api.Reaction.deserialize(allocator, r);
        } else {
            self.reactions_default = null;
        }
        if ((flags >> 16) & 1 != 0) {
            self.autologin_token = try r.readString();
        } else {
            self.autologin_token = null;
        }
        return self;
    }
};

pub const nearestDc = struct {
    pub const constructor_id: u32 = 0x8e1a1775;
    country: []const u8,
    this_dc: i32,
    nearest_dc: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.country);
        try w.writeInt(self.this_dc);
        try w.writeInt(self.nearest_dc);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.country = try r.readString();
        self.this_dc = try r.readInt();
        self.nearest_dc = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const appUpdate = struct {
    pub const constructor_id: u32 = 0xccbbce30;
    can_not_skip: bool = false,
    id: i32,
    version: []const u8,
    text: []const u8,
    entities: []api.MessageEntity,
    document: ?api.Document = null,
    url: ?[]const u8 = null,
    sticker: ?api.Document = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.can_not_skip) flags |= 1 << 0;
        if (self.document != null) flags |= 1 << 1;
        if (self.url != null) flags |= 1 << 2;
        if (self.sticker != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        try w.writeInt(self.id);
        try w.writeString(self.version);
        try w.writeString(self.text);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.entities.len);
        for (self.entities) |elem_1306| {
            try elem_1306.serialize(w);
        }
        if (self.document) |v| {
            try v.serialize(w);
        }
        if (self.url) |v| {
            try w.writeString(v);
        }
        if (self.sticker) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.can_not_skip = (flags >> 0) & 1 != 0;
        self.id = try r.readInt();
        self.version = try r.readString();
        self.text = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1307 = try r.readVectorLength();
        const vec_1308 = allocator.alloc(api.MessageEntity, len_1307) catch return error.OutOfMemory;
        for (vec_1308) |*elem_1309| {
            elem_1309.* = try api.MessageEntity.deserialize(allocator, r);
        }
        self.entities = vec_1308;
        if ((flags >> 1) & 1 != 0) {
            self.document = try api.Document.deserialize(allocator, r);
        } else {
            self.document = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.url = try r.readString();
        } else {
            self.url = null;
        }
        if ((flags >> 3) & 1 != 0) {
            self.sticker = try api.Document.deserialize(allocator, r);
        } else {
            self.sticker = null;
        }
        return self;
    }
};

pub const noAppUpdate = struct {
    pub const constructor_id: u32 = 0xc45a6536;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inviteText = struct {
    pub const constructor_id: u32 = 0x18cb9f78;
    message: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.message);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.message = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const support = struct {
    pub const constructor_id: u32 = 0x17c6b5f6;
    phone_number: []const u8,
    user: api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.phone_number);
        try self.user.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.phone_number = try r.readString();
        self.user = try api.User.deserialize(allocator, r);
        return self;
    }
};

pub const termsOfService = struct {
    pub const constructor_id: u32 = 0x780a0310;
    popup: bool = false,
    id: api.DataJSON,
    text: []const u8,
    entities: []api.MessageEntity,
    min_age_confirm: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.popup) flags |= 1 << 0;
        if (self.min_age_confirm != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.id.serialize(w);
        try w.writeString(self.text);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.entities.len);
        for (self.entities) |elem_1310| {
            try elem_1310.serialize(w);
        }
        if (self.min_age_confirm) |v| {
            try w.writeInt(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.popup = (flags >> 0) & 1 != 0;
        self.id = try api.DataJSON.deserialize(allocator, r);
        self.text = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1311 = try r.readVectorLength();
        const vec_1312 = allocator.alloc(api.MessageEntity, len_1311) catch return error.OutOfMemory;
        for (vec_1312) |*elem_1313| {
            elem_1313.* = try api.MessageEntity.deserialize(allocator, r);
        }
        self.entities = vec_1312;
        if ((flags >> 1) & 1 != 0) {
            self.min_age_confirm = try r.readInt();
        } else {
            self.min_age_confirm = null;
        }
        return self;
    }
};

pub const recentMeUrlUnknown = struct {
    pub const constructor_id: u32 = 0x46e1d13d;
    url: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const recentMeUrlUser = struct {
    pub const constructor_id: u32 = 0xb92c09e2;
    url: []const u8,
    user_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
        try w.writeLong(self.user_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        self.user_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const recentMeUrlChat = struct {
    pub const constructor_id: u32 = 0xb2da71d2;
    url: []const u8,
    chat_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
        try w.writeLong(self.chat_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        self.chat_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const recentMeUrlChatInvite = struct {
    pub const constructor_id: u32 = 0xeb49081d;
    url: []const u8,
    chat_invite: api.ChatInvite,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
        try self.chat_invite.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        self.chat_invite = try api.ChatInvite.deserialize(allocator, r);
        return self;
    }
};

pub const recentMeUrlStickerSet = struct {
    pub const constructor_id: u32 = 0xbc0a57dc;
    url: []const u8,
    set: api.StickerSetCovered,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
        try self.set.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        self.set = try api.StickerSetCovered.deserialize(allocator, r);
        return self;
    }
};

pub const recentMeUrls = struct {
    pub const constructor_id: u32 = 0x0e0310d7;
    urls: []api.RecentMeUrl,
    chats: []api.Chat,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.urls.len);
        for (self.urls) |elem_1314| {
            try elem_1314.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_1315| {
            try elem_1315.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1316| {
            try elem_1316.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1317 = try r.readVectorLength();
        const vec_1318 = allocator.alloc(api.RecentMeUrl, len_1317) catch return error.OutOfMemory;
        for (vec_1318) |*elem_1319| {
            elem_1319.* = try api.RecentMeUrl.deserialize(allocator, r);
        }
        self.urls = vec_1318;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1320 = try r.readVectorLength();
        const vec_1321 = allocator.alloc(api.Chat, len_1320) catch return error.OutOfMemory;
        for (vec_1321) |*elem_1322| {
            elem_1322.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_1321;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1323 = try r.readVectorLength();
        const vec_1324 = allocator.alloc(api.User, len_1323) catch return error.OutOfMemory;
        for (vec_1324) |*elem_1325| {
            elem_1325.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1324;
        return self;
    }
};

pub const termsOfServiceUpdateEmpty = struct {
    pub const constructor_id: u32 = 0xe3309f7f;
    expires: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.expires);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.expires = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const termsOfServiceUpdate = struct {
    pub const constructor_id: u32 = 0x28ecf961;
    expires: i32,
    terms_of_service: api.help.TermsOfService,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.expires);
        try self.terms_of_service.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.expires = try r.readInt();
        self.terms_of_service = try api.help.TermsOfService.deserialize(allocator, r);
        return self;
    }
};

pub const deepLinkInfoEmpty = struct {
    pub const constructor_id: u32 = 0x66afa166;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const deepLinkInfo = struct {
    pub const constructor_id: u32 = 0x6a4ee832;
    update_app: bool = false,
    message: []const u8,
    entities: ?[]api.MessageEntity = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.update_app) flags |= 1 << 0;
        if (self.entities != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeString(self.message);
        if (self.entities) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_1326| {
                try elem_1326.serialize(w);
            }
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.update_app = (flags >> 0) & 1 != 0;
        self.message = try r.readString();
        if ((flags >> 1) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_1327 = try r.readVectorLength();
            const vec_1328 = allocator.alloc(api.MessageEntity, len_1327) catch return error.OutOfMemory;
            for (vec_1328) |*elem_1329| {
                elem_1329.* = try api.MessageEntity.deserialize(allocator, r);
            }
            self.entities = vec_1328;
        } else {
            self.entities = null;
        }
        return self;
    }
};

pub const passportConfigNotModified = struct {
    pub const constructor_id: u32 = 0xbfb9f457;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const passportConfig = struct {
    pub const constructor_id: u32 = 0xa098d6af;
    hash: i32,
    countries_langs: api.DataJSON,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.hash);
        try self.countries_langs.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.hash = try r.readInt();
        self.countries_langs = try api.DataJSON.deserialize(allocator, r);
        return self;
    }
};

pub const supportName = struct {
    pub const constructor_id: u32 = 0x8c05f1c9;
    name: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.name);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.name = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const userInfoEmpty = struct {
    pub const constructor_id: u32 = 0xf3ae2eed;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const userInfo = struct {
    pub const constructor_id: u32 = 0x01eb3758;
    message: []const u8,
    entities: []api.MessageEntity,
    author: []const u8,
    date: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.message);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.entities.len);
        for (self.entities) |elem_1330| {
            try elem_1330.serialize(w);
        }
        try w.writeString(self.author);
        try w.writeInt(self.date);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.message = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1331 = try r.readVectorLength();
        const vec_1332 = allocator.alloc(api.MessageEntity, len_1331) catch return error.OutOfMemory;
        for (vec_1332) |*elem_1333| {
            elem_1333.* = try api.MessageEntity.deserialize(allocator, r);
        }
        self.entities = vec_1332;
        self.author = try r.readString();
        self.date = try r.readInt();
        return self;
    }
};

pub const promoDataEmpty = struct {
    pub const constructor_id: u32 = 0x98f6ac75;
    expires: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.expires);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.expires = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const promoData = struct {
    pub const constructor_id: u32 = 0x08a4d87a;
    proxy: bool = false,
    expires: i32,
    peer: ?api.Peer = null,
    psa_type: ?[]const u8 = null,
    psa_message: ?[]const u8 = null,
    pending_suggestions: [][]const u8,
    dismissed_suggestions: [][]const u8,
    custom_pending_suggestion: ?api.PendingSuggestion = null,
    chats: []api.Chat,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.proxy) flags |= 1 << 0;
        if (self.peer != null) flags |= 1 << 3;
        if (self.psa_type != null) flags |= 1 << 1;
        if (self.psa_message != null) flags |= 1 << 2;
        if (self.custom_pending_suggestion != null) flags |= 1 << 4;
        try w.writeUInt(flags);
        try w.writeInt(self.expires);
        if (self.peer) |v| {
            try v.serialize(w);
        }
        if (self.psa_type) |v| {
            try w.writeString(v);
        }
        if (self.psa_message) |v| {
            try w.writeString(v);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.pending_suggestions.len);
        for (self.pending_suggestions) |elem_1334| {
            try w.writeString(elem_1334);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.dismissed_suggestions.len);
        for (self.dismissed_suggestions) |elem_1335| {
            try w.writeString(elem_1335);
        }
        if (self.custom_pending_suggestion) |v| {
            try v.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_1336| {
            try elem_1336.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1337| {
            try elem_1337.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.proxy = (flags >> 0) & 1 != 0;
        self.expires = try r.readInt();
        if ((flags >> 3) & 1 != 0) {
            self.peer = try api.Peer.deserialize(allocator, r);
        } else {
            self.peer = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.psa_type = try r.readString();
        } else {
            self.psa_type = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.psa_message = try r.readString();
        } else {
            self.psa_message = null;
        }
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1338 = try r.readVectorLength();
        const vec_1339 = allocator.alloc([]const u8, len_1338) catch return error.OutOfMemory;
        for (vec_1339) |*elem_1340| {
            elem_1340.* = try r.readString();
        }
        self.pending_suggestions = vec_1339;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1341 = try r.readVectorLength();
        const vec_1342 = allocator.alloc([]const u8, len_1341) catch return error.OutOfMemory;
        for (vec_1342) |*elem_1343| {
            elem_1343.* = try r.readString();
        }
        self.dismissed_suggestions = vec_1342;
        if ((flags >> 4) & 1 != 0) {
            self.custom_pending_suggestion = try api.PendingSuggestion.deserialize(allocator, r);
        } else {
            self.custom_pending_suggestion = null;
        }
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1344 = try r.readVectorLength();
        const vec_1345 = allocator.alloc(api.Chat, len_1344) catch return error.OutOfMemory;
        for (vec_1345) |*elem_1346| {
            elem_1346.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_1345;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1347 = try r.readVectorLength();
        const vec_1348 = allocator.alloc(api.User, len_1347) catch return error.OutOfMemory;
        for (vec_1348) |*elem_1349| {
            elem_1349.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1348;
        return self;
    }
};

pub const countryCode = struct {
    pub const constructor_id: u32 = 0x4203c5ef;
    country_code: []const u8,
    prefixes: ?[][]const u8 = null,
    patterns: ?[][]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.prefixes != null) flags |= 1 << 0;
        if (self.patterns != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeString(self.country_code);
        if (self.prefixes) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_1350| {
                try w.writeString(elem_1350);
            }
        }
        if (self.patterns) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_1351| {
                try w.writeString(elem_1351);
            }
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.country_code = try r.readString();
        if ((flags >> 0) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_1352 = try r.readVectorLength();
            const vec_1353 = allocator.alloc([]const u8, len_1352) catch return error.OutOfMemory;
            for (vec_1353) |*elem_1354| {
                elem_1354.* = try r.readString();
            }
            self.prefixes = vec_1353;
        } else {
            self.prefixes = null;
        }
        if ((flags >> 1) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_1355 = try r.readVectorLength();
            const vec_1356 = allocator.alloc([]const u8, len_1355) catch return error.OutOfMemory;
            for (vec_1356) |*elem_1357| {
                elem_1357.* = try r.readString();
            }
            self.patterns = vec_1356;
        } else {
            self.patterns = null;
        }
        return self;
    }
};

pub const country = struct {
    pub const constructor_id: u32 = 0xc3878e23;
    hidden: bool = false,
    iso2: []const u8,
    default_name: []const u8,
    name: ?[]const u8 = null,
    country_codes: []api.help.CountryCode,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.hidden) flags |= 1 << 0;
        if (self.name != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeString(self.iso2);
        try w.writeString(self.default_name);
        if (self.name) |v| {
            try w.writeString(v);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.country_codes.len);
        for (self.country_codes) |elem_1358| {
            try elem_1358.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.hidden = (flags >> 0) & 1 != 0;
        self.iso2 = try r.readString();
        self.default_name = try r.readString();
        if ((flags >> 1) & 1 != 0) {
            self.name = try r.readString();
        } else {
            self.name = null;
        }
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1359 = try r.readVectorLength();
        const vec_1360 = allocator.alloc(api.help.CountryCode, len_1359) catch return error.OutOfMemory;
        for (vec_1360) |*elem_1361| {
            elem_1361.* = try api.help.CountryCode.deserialize(allocator, r);
        }
        self.country_codes = vec_1360;
        return self;
    }
};

pub const countriesListNotModified = struct {
    pub const constructor_id: u32 = 0x93cc1f32;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const countriesList = struct {
    pub const constructor_id: u32 = 0x87d0759e;
    countries: []api.help.Country,
    hash: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.countries.len);
        for (self.countries) |elem_1362| {
            try elem_1362.serialize(w);
        }
        try w.writeInt(self.hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1363 = try r.readVectorLength();
        const vec_1364 = allocator.alloc(api.help.Country, len_1363) catch return error.OutOfMemory;
        for (vec_1364) |*elem_1365| {
            elem_1365.* = try api.help.Country.deserialize(allocator, r);
        }
        self.countries = vec_1364;
        self.hash = try r.readInt();
        return self;
    }
};

pub const premiumPromo = struct {
    pub const constructor_id: u32 = 0x5334759c;
    status_text: []const u8,
    status_entities: []api.MessageEntity,
    video_sections: [][]const u8,
    videos: []api.Document,
    period_options: []api.PremiumSubscriptionOption,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.status_text);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.status_entities.len);
        for (self.status_entities) |elem_1366| {
            try elem_1366.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.video_sections.len);
        for (self.video_sections) |elem_1367| {
            try w.writeString(elem_1367);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.videos.len);
        for (self.videos) |elem_1368| {
            try elem_1368.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.period_options.len);
        for (self.period_options) |elem_1369| {
            try elem_1369.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1370| {
            try elem_1370.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.status_text = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1371 = try r.readVectorLength();
        const vec_1372 = allocator.alloc(api.MessageEntity, len_1371) catch return error.OutOfMemory;
        for (vec_1372) |*elem_1373| {
            elem_1373.* = try api.MessageEntity.deserialize(allocator, r);
        }
        self.status_entities = vec_1372;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1374 = try r.readVectorLength();
        const vec_1375 = allocator.alloc([]const u8, len_1374) catch return error.OutOfMemory;
        for (vec_1375) |*elem_1376| {
            elem_1376.* = try r.readString();
        }
        self.video_sections = vec_1375;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1377 = try r.readVectorLength();
        const vec_1378 = allocator.alloc(api.Document, len_1377) catch return error.OutOfMemory;
        for (vec_1378) |*elem_1379| {
            elem_1379.* = try api.Document.deserialize(allocator, r);
        }
        self.videos = vec_1378;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1380 = try r.readVectorLength();
        const vec_1381 = allocator.alloc(api.PremiumSubscriptionOption, len_1380) catch return error.OutOfMemory;
        for (vec_1381) |*elem_1382| {
            elem_1382.* = try api.PremiumSubscriptionOption.deserialize(allocator, r);
        }
        self.period_options = vec_1381;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1383 = try r.readVectorLength();
        const vec_1384 = allocator.alloc(api.User, len_1383) catch return error.OutOfMemory;
        for (vec_1384) |*elem_1385| {
            elem_1385.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1384;
        return self;
    }
};

pub const appConfigNotModified = struct {
    pub const constructor_id: u32 = 0x7cde641d;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const appConfig = struct {
    pub const constructor_id: u32 = 0xdd18782e;
    hash: i32,
    config: *api.JSONValue,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.hash);
        try self.config.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.hash = try r.readInt();
                const ptr_1386 = allocator.create(api.JSONValue) catch return error.OutOfMemory;
        ptr_1386.* = try api.JSONValue.deserialize(allocator, r);
        self.config = ptr_1386;
        return self;
    }
};

pub const peerColorSet = struct {
    pub const constructor_id: u32 = 0x26219a58;
    colors: []i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.colors.len);
        for (self.colors) |elem_1387| {
            try w.writeInt(elem_1387);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1388 = try r.readVectorLength();
        const vec_1389 = allocator.alloc(i32, len_1388) catch return error.OutOfMemory;
        for (vec_1389) |*elem_1390| {
            elem_1390.* = try r.readInt();
        }
        self.colors = vec_1389;
        return self;
    }
};

pub const peerColorProfileSet = struct {
    pub const constructor_id: u32 = 0x767d61eb;
    palette_colors: []i32,
    bg_colors: []i32,
    story_colors: []i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.palette_colors.len);
        for (self.palette_colors) |elem_1391| {
            try w.writeInt(elem_1391);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.bg_colors.len);
        for (self.bg_colors) |elem_1392| {
            try w.writeInt(elem_1392);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.story_colors.len);
        for (self.story_colors) |elem_1393| {
            try w.writeInt(elem_1393);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1394 = try r.readVectorLength();
        const vec_1395 = allocator.alloc(i32, len_1394) catch return error.OutOfMemory;
        for (vec_1395) |*elem_1396| {
            elem_1396.* = try r.readInt();
        }
        self.palette_colors = vec_1395;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1397 = try r.readVectorLength();
        const vec_1398 = allocator.alloc(i32, len_1397) catch return error.OutOfMemory;
        for (vec_1398) |*elem_1399| {
            elem_1399.* = try r.readInt();
        }
        self.bg_colors = vec_1398;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1400 = try r.readVectorLength();
        const vec_1401 = allocator.alloc(i32, len_1400) catch return error.OutOfMemory;
        for (vec_1401) |*elem_1402| {
            elem_1402.* = try r.readInt();
        }
        self.story_colors = vec_1401;
        return self;
    }
};

pub const peerColorOption = struct {
    pub const constructor_id: u32 = 0xadec6ebe;
    hidden: bool = false,
    color_id: i32,
    colors: ?api.help.PeerColorSet = null,
    dark_colors: ?api.help.PeerColorSet = null,
    channel_min_level: ?i32 = null,
    group_min_level: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.hidden) flags |= 1 << 0;
        if (self.colors != null) flags |= 1 << 1;
        if (self.dark_colors != null) flags |= 1 << 2;
        if (self.channel_min_level != null) flags |= 1 << 3;
        if (self.group_min_level != null) flags |= 1 << 4;
        try w.writeUInt(flags);
        try w.writeInt(self.color_id);
        if (self.colors) |v| {
            try v.serialize(w);
        }
        if (self.dark_colors) |v| {
            try v.serialize(w);
        }
        if (self.channel_min_level) |v| {
            try w.writeInt(v);
        }
        if (self.group_min_level) |v| {
            try w.writeInt(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.hidden = (flags >> 0) & 1 != 0;
        self.color_id = try r.readInt();
        if ((flags >> 1) & 1 != 0) {
            self.colors = try api.help.PeerColorSet.deserialize(allocator, r);
        } else {
            self.colors = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.dark_colors = try api.help.PeerColorSet.deserialize(allocator, r);
        } else {
            self.dark_colors = null;
        }
        if ((flags >> 3) & 1 != 0) {
            self.channel_min_level = try r.readInt();
        } else {
            self.channel_min_level = null;
        }
        if ((flags >> 4) & 1 != 0) {
            self.group_min_level = try r.readInt();
        } else {
            self.group_min_level = null;
        }
        return self;
    }
};

pub const peerColorsNotModified = struct {
    pub const constructor_id: u32 = 0x2ba1f5ce;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const peerColors = struct {
    pub const constructor_id: u32 = 0x00f8ed08;
    hash: i32,
    colors: []api.help.PeerColorOption,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.hash);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.colors.len);
        for (self.colors) |elem_1403| {
            try elem_1403.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.hash = try r.readInt();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1404 = try r.readVectorLength();
        const vec_1405 = allocator.alloc(api.help.PeerColorOption, len_1404) catch return error.OutOfMemory;
        for (vec_1405) |*elem_1406| {
            elem_1406.* = try api.help.PeerColorOption.deserialize(allocator, r);
        }
        self.colors = vec_1405;
        return self;
    }
};

pub const timezonesListNotModified = struct {
    pub const constructor_id: u32 = 0x970708cc;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const timezonesList = struct {
    pub const constructor_id: u32 = 0x7b74ed71;
    timezones: []api.Timezone,
    hash: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.timezones.len);
        for (self.timezones) |elem_1407| {
            try elem_1407.serialize(w);
        }
        try w.writeInt(self.hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1408 = try r.readVectorLength();
        const vec_1409 = allocator.alloc(api.Timezone, len_1408) catch return error.OutOfMemory;
        for (vec_1409) |*elem_1410| {
            elem_1410.* = try api.Timezone.deserialize(allocator, r);
        }
        self.timezones = vec_1409;
        self.hash = try r.readInt();
        return self;
    }
};

pub const Config = union(enum) {
    config: api.config,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.config.constructor_id => return .{ .config = try api.config.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const NearestDc = union(enum) {
    nearestDc: api.nearestDc,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.nearestDc.constructor_id => return .{ .nearestDc = try api.nearestDc.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const AppUpdate = union(enum) {
    appUpdate: api.help.appUpdate,
    noAppUpdate: api.help.noAppUpdate,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.appUpdate.constructor_id => return .{ .appUpdate = try api.help.appUpdate.deserialize(allocator, r) },
            api.help.noAppUpdate.constructor_id => return .{ .noAppUpdate = try api.help.noAppUpdate.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InviteText = union(enum) {
    inviteText: api.help.inviteText,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.inviteText.constructor_id => return .{ .inviteText = try api.help.inviteText.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const Support = union(enum) {
    support: api.help.support,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.support.constructor_id => return .{ .support = try api.help.support.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const TermsOfService = union(enum) {
    termsOfService: api.help.termsOfService,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.termsOfService.constructor_id => return .{ .termsOfService = try api.help.termsOfService.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const RecentMeUrl = union(enum) {
    recentMeUrlUnknown: api.recentMeUrlUnknown,
    recentMeUrlUser: api.recentMeUrlUser,
    recentMeUrlChat: api.recentMeUrlChat,
    recentMeUrlChatInvite: api.recentMeUrlChatInvite,
    recentMeUrlStickerSet: api.recentMeUrlStickerSet,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.recentMeUrlUnknown.constructor_id => return .{ .recentMeUrlUnknown = try api.recentMeUrlUnknown.deserialize(allocator, r) },
            api.recentMeUrlUser.constructor_id => return .{ .recentMeUrlUser = try api.recentMeUrlUser.deserialize(allocator, r) },
            api.recentMeUrlChat.constructor_id => return .{ .recentMeUrlChat = try api.recentMeUrlChat.deserialize(allocator, r) },
            api.recentMeUrlChatInvite.constructor_id => return .{ .recentMeUrlChatInvite = try api.recentMeUrlChatInvite.deserialize(allocator, r) },
            api.recentMeUrlStickerSet.constructor_id => return .{ .recentMeUrlStickerSet = try api.recentMeUrlStickerSet.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const RecentMeUrls = union(enum) {
    recentMeUrls: api.help.recentMeUrls,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.recentMeUrls.constructor_id => return .{ .recentMeUrls = try api.help.recentMeUrls.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const TermsOfServiceUpdate = union(enum) {
    termsOfServiceUpdateEmpty: api.help.termsOfServiceUpdateEmpty,
    termsOfServiceUpdate: api.help.termsOfServiceUpdate,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.termsOfServiceUpdateEmpty.constructor_id => return .{ .termsOfServiceUpdateEmpty = try api.help.termsOfServiceUpdateEmpty.deserialize(allocator, r) },
            api.help.termsOfServiceUpdate.constructor_id => return .{ .termsOfServiceUpdate = try api.help.termsOfServiceUpdate.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const DeepLinkInfo = union(enum) {
    deepLinkInfoEmpty: api.help.deepLinkInfoEmpty,
    deepLinkInfo: api.help.deepLinkInfo,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.deepLinkInfoEmpty.constructor_id => return .{ .deepLinkInfoEmpty = try api.help.deepLinkInfoEmpty.deserialize(allocator, r) },
            api.help.deepLinkInfo.constructor_id => return .{ .deepLinkInfo = try api.help.deepLinkInfo.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PassportConfig = union(enum) {
    passportConfigNotModified: api.help.passportConfigNotModified,
    passportConfig: api.help.passportConfig,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.passportConfigNotModified.constructor_id => return .{ .passportConfigNotModified = try api.help.passportConfigNotModified.deserialize(allocator, r) },
            api.help.passportConfig.constructor_id => return .{ .passportConfig = try api.help.passportConfig.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SupportName = union(enum) {
    supportName: api.help.supportName,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.supportName.constructor_id => return .{ .supportName = try api.help.supportName.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const UserInfo = union(enum) {
    userInfoEmpty: api.help.userInfoEmpty,
    userInfo: api.help.userInfo,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.userInfoEmpty.constructor_id => return .{ .userInfoEmpty = try api.help.userInfoEmpty.deserialize(allocator, r) },
            api.help.userInfo.constructor_id => return .{ .userInfo = try api.help.userInfo.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PromoData = union(enum) {
    promoDataEmpty: api.help.promoDataEmpty,
    promoData: api.help.promoData,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.promoDataEmpty.constructor_id => return .{ .promoDataEmpty = try api.help.promoDataEmpty.deserialize(allocator, r) },
            api.help.promoData.constructor_id => return .{ .promoData = try api.help.promoData.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const CountryCode = union(enum) {
    countryCode: api.help.countryCode,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.countryCode.constructor_id => return .{ .countryCode = try api.help.countryCode.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const Country = union(enum) {
    country: api.help.country,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.country.constructor_id => return .{ .country = try api.help.country.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const CountriesList = union(enum) {
    countriesListNotModified: api.help.countriesListNotModified,
    countriesList: api.help.countriesList,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.countriesListNotModified.constructor_id => return .{ .countriesListNotModified = try api.help.countriesListNotModified.deserialize(allocator, r) },
            api.help.countriesList.constructor_id => return .{ .countriesList = try api.help.countriesList.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PremiumPromo = union(enum) {
    premiumPromo: api.help.premiumPromo,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.premiumPromo.constructor_id => return .{ .premiumPromo = try api.help.premiumPromo.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const AppConfig = union(enum) {
    appConfigNotModified: api.help.appConfigNotModified,
    appConfig: api.help.appConfig,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.appConfigNotModified.constructor_id => return .{ .appConfigNotModified = try api.help.appConfigNotModified.deserialize(allocator, r) },
            api.help.appConfig.constructor_id => return .{ .appConfig = try api.help.appConfig.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PeerColorSet = union(enum) {
    peerColorSet: api.help.peerColorSet,
    peerColorProfileSet: api.help.peerColorProfileSet,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.peerColorSet.constructor_id => return .{ .peerColorSet = try api.help.peerColorSet.deserialize(allocator, r) },
            api.help.peerColorProfileSet.constructor_id => return .{ .peerColorProfileSet = try api.help.peerColorProfileSet.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PeerColorOption = union(enum) {
    peerColorOption: api.help.peerColorOption,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.peerColorOption.constructor_id => return .{ .peerColorOption = try api.help.peerColorOption.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PeerColors = union(enum) {
    peerColorsNotModified: api.help.peerColorsNotModified,
    peerColors: api.help.peerColors,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.peerColorsNotModified.constructor_id => return .{ .peerColorsNotModified = try api.help.peerColorsNotModified.deserialize(allocator, r) },
            api.help.peerColors.constructor_id => return .{ .peerColors = try api.help.peerColors.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const TimezonesList = union(enum) {
    timezonesListNotModified: api.help.timezonesListNotModified,
    timezonesList: api.help.timezonesList,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.help.timezonesListNotModified.constructor_id => return .{ .timezonesListNotModified = try api.help.timezonesListNotModified.deserialize(allocator, r) },
            api.help.timezonesList.constructor_id => return .{ .timezonesList = try api.help.timezonesList.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

