//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const inputPeerEmpty = struct {
    pub const constructor_id: u32 = 0x7f3b18ea;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputPeerSelf = struct {
    pub const constructor_id: u32 = 0x7da07ec9;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputPeerChat = struct {
    pub const constructor_id: u32 = 0x35a95cb9;
    chat_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.chat_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.chat_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputPeerUser = struct {
    pub const constructor_id: u32 = 0xdde8a54c;
    user_id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.user_id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.user_id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputPeerChannel = struct {
    pub const constructor_id: u32 = 0x27bcbbfc;
    channel_id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.channel_id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.channel_id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputPeerUserFromMessage = struct {
    pub const constructor_id: u32 = 0xa87b0a1c;
    peer: *api.InputPeer,
    msg_id: i32,
    user_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
        try w.writeInt(self.msg_id);
        try w.writeLong(self.user_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
                const ptr_21 = allocator.create(api.InputPeer) catch return error.OutOfMemory;
        ptr_21.* = try api.InputPeer.deserialize(allocator, r);
        self.peer = ptr_21;
        self.msg_id = try r.readInt();
        self.user_id = try r.readLong();
        return self;
    }
};

pub const inputPeerChannelFromMessage = struct {
    pub const constructor_id: u32 = 0xbd2a0840;
    peer: *api.InputPeer,
    msg_id: i32,
    channel_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
        try w.writeInt(self.msg_id);
        try w.writeLong(self.channel_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
                const ptr_22 = allocator.create(api.InputPeer) catch return error.OutOfMemory;
        ptr_22.* = try api.InputPeer.deserialize(allocator, r);
        self.peer = ptr_22;
        self.msg_id = try r.readInt();
        self.channel_id = try r.readLong();
        return self;
    }
};

pub const inputUserEmpty = struct {
    pub const constructor_id: u32 = 0xb98886cf;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputUserSelf = struct {
    pub const constructor_id: u32 = 0xf7c1b13f;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputUser = struct {
    pub const constructor_id: u32 = 0xf21158c6;
    user_id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.user_id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.user_id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputUserFromMessage = struct {
    pub const constructor_id: u32 = 0x1da448e2;
    peer: *api.InputPeer,
    msg_id: i32,
    user_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
        try w.writeInt(self.msg_id);
        try w.writeLong(self.user_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
                const ptr_23 = allocator.create(api.InputPeer) catch return error.OutOfMemory;
        ptr_23.* = try api.InputPeer.deserialize(allocator, r);
        self.peer = ptr_23;
        self.msg_id = try r.readInt();
        self.user_id = try r.readLong();
        return self;
    }
};

pub const peerUser = struct {
    pub const constructor_id: u32 = 0x59511722;
    user_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.user_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.user_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const peerChat = struct {
    pub const constructor_id: u32 = 0x36c6019a;
    chat_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.chat_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.chat_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const peerChannel = struct {
    pub const constructor_id: u32 = 0xa2a5371e;
    channel_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.channel_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.channel_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputNotifyPeer = struct {
    pub const constructor_id: u32 = 0xb8bc5b0c;
    peer: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
                const ptr_24 = allocator.create(api.InputPeer) catch return error.OutOfMemory;
        ptr_24.* = try api.InputPeer.deserialize(allocator, r);
        self.peer = ptr_24;
        return self;
    }
};

pub const inputNotifyUsers = struct {
    pub const constructor_id: u32 = 0x193b4417;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputNotifyChats = struct {
    pub const constructor_id: u32 = 0x4a95e84e;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputNotifyBroadcasts = struct {
    pub const constructor_id: u32 = 0xb1db7c7e;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputNotifyForumTopic = struct {
    pub const constructor_id: u32 = 0x5c467992;
    peer: *api.InputPeer,
    top_msg_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
        try w.writeInt(self.top_msg_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
                const ptr_25 = allocator.create(api.InputPeer) catch return error.OutOfMemory;
        ptr_25.* = try api.InputPeer.deserialize(allocator, r);
        self.peer = ptr_25;
        self.top_msg_id = try r.readInt();
        return self;
    }
};

pub const inputNotifyCommunity = struct {
    pub const constructor_id: u32 = 0x27bb1adc;
    community: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.community.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.community = try api.InputChannel.deserialize(allocator, r);
        return self;
    }
};

pub const notifyPeer = struct {
    pub const constructor_id: u32 = 0x9fd40bd8;
    peer: api.Peer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.peer = try api.Peer.deserialize(allocator, r);
        return self;
    }
};

pub const notifyUsers = struct {
    pub const constructor_id: u32 = 0xb4c83b4c;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const notifyChats = struct {
    pub const constructor_id: u32 = 0xc007cec3;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const notifyBroadcasts = struct {
    pub const constructor_id: u32 = 0xd612e8ef;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const notifyForumTopic = struct {
    pub const constructor_id: u32 = 0x226e6308;
    peer: api.Peer,
    top_msg_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
        try w.writeInt(self.top_msg_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.peer = try api.Peer.deserialize(allocator, r);
        self.top_msg_id = try r.readInt();
        return self;
    }
};

pub const notifyCommunity = struct {
    pub const constructor_id: u32 = 0xbe376999;
    community_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.community_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.community_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputChannelEmpty = struct {
    pub const constructor_id: u32 = 0xee8c1e86;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputChannel = struct {
    pub const constructor_id: u32 = 0xf35aec28;
    channel_id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.channel_id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.channel_id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputChannelFromMessage = struct {
    pub const constructor_id: u32 = 0x5b934f9d;
    peer: *api.InputPeer,
    msg_id: i32,
    channel_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
        try w.writeInt(self.msg_id);
        try w.writeLong(self.channel_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
                const ptr_26 = allocator.create(api.InputPeer) catch return error.OutOfMemory;
        ptr_26.* = try api.InputPeer.deserialize(allocator, r);
        self.peer = ptr_26;
        self.msg_id = try r.readInt();
        self.channel_id = try r.readLong();
        return self;
    }
};

pub const peerLocated = struct {
    pub const constructor_id: u32 = 0xca461b5d;
    peer: api.Peer,
    expires: i32,
    distance: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer.serialize(w);
        try w.writeInt(self.expires);
        try w.writeInt(self.distance);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.peer = try api.Peer.deserialize(allocator, r);
        self.expires = try r.readInt();
        self.distance = try r.readInt();
        return self;
    }
};

pub const peerSelfLocated = struct {
    pub const constructor_id: u32 = 0xf8ec284b;
    expires: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.expires);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.expires = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const peerBlocked = struct {
    pub const constructor_id: u32 = 0xe8fd8014;
    peer_id: api.Peer,
    date: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.peer_id.serialize(w);
        try w.writeInt(self.date);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.peer_id = try api.Peer.deserialize(allocator, r);
        self.date = try r.readInt();
        return self;
    }
};

pub const sendAsPeer = struct {
    pub const constructor_id: u32 = 0xb81c7034;
    premium_required: bool = false,
    peer: api.Peer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.premium_required) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.peer.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.premium_required = (flags >> 0) & 1 != 0;
        self.peer = try api.Peer.deserialize(allocator, r);
        return self;
    }
};

pub const requestPeerTypeUser = struct {
    pub const constructor_id: u32 = 0x5f3b8a00;
    bot: ?bool = null,
    premium: ?bool = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.bot != null) flags |= 1 << 0;
        if (self.premium != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        if (self.bot) |v| {
            try w.writeBool(v);
        }
        if (self.premium) |v| {
            try w.writeBool(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        if ((flags >> 0) & 1 != 0) {
            self.bot = try r.readBool();
        } else {
            self.bot = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.premium = try r.readBool();
        } else {
            self.premium = null;
        }
        _ = allocator;
        return self;
    }
};

pub const requestPeerTypeChat = struct {
    pub const constructor_id: u32 = 0xc9f06e1b;
    creator: bool = false,
    bot_participant: bool = false,
    has_username: ?bool = null,
    forum: ?bool = null,
    user_admin_rights: ?api.ChatAdminRights = null,
    bot_admin_rights: ?api.ChatAdminRights = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.creator) flags |= 1 << 0;
        if (self.bot_participant) flags |= 1 << 5;
        if (self.has_username != null) flags |= 1 << 3;
        if (self.forum != null) flags |= 1 << 4;
        if (self.user_admin_rights != null) flags |= 1 << 1;
        if (self.bot_admin_rights != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        if (self.has_username) |v| {
            try w.writeBool(v);
        }
        if (self.forum) |v| {
            try w.writeBool(v);
        }
        if (self.user_admin_rights) |v| {
            try v.serialize(w);
        }
        if (self.bot_admin_rights) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.creator = (flags >> 0) & 1 != 0;
        self.bot_participant = (flags >> 5) & 1 != 0;
        if ((flags >> 3) & 1 != 0) {
            self.has_username = try r.readBool();
        } else {
            self.has_username = null;
        }
        if ((flags >> 4) & 1 != 0) {
            self.forum = try r.readBool();
        } else {
            self.forum = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.user_admin_rights = try api.ChatAdminRights.deserialize(allocator, r);
        } else {
            self.user_admin_rights = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.bot_admin_rights = try api.ChatAdminRights.deserialize(allocator, r);
        } else {
            self.bot_admin_rights = null;
        }
        return self;
    }
};

pub const requestPeerTypeBroadcast = struct {
    pub const constructor_id: u32 = 0x339bef6c;
    creator: bool = false,
    has_username: ?bool = null,
    user_admin_rights: ?api.ChatAdminRights = null,
    bot_admin_rights: ?api.ChatAdminRights = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.creator) flags |= 1 << 0;
        if (self.has_username != null) flags |= 1 << 3;
        if (self.user_admin_rights != null) flags |= 1 << 1;
        if (self.bot_admin_rights != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        if (self.has_username) |v| {
            try w.writeBool(v);
        }
        if (self.user_admin_rights) |v| {
            try v.serialize(w);
        }
        if (self.bot_admin_rights) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.creator = (flags >> 0) & 1 != 0;
        if ((flags >> 3) & 1 != 0) {
            self.has_username = try r.readBool();
        } else {
            self.has_username = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.user_admin_rights = try api.ChatAdminRights.deserialize(allocator, r);
        } else {
            self.user_admin_rights = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.bot_admin_rights = try api.ChatAdminRights.deserialize(allocator, r);
        } else {
            self.bot_admin_rights = null;
        }
        return self;
    }
};

pub const requestPeerTypeCreateBot = struct {
    pub const constructor_id: u32 = 0x3e81e078;
    bot_managed: bool = false,
    suggested_name: ?[]const u8 = null,
    suggested_username: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.bot_managed) flags |= 1 << 0;
        if (self.suggested_name != null) flags |= 1 << 1;
        if (self.suggested_username != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        if (self.suggested_name) |v| {
            try w.writeString(v);
        }
        if (self.suggested_username) |v| {
            try w.writeString(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.bot_managed = (flags >> 0) & 1 != 0;
        if ((flags >> 1) & 1 != 0) {
            self.suggested_name = try r.readString();
        } else {
            self.suggested_name = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.suggested_username = try r.readString();
        } else {
            self.suggested_username = null;
        }
        _ = allocator;
        return self;
    }
};

pub const peerColor = struct {
    pub const constructor_id: u32 = 0xb54b5acf;
    color: ?i32 = null,
    background_emoji_id: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.color != null) flags |= 1 << 0;
        if (self.background_emoji_id != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        if (self.color) |v| {
            try w.writeInt(v);
        }
        if (self.background_emoji_id) |v| {
            try w.writeLong(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        if ((flags >> 0) & 1 != 0) {
            self.color = try r.readInt();
        } else {
            self.color = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.background_emoji_id = try r.readLong();
        } else {
            self.background_emoji_id = null;
        }
        _ = allocator;
        return self;
    }
};

pub const peerColorCollectible = struct {
    pub const constructor_id: u32 = 0xb9c0639a;
    collectible_id: i64,
    gift_emoji_id: i64,
    background_emoji_id: i64,
    accent_color: i32,
    colors: []i32,
    dark_accent_color: ?i32 = null,
    dark_colors: ?[]i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.dark_accent_color != null) flags |= 1 << 0;
        if (self.dark_colors != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeLong(self.collectible_id);
        try w.writeLong(self.gift_emoji_id);
        try w.writeLong(self.background_emoji_id);
        try w.writeInt(self.accent_color);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.colors.len);
        for (self.colors) |elem_27| {
            try w.writeInt(elem_27);
        }
        if (self.dark_accent_color) |v| {
            try w.writeInt(v);
        }
        if (self.dark_colors) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_28| {
                try w.writeInt(elem_28);
            }
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.collectible_id = try r.readLong();
        self.gift_emoji_id = try r.readLong();
        self.background_emoji_id = try r.readLong();
        self.accent_color = try r.readInt();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_29 = try r.readVectorLength();
        const vec_30 = allocator.alloc(i32, len_29) catch return error.OutOfMemory;
        for (vec_30) |*elem_31| {
            elem_31.* = try r.readInt();
        }
        self.colors = vec_30;
        if ((flags >> 0) & 1 != 0) {
            self.dark_accent_color = try r.readInt();
        } else {
            self.dark_accent_color = null;
        }
        if ((flags >> 1) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_32 = try r.readVectorLength();
            const vec_33 = allocator.alloc(i32, len_32) catch return error.OutOfMemory;
            for (vec_33) |*elem_34| {
                elem_34.* = try r.readInt();
            }
            self.dark_colors = vec_33;
        } else {
            self.dark_colors = null;
        }
        return self;
    }
};

pub const inputPeerColorCollectible = struct {
    pub const constructor_id: u32 = 0xb8ea86a9;
    collectible_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.collectible_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.collectible_id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const requestedPeerUser = struct {
    pub const constructor_id: u32 = 0xd62ff46a;
    user_id: i64,
    first_name: ?[]const u8 = null,
    last_name: ?[]const u8 = null,
    username: ?[]const u8 = null,
    photo: ?api.Photo = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.first_name != null) flags |= 1 << 0;
        if (self.last_name != null) flags |= 1 << 0;
        if (self.username != null) flags |= 1 << 1;
        if (self.photo != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        try w.writeLong(self.user_id);
        if (self.first_name) |v| {
            try w.writeString(v);
        }
        if (self.last_name) |v| {
            try w.writeString(v);
        }
        if (self.username) |v| {
            try w.writeString(v);
        }
        if (self.photo) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.user_id = try r.readLong();
        if ((flags >> 0) & 1 != 0) {
            self.first_name = try r.readString();
        } else {
            self.first_name = null;
        }
        if ((flags >> 0) & 1 != 0) {
            self.last_name = try r.readString();
        } else {
            self.last_name = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.username = try r.readString();
        } else {
            self.username = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.photo = try api.Photo.deserialize(allocator, r);
        } else {
            self.photo = null;
        }
        return self;
    }
};

pub const requestedPeerChat = struct {
    pub const constructor_id: u32 = 0x7307544f;
    chat_id: i64,
    title: ?[]const u8 = null,
    photo: ?api.Photo = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.title != null) flags |= 1 << 0;
        if (self.photo != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        try w.writeLong(self.chat_id);
        if (self.title) |v| {
            try w.writeString(v);
        }
        if (self.photo) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.chat_id = try r.readLong();
        if ((flags >> 0) & 1 != 0) {
            self.title = try r.readString();
        } else {
            self.title = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.photo = try api.Photo.deserialize(allocator, r);
        } else {
            self.photo = null;
        }
        return self;
    }
};

pub const requestedPeerChannel = struct {
    pub const constructor_id: u32 = 0x8ba403e4;
    channel_id: i64,
    title: ?[]const u8 = null,
    username: ?[]const u8 = null,
    photo: ?api.Photo = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.title != null) flags |= 1 << 0;
        if (self.username != null) flags |= 1 << 1;
        if (self.photo != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        try w.writeLong(self.channel_id);
        if (self.title) |v| {
            try w.writeString(v);
        }
        if (self.username) |v| {
            try w.writeString(v);
        }
        if (self.photo) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.channel_id = try r.readLong();
        if ((flags >> 0) & 1 != 0) {
            self.title = try r.readString();
        } else {
            self.title = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.username = try r.readString();
        } else {
            self.username = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.photo = try api.Photo.deserialize(allocator, r);
        } else {
            self.photo = null;
        }
        return self;
    }
};

pub const InputPeer = union(enum) {
    inputPeerEmpty: api.inputPeerEmpty,
    inputPeerSelf: api.inputPeerSelf,
    inputPeerChat: api.inputPeerChat,
    inputPeerUser: api.inputPeerUser,
    inputPeerChannel: api.inputPeerChannel,
    inputPeerUserFromMessage: api.inputPeerUserFromMessage,
    inputPeerChannelFromMessage: api.inputPeerChannelFromMessage,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputPeerEmpty.constructor_id => return .{ .inputPeerEmpty = try api.inputPeerEmpty.deserialize(allocator, r) },
            api.inputPeerSelf.constructor_id => return .{ .inputPeerSelf = try api.inputPeerSelf.deserialize(allocator, r) },
            api.inputPeerChat.constructor_id => return .{ .inputPeerChat = try api.inputPeerChat.deserialize(allocator, r) },
            api.inputPeerUser.constructor_id => return .{ .inputPeerUser = try api.inputPeerUser.deserialize(allocator, r) },
            api.inputPeerChannel.constructor_id => return .{ .inputPeerChannel = try api.inputPeerChannel.deserialize(allocator, r) },
            api.inputPeerUserFromMessage.constructor_id => return .{ .inputPeerUserFromMessage = try api.inputPeerUserFromMessage.deserialize(allocator, r) },
            api.inputPeerChannelFromMessage.constructor_id => return .{ .inputPeerChannelFromMessage = try api.inputPeerChannelFromMessage.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputUser = union(enum) {
    inputUserEmpty: api.inputUserEmpty,
    inputUserSelf: api.inputUserSelf,
    inputUser: api.inputUser,
    inputUserFromMessage: api.inputUserFromMessage,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputUserEmpty.constructor_id => return .{ .inputUserEmpty = try api.inputUserEmpty.deserialize(allocator, r) },
            api.inputUserSelf.constructor_id => return .{ .inputUserSelf = try api.inputUserSelf.deserialize(allocator, r) },
            api.inputUser.constructor_id => return .{ .inputUser = try api.inputUser.deserialize(allocator, r) },
            api.inputUserFromMessage.constructor_id => return .{ .inputUserFromMessage = try api.inputUserFromMessage.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const Peer = union(enum) {
    peerUser: api.peerUser,
    peerChat: api.peerChat,
    peerChannel: api.peerChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.peerUser.constructor_id => return .{ .peerUser = try api.peerUser.deserialize(allocator, r) },
            api.peerChat.constructor_id => return .{ .peerChat = try api.peerChat.deserialize(allocator, r) },
            api.peerChannel.constructor_id => return .{ .peerChannel = try api.peerChannel.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputNotifyPeer = union(enum) {
    inputNotifyPeer: api.inputNotifyPeer,
    inputNotifyUsers: api.inputNotifyUsers,
    inputNotifyChats: api.inputNotifyChats,
    inputNotifyBroadcasts: api.inputNotifyBroadcasts,
    inputNotifyForumTopic: api.inputNotifyForumTopic,
    inputNotifyCommunity: api.inputNotifyCommunity,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputNotifyPeer.constructor_id => return .{ .inputNotifyPeer = try api.inputNotifyPeer.deserialize(allocator, r) },
            api.inputNotifyUsers.constructor_id => return .{ .inputNotifyUsers = try api.inputNotifyUsers.deserialize(allocator, r) },
            api.inputNotifyChats.constructor_id => return .{ .inputNotifyChats = try api.inputNotifyChats.deserialize(allocator, r) },
            api.inputNotifyBroadcasts.constructor_id => return .{ .inputNotifyBroadcasts = try api.inputNotifyBroadcasts.deserialize(allocator, r) },
            api.inputNotifyForumTopic.constructor_id => return .{ .inputNotifyForumTopic = try api.inputNotifyForumTopic.deserialize(allocator, r) },
            api.inputNotifyCommunity.constructor_id => return .{ .inputNotifyCommunity = try api.inputNotifyCommunity.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const NotifyPeer = union(enum) {
    notifyPeer: api.notifyPeer,
    notifyUsers: api.notifyUsers,
    notifyChats: api.notifyChats,
    notifyBroadcasts: api.notifyBroadcasts,
    notifyForumTopic: api.notifyForumTopic,
    notifyCommunity: api.notifyCommunity,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.notifyPeer.constructor_id => return .{ .notifyPeer = try api.notifyPeer.deserialize(allocator, r) },
            api.notifyUsers.constructor_id => return .{ .notifyUsers = try api.notifyUsers.deserialize(allocator, r) },
            api.notifyChats.constructor_id => return .{ .notifyChats = try api.notifyChats.deserialize(allocator, r) },
            api.notifyBroadcasts.constructor_id => return .{ .notifyBroadcasts = try api.notifyBroadcasts.deserialize(allocator, r) },
            api.notifyForumTopic.constructor_id => return .{ .notifyForumTopic = try api.notifyForumTopic.deserialize(allocator, r) },
            api.notifyCommunity.constructor_id => return .{ .notifyCommunity = try api.notifyCommunity.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputChannel = union(enum) {
    inputChannelEmpty: api.inputChannelEmpty,
    inputChannel: api.inputChannel,
    inputChannelFromMessage: api.inputChannelFromMessage,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputChannelEmpty.constructor_id => return .{ .inputChannelEmpty = try api.inputChannelEmpty.deserialize(allocator, r) },
            api.inputChannel.constructor_id => return .{ .inputChannel = try api.inputChannel.deserialize(allocator, r) },
            api.inputChannelFromMessage.constructor_id => return .{ .inputChannelFromMessage = try api.inputChannelFromMessage.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PeerLocated = union(enum) {
    peerLocated: api.peerLocated,
    peerSelfLocated: api.peerSelfLocated,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.peerLocated.constructor_id => return .{ .peerLocated = try api.peerLocated.deserialize(allocator, r) },
            api.peerSelfLocated.constructor_id => return .{ .peerSelfLocated = try api.peerSelfLocated.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PeerBlocked = union(enum) {
    peerBlocked: api.peerBlocked,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.peerBlocked.constructor_id => return .{ .peerBlocked = try api.peerBlocked.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SendAsPeer = union(enum) {
    sendAsPeer: api.sendAsPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.sendAsPeer.constructor_id => return .{ .sendAsPeer = try api.sendAsPeer.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const RequestPeerType = union(enum) {
    requestPeerTypeUser: api.requestPeerTypeUser,
    requestPeerTypeChat: api.requestPeerTypeChat,
    requestPeerTypeBroadcast: api.requestPeerTypeBroadcast,
    requestPeerTypeCreateBot: api.requestPeerTypeCreateBot,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.requestPeerTypeUser.constructor_id => return .{ .requestPeerTypeUser = try api.requestPeerTypeUser.deserialize(allocator, r) },
            api.requestPeerTypeChat.constructor_id => return .{ .requestPeerTypeChat = try api.requestPeerTypeChat.deserialize(allocator, r) },
            api.requestPeerTypeBroadcast.constructor_id => return .{ .requestPeerTypeBroadcast = try api.requestPeerTypeBroadcast.deserialize(allocator, r) },
            api.requestPeerTypeCreateBot.constructor_id => return .{ .requestPeerTypeCreateBot = try api.requestPeerTypeCreateBot.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PeerColor = union(enum) {
    peerColor: api.peerColor,
    peerColorCollectible: api.peerColorCollectible,
    inputPeerColorCollectible: api.inputPeerColorCollectible,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.peerColor.constructor_id => return .{ .peerColor = try api.peerColor.deserialize(allocator, r) },
            api.peerColorCollectible.constructor_id => return .{ .peerColorCollectible = try api.peerColorCollectible.deserialize(allocator, r) },
            api.inputPeerColorCollectible.constructor_id => return .{ .inputPeerColorCollectible = try api.inputPeerColorCollectible.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const RequestedPeer = union(enum) {
    requestedPeerUser: api.requestedPeerUser,
    requestedPeerChat: api.requestedPeerChat,
    requestedPeerChannel: api.requestedPeerChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.requestedPeerUser.constructor_id => return .{ .requestedPeerUser = try api.requestedPeerUser.deserialize(allocator, r) },
            api.requestedPeerChat.constructor_id => return .{ .requestedPeerChat = try api.requestedPeerChat.deserialize(allocator, r) },
            api.requestedPeerChannel.constructor_id => return .{ .requestedPeerChannel = try api.requestedPeerChannel.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

