//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const phoneCallDiscardReasonMissed = struct {
    pub const constructor_id: u32 = 0x85e42301;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const phoneCallDiscardReasonDisconnect = struct {
    pub const constructor_id: u32 = 0xe095c1a0;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const phoneCallDiscardReasonHangup = struct {
    pub const constructor_id: u32 = 0x57adc690;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const phoneCallDiscardReasonBusy = struct {
    pub const constructor_id: u32 = 0xfaf7e8c9;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const phoneCallDiscardReasonMigrateConferenceCall = struct {
    pub const constructor_id: u32 = 0x9fbbf1f7;
    slug: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.slug);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.slug = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inputPhoneCall = struct {
    pub const constructor_id: u32 = 0x1e36fded;
    id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const phoneCallEmpty = struct {
    pub const constructor_id: u32 = 0x5366c915;
    id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const phoneCallWaiting = struct {
    pub const constructor_id: u32 = 0xc5226f17;
    video: bool = false,
    id: i64,
    access_hash: i64,
    date: i32,
    admin_id: i64,
    participant_id: i64,
    protocol: api.PhoneCallProtocol,
    receive_date: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.video) flags |= 1 << 6;
        if (self.receive_date != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeInt(self.date);
        try w.writeLong(self.admin_id);
        try w.writeLong(self.participant_id);
        try self.protocol.serialize(w);
        if (self.receive_date) |v| {
            try w.writeInt(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.video = (flags >> 6) & 1 != 0;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.date = try r.readInt();
        self.admin_id = try r.readLong();
        self.participant_id = try r.readLong();
        self.protocol = try api.PhoneCallProtocol.deserialize(allocator, r);
        if ((flags >> 0) & 1 != 0) {
            self.receive_date = try r.readInt();
        } else {
            self.receive_date = null;
        }
        return self;
    }
};

pub const phoneCallRequested = struct {
    pub const constructor_id: u32 = 0x14b0ed0c;
    video: bool = false,
    id: i64,
    access_hash: i64,
    date: i32,
    admin_id: i64,
    participant_id: i64,
    g_a_hash: []const u8,
    protocol: api.PhoneCallProtocol,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.video) flags |= 1 << 6;
        try w.writeUInt(flags);
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeInt(self.date);
        try w.writeLong(self.admin_id);
        try w.writeLong(self.participant_id);
        try w.writeBytes(self.g_a_hash);
        try self.protocol.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.video = (flags >> 6) & 1 != 0;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.date = try r.readInt();
        self.admin_id = try r.readLong();
        self.participant_id = try r.readLong();
        self.g_a_hash = try r.readBytes();
        self.protocol = try api.PhoneCallProtocol.deserialize(allocator, r);
        return self;
    }
};

pub const phoneCallAccepted = struct {
    pub const constructor_id: u32 = 0x3660c311;
    video: bool = false,
    id: i64,
    access_hash: i64,
    date: i32,
    admin_id: i64,
    participant_id: i64,
    g_b: []const u8,
    protocol: api.PhoneCallProtocol,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.video) flags |= 1 << 6;
        try w.writeUInt(flags);
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeInt(self.date);
        try w.writeLong(self.admin_id);
        try w.writeLong(self.participant_id);
        try w.writeBytes(self.g_b);
        try self.protocol.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.video = (flags >> 6) & 1 != 0;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.date = try r.readInt();
        self.admin_id = try r.readLong();
        self.participant_id = try r.readLong();
        self.g_b = try r.readBytes();
        self.protocol = try api.PhoneCallProtocol.deserialize(allocator, r);
        return self;
    }
};

pub const phoneCall = struct {
    pub const constructor_id: u32 = 0x30535af5;
    p2p_allowed: bool = false,
    video: bool = false,
    conference_supported: bool = false,
    id: i64,
    access_hash: i64,
    date: i32,
    admin_id: i64,
    participant_id: i64,
    g_a_or_b: []const u8,
    key_fingerprint: i64,
    protocol: api.PhoneCallProtocol,
    connections: []api.PhoneConnection,
    start_date: i32,
    custom_parameters: ?api.DataJSON = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.p2p_allowed) flags |= 1 << 5;
        if (self.video) flags |= 1 << 6;
        if (self.conference_supported) flags |= 1 << 8;
        if (self.custom_parameters != null) flags |= 1 << 7;
        try w.writeUInt(flags);
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeInt(self.date);
        try w.writeLong(self.admin_id);
        try w.writeLong(self.participant_id);
        try w.writeBytes(self.g_a_or_b);
        try w.writeLong(self.key_fingerprint);
        try self.protocol.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.connections.len);
        for (self.connections) |elem_1906| {
            try elem_1906.serialize(w);
        }
        try w.writeInt(self.start_date);
        if (self.custom_parameters) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.p2p_allowed = (flags >> 5) & 1 != 0;
        self.video = (flags >> 6) & 1 != 0;
        self.conference_supported = (flags >> 8) & 1 != 0;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.date = try r.readInt();
        self.admin_id = try r.readLong();
        self.participant_id = try r.readLong();
        self.g_a_or_b = try r.readBytes();
        self.key_fingerprint = try r.readLong();
        self.protocol = try api.PhoneCallProtocol.deserialize(allocator, r);
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1907 = try r.readVectorLength();
        const vec_1908 = allocator.alloc(api.PhoneConnection, len_1907) catch return error.OutOfMemory;
        for (vec_1908) |*elem_1909| {
            elem_1909.* = try api.PhoneConnection.deserialize(allocator, r);
        }
        self.connections = vec_1908;
        self.start_date = try r.readInt();
        if ((flags >> 7) & 1 != 0) {
            self.custom_parameters = try api.DataJSON.deserialize(allocator, r);
        } else {
            self.custom_parameters = null;
        }
        return self;
    }
};

pub const phoneCallDiscarded = struct {
    pub const constructor_id: u32 = 0x50ca4de1;
    need_rating: bool = false,
    need_debug: bool = false,
    video: bool = false,
    id: i64,
    reason: ?api.PhoneCallDiscardReason = null,
    duration: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.need_rating) flags |= 1 << 2;
        if (self.need_debug) flags |= 1 << 3;
        if (self.video) flags |= 1 << 6;
        if (self.reason != null) flags |= 1 << 0;
        if (self.duration != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeLong(self.id);
        if (self.reason) |v| {
            try v.serialize(w);
        }
        if (self.duration) |v| {
            try w.writeInt(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.need_rating = (flags >> 2) & 1 != 0;
        self.need_debug = (flags >> 3) & 1 != 0;
        self.video = (flags >> 6) & 1 != 0;
        self.id = try r.readLong();
        if ((flags >> 0) & 1 != 0) {
            self.reason = try api.PhoneCallDiscardReason.deserialize(allocator, r);
        } else {
            self.reason = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.duration = try r.readInt();
        } else {
            self.duration = null;
        }
        return self;
    }
};

pub const phoneCallProtocol = struct {
    pub const constructor_id: u32 = 0xfc878fc8;
    udp_p2p: bool = false,
    udp_reflector: bool = false,
    min_layer: i32,
    max_layer: i32,
    library_versions: [][]const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.udp_p2p) flags |= 1 << 0;
        if (self.udp_reflector) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeInt(self.min_layer);
        try w.writeInt(self.max_layer);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.library_versions.len);
        for (self.library_versions) |elem_1910| {
            try w.writeString(elem_1910);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.udp_p2p = (flags >> 0) & 1 != 0;
        self.udp_reflector = (flags >> 1) & 1 != 0;
        self.min_layer = try r.readInt();
        self.max_layer = try r.readInt();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1911 = try r.readVectorLength();
        const vec_1912 = allocator.alloc([]const u8, len_1911) catch return error.OutOfMemory;
        for (vec_1912) |*elem_1913| {
            elem_1913.* = try r.readString();
        }
        self.library_versions = vec_1912;
        return self;
    }
};

pub const phoneCall_ = struct {
    pub const constructor_id: u32 = 0xec82e140;
    phone_call: api.PhoneCall,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.phone_call.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1914| {
            try elem_1914.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.phone_call = try api.PhoneCall.deserialize(allocator, r);
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1915 = try r.readVectorLength();
        const vec_1916 = allocator.alloc(api.User, len_1915) catch return error.OutOfMemory;
        for (vec_1916) |*elem_1917| {
            elem_1917.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1916;
        return self;
    }
};

pub const groupCallDiscarded = struct {
    pub const constructor_id: u32 = 0x7780bcb4;
    id: i64,
    access_hash: i64,
    duration: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeInt(self.duration);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.duration = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const groupCall = struct {
    pub const constructor_id: u32 = 0xefb2b617;
    join_muted: bool = false,
    can_change_join_muted: bool = false,
    join_date_asc: bool = false,
    schedule_start_subscribed: bool = false,
    can_start_video: bool = false,
    record_video_active: bool = false,
    rtmp_stream: bool = false,
    listeners_hidden: bool = false,
    conference: bool = false,
    creator: bool = false,
    messages_enabled: bool = false,
    can_change_messages_enabled: bool = false,
    min: bool = false,
    id: i64,
    access_hash: i64,
    participants_count: i32,
    title: ?[]const u8 = null,
    stream_dc_id: ?i32 = null,
    record_start_date: ?i32 = null,
    schedule_date: ?i32 = null,
    unmuted_video_count: ?i32 = null,
    unmuted_video_limit: i32,
    version: i32,
    invite_link: ?[]const u8 = null,
    send_paid_messages_stars: ?i64 = null,
    default_send_as: ?api.Peer = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.join_muted) flags |= 1 << 1;
        if (self.can_change_join_muted) flags |= 1 << 2;
        if (self.join_date_asc) flags |= 1 << 6;
        if (self.schedule_start_subscribed) flags |= 1 << 8;
        if (self.can_start_video) flags |= 1 << 9;
        if (self.record_video_active) flags |= 1 << 11;
        if (self.rtmp_stream) flags |= 1 << 12;
        if (self.listeners_hidden) flags |= 1 << 13;
        if (self.conference) flags |= 1 << 14;
        if (self.creator) flags |= 1 << 15;
        if (self.messages_enabled) flags |= 1 << 17;
        if (self.can_change_messages_enabled) flags |= 1 << 18;
        if (self.min) flags |= 1 << 19;
        if (self.title != null) flags |= 1 << 3;
        if (self.stream_dc_id != null) flags |= 1 << 4;
        if (self.record_start_date != null) flags |= 1 << 5;
        if (self.schedule_date != null) flags |= 1 << 7;
        if (self.unmuted_video_count != null) flags |= 1 << 10;
        if (self.invite_link != null) flags |= 1 << 16;
        if (self.send_paid_messages_stars != null) flags |= 1 << 20;
        if (self.default_send_as != null) flags |= 1 << 21;
        try w.writeUInt(flags);
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeInt(self.participants_count);
        if (self.title) |v| {
            try w.writeString(v);
        }
        if (self.stream_dc_id) |v| {
            try w.writeInt(v);
        }
        if (self.record_start_date) |v| {
            try w.writeInt(v);
        }
        if (self.schedule_date) |v| {
            try w.writeInt(v);
        }
        if (self.unmuted_video_count) |v| {
            try w.writeInt(v);
        }
        try w.writeInt(self.unmuted_video_limit);
        try w.writeInt(self.version);
        if (self.invite_link) |v| {
            try w.writeString(v);
        }
        if (self.send_paid_messages_stars) |v| {
            try w.writeLong(v);
        }
        if (self.default_send_as) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.join_muted = (flags >> 1) & 1 != 0;
        self.can_change_join_muted = (flags >> 2) & 1 != 0;
        self.join_date_asc = (flags >> 6) & 1 != 0;
        self.schedule_start_subscribed = (flags >> 8) & 1 != 0;
        self.can_start_video = (flags >> 9) & 1 != 0;
        self.record_video_active = (flags >> 11) & 1 != 0;
        self.rtmp_stream = (flags >> 12) & 1 != 0;
        self.listeners_hidden = (flags >> 13) & 1 != 0;
        self.conference = (flags >> 14) & 1 != 0;
        self.creator = (flags >> 15) & 1 != 0;
        self.messages_enabled = (flags >> 17) & 1 != 0;
        self.can_change_messages_enabled = (flags >> 18) & 1 != 0;
        self.min = (flags >> 19) & 1 != 0;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.participants_count = try r.readInt();
        if ((flags >> 3) & 1 != 0) {
            self.title = try r.readString();
        } else {
            self.title = null;
        }
        if ((flags >> 4) & 1 != 0) {
            self.stream_dc_id = try r.readInt();
        } else {
            self.stream_dc_id = null;
        }
        if ((flags >> 5) & 1 != 0) {
            self.record_start_date = try r.readInt();
        } else {
            self.record_start_date = null;
        }
        if ((flags >> 7) & 1 != 0) {
            self.schedule_date = try r.readInt();
        } else {
            self.schedule_date = null;
        }
        if ((flags >> 10) & 1 != 0) {
            self.unmuted_video_count = try r.readInt();
        } else {
            self.unmuted_video_count = null;
        }
        self.unmuted_video_limit = try r.readInt();
        self.version = try r.readInt();
        if ((flags >> 16) & 1 != 0) {
            self.invite_link = try r.readString();
        } else {
            self.invite_link = null;
        }
        if ((flags >> 20) & 1 != 0) {
            self.send_paid_messages_stars = try r.readLong();
        } else {
            self.send_paid_messages_stars = null;
        }
        if ((flags >> 21) & 1 != 0) {
            self.default_send_as = try api.Peer.deserialize(allocator, r);
        } else {
            self.default_send_as = null;
        }
        return self;
    }
};

pub const inputGroupCall = struct {
    pub const constructor_id: u32 = 0xd8aa840f;
    id: i64,
    access_hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const inputGroupCallSlug = struct {
    pub const constructor_id: u32 = 0xfe06823f;
    slug: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.slug);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.slug = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const inputGroupCallInviteMessage = struct {
    pub const constructor_id: u32 = 0x8c10603f;
    msg_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.msg_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.msg_id = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const groupCallParticipant = struct {
    pub const constructor_id: u32 = 0x2a3dc7ac;
    muted: bool = false,
    left: bool = false,
    can_self_unmute: bool = false,
    just_joined: bool = false,
    versioned: bool = false,
    min: bool = false,
    muted_by_you: bool = false,
    volume_by_admin: bool = false,
    self: bool = false,
    video_joined: bool = false,
    peer: api.Peer,
    date: i32,
    active_date: ?i32 = null,
    source: i32,
    volume: ?i32 = null,
    about: ?[]const u8 = null,
    raise_hand_rating: ?i64 = null,
    video: ?api.GroupCallParticipantVideo = null,
    presentation: ?api.GroupCallParticipantVideo = null,
    paid_stars_total: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.muted) flags |= 1 << 0;
        if (self.left) flags |= 1 << 1;
        if (self.can_self_unmute) flags |= 1 << 2;
        if (self.just_joined) flags |= 1 << 4;
        if (self.versioned) flags |= 1 << 5;
        if (self.min) flags |= 1 << 8;
        if (self.muted_by_you) flags |= 1 << 9;
        if (self.volume_by_admin) flags |= 1 << 10;
        if (self.self) flags |= 1 << 12;
        if (self.video_joined) flags |= 1 << 15;
        if (self.active_date != null) flags |= 1 << 3;
        if (self.volume != null) flags |= 1 << 7;
        if (self.about != null) flags |= 1 << 11;
        if (self.raise_hand_rating != null) flags |= 1 << 13;
        if (self.video != null) flags |= 1 << 6;
        if (self.presentation != null) flags |= 1 << 14;
        if (self.paid_stars_total != null) flags |= 1 << 16;
        try w.writeUInt(flags);
        try self.peer.serialize(w);
        try w.writeInt(self.date);
        if (self.active_date) |v| {
            try w.writeInt(v);
        }
        try w.writeInt(self.source);
        if (self.volume) |v| {
            try w.writeInt(v);
        }
        if (self.about) |v| {
            try w.writeString(v);
        }
        if (self.raise_hand_rating) |v| {
            try w.writeLong(v);
        }
        if (self.video) |v| {
            try v.serialize(w);
        }
        if (self.presentation) |v| {
            try v.serialize(w);
        }
        if (self.paid_stars_total) |v| {
            try w.writeLong(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.muted = (flags >> 0) & 1 != 0;
        self.left = (flags >> 1) & 1 != 0;
        self.can_self_unmute = (flags >> 2) & 1 != 0;
        self.just_joined = (flags >> 4) & 1 != 0;
        self.versioned = (flags >> 5) & 1 != 0;
        self.min = (flags >> 8) & 1 != 0;
        self.muted_by_you = (flags >> 9) & 1 != 0;
        self.volume_by_admin = (flags >> 10) & 1 != 0;
        self.self = (flags >> 12) & 1 != 0;
        self.video_joined = (flags >> 15) & 1 != 0;
        self.peer = try api.Peer.deserialize(allocator, r);
        self.date = try r.readInt();
        if ((flags >> 3) & 1 != 0) {
            self.active_date = try r.readInt();
        } else {
            self.active_date = null;
        }
        self.source = try r.readInt();
        if ((flags >> 7) & 1 != 0) {
            self.volume = try r.readInt();
        } else {
            self.volume = null;
        }
        if ((flags >> 11) & 1 != 0) {
            self.about = try r.readString();
        } else {
            self.about = null;
        }
        if ((flags >> 13) & 1 != 0) {
            self.raise_hand_rating = try r.readLong();
        } else {
            self.raise_hand_rating = null;
        }
        if ((flags >> 6) & 1 != 0) {
            self.video = try api.GroupCallParticipantVideo.deserialize(allocator, r);
        } else {
            self.video = null;
        }
        if ((flags >> 14) & 1 != 0) {
            self.presentation = try api.GroupCallParticipantVideo.deserialize(allocator, r);
        } else {
            self.presentation = null;
        }
        if ((flags >> 16) & 1 != 0) {
            self.paid_stars_total = try r.readLong();
        } else {
            self.paid_stars_total = null;
        }
        return self;
    }
};

pub const groupCall_ = struct {
    pub const constructor_id: u32 = 0x9e727aad;
    call: api.GroupCall,
    participants: []api.GroupCallParticipant,
    participants_next_offset: []const u8,
    chats: []api.Chat,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.call.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.participants.len);
        for (self.participants) |elem_1918| {
            try elem_1918.serialize(w);
        }
        try w.writeString(self.participants_next_offset);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_1919| {
            try elem_1919.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1920| {
            try elem_1920.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.call = try api.GroupCall.deserialize(allocator, r);
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1921 = try r.readVectorLength();
        const vec_1922 = allocator.alloc(api.GroupCallParticipant, len_1921) catch return error.OutOfMemory;
        for (vec_1922) |*elem_1923| {
            elem_1923.* = try api.GroupCallParticipant.deserialize(allocator, r);
        }
        self.participants = vec_1922;
        self.participants_next_offset = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1924 = try r.readVectorLength();
        const vec_1925 = allocator.alloc(api.Chat, len_1924) catch return error.OutOfMemory;
        for (vec_1925) |*elem_1926| {
            elem_1926.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_1925;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1927 = try r.readVectorLength();
        const vec_1928 = allocator.alloc(api.User, len_1927) catch return error.OutOfMemory;
        for (vec_1928) |*elem_1929| {
            elem_1929.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1928;
        return self;
    }
};

pub const groupParticipants = struct {
    pub const constructor_id: u32 = 0xf47751b6;
    count: i32,
    participants: []api.GroupCallParticipant,
    next_offset: []const u8,
    chats: []api.Chat,
    users: []api.User,
    version: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.count);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.participants.len);
        for (self.participants) |elem_1930| {
            try elem_1930.serialize(w);
        }
        try w.writeString(self.next_offset);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_1931| {
            try elem_1931.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1932| {
            try elem_1932.serialize(w);
        }
        try w.writeInt(self.version);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.count = try r.readInt();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1933 = try r.readVectorLength();
        const vec_1934 = allocator.alloc(api.GroupCallParticipant, len_1933) catch return error.OutOfMemory;
        for (vec_1934) |*elem_1935| {
            elem_1935.* = try api.GroupCallParticipant.deserialize(allocator, r);
        }
        self.participants = vec_1934;
        self.next_offset = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1936 = try r.readVectorLength();
        const vec_1937 = allocator.alloc(api.Chat, len_1936) catch return error.OutOfMemory;
        for (vec_1937) |*elem_1938| {
            elem_1938.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_1937;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1939 = try r.readVectorLength();
        const vec_1940 = allocator.alloc(api.User, len_1939) catch return error.OutOfMemory;
        for (vec_1940) |*elem_1941| {
            elem_1941.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1940;
        self.version = try r.readInt();
        return self;
    }
};

pub const joinAsPeers = struct {
    pub const constructor_id: u32 = 0xafe5623f;
    peers: []api.Peer,
    chats: []api.Chat,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.peers.len);
        for (self.peers) |elem_1942| {
            try elem_1942.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_1943| {
            try elem_1943.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1944| {
            try elem_1944.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1945 = try r.readVectorLength();
        const vec_1946 = allocator.alloc(api.Peer, len_1945) catch return error.OutOfMemory;
        for (vec_1946) |*elem_1947| {
            elem_1947.* = try api.Peer.deserialize(allocator, r);
        }
        self.peers = vec_1946;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1948 = try r.readVectorLength();
        const vec_1949 = allocator.alloc(api.Chat, len_1948) catch return error.OutOfMemory;
        for (vec_1949) |*elem_1950| {
            elem_1950.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_1949;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1951 = try r.readVectorLength();
        const vec_1952 = allocator.alloc(api.User, len_1951) catch return error.OutOfMemory;
        for (vec_1952) |*elem_1953| {
            elem_1953.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1952;
        return self;
    }
};

pub const exportedGroupCallInvite = struct {
    pub const constructor_id: u32 = 0x204bd158;
    link: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.link);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.link = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const groupCallParticipantVideoSourceGroup = struct {
    pub const constructor_id: u32 = 0xdcb118b7;
    semantics: []const u8,
    sources: []i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.semantics);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.sources.len);
        for (self.sources) |elem_1954| {
            try w.writeInt(elem_1954);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.semantics = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1955 = try r.readVectorLength();
        const vec_1956 = allocator.alloc(i32, len_1955) catch return error.OutOfMemory;
        for (vec_1956) |*elem_1957| {
            elem_1957.* = try r.readInt();
        }
        self.sources = vec_1956;
        return self;
    }
};

pub const groupCallParticipantVideo = struct {
    pub const constructor_id: u32 = 0x67753ac8;
    paused: bool = false,
    endpoint: []const u8,
    source_groups: []api.GroupCallParticipantVideoSourceGroup,
    audio_source: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.paused) flags |= 1 << 0;
        if (self.audio_source != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeString(self.endpoint);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.source_groups.len);
        for (self.source_groups) |elem_1958| {
            try elem_1958.serialize(w);
        }
        if (self.audio_source) |v| {
            try w.writeInt(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.paused = (flags >> 0) & 1 != 0;
        self.endpoint = try r.readString();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1959 = try r.readVectorLength();
        const vec_1960 = allocator.alloc(api.GroupCallParticipantVideoSourceGroup, len_1959) catch return error.OutOfMemory;
        for (vec_1960) |*elem_1961| {
            elem_1961.* = try api.GroupCallParticipantVideoSourceGroup.deserialize(allocator, r);
        }
        self.source_groups = vec_1960;
        if ((flags >> 1) & 1 != 0) {
            self.audio_source = try r.readInt();
        } else {
            self.audio_source = null;
        }
        return self;
    }
};

pub const groupCallStreamChannel = struct {
    pub const constructor_id: u32 = 0x80eb48af;
    channel: i32,
    scale: i32,
    last_timestamp_ms: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeInt(self.channel);
        try w.writeInt(self.scale);
        try w.writeLong(self.last_timestamp_ms);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.channel = try r.readInt();
        self.scale = try r.readInt();
        self.last_timestamp_ms = try r.readLong();
        _ = allocator;
        return self;
    }
};

pub const groupCallStreamChannels = struct {
    pub const constructor_id: u32 = 0xd0e482b2;
    channels: []api.GroupCallStreamChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.channels.len);
        for (self.channels) |elem_1962| {
            try elem_1962.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1963 = try r.readVectorLength();
        const vec_1964 = allocator.alloc(api.GroupCallStreamChannel, len_1963) catch return error.OutOfMemory;
        for (vec_1964) |*elem_1965| {
            elem_1965.* = try api.GroupCallStreamChannel.deserialize(allocator, r);
        }
        self.channels = vec_1964;
        return self;
    }
};

pub const groupCallStreamRtmpUrl = struct {
    pub const constructor_id: u32 = 0x2dbf3432;
    url: []const u8,
    key: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.url);
        try w.writeString(self.key);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.url = try r.readString();
        self.key = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const groupCallMessage = struct {
    pub const constructor_id: u32 = 0x1a8afc7e;
    from_admin: bool = false,
    id: i32,
    from_id: api.Peer,
    date: i32,
    message: api.TextWithEntities,
    paid_message_stars: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.from_admin) flags |= 1 << 1;
        if (self.paid_message_stars != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeInt(self.id);
        try self.from_id.serialize(w);
        try w.writeInt(self.date);
        try self.message.serialize(w);
        if (self.paid_message_stars) |v| {
            try w.writeLong(v);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.from_admin = (flags >> 1) & 1 != 0;
        self.id = try r.readInt();
        self.from_id = try api.Peer.deserialize(allocator, r);
        self.date = try r.readInt();
        self.message = try api.TextWithEntities.deserialize(allocator, r);
        if ((flags >> 0) & 1 != 0) {
            self.paid_message_stars = try r.readLong();
        } else {
            self.paid_message_stars = null;
        }
        return self;
    }
};

pub const groupCallDonor = struct {
    pub const constructor_id: u32 = 0xee430c85;
    top: bool = false,
    my: bool = false,
    peer_id: ?api.Peer = null,
    stars: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.top) flags |= 1 << 0;
        if (self.my) flags |= 1 << 1;
        if (self.peer_id != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        if (self.peer_id) |v| {
            try v.serialize(w);
        }
        try w.writeLong(self.stars);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.top = (flags >> 0) & 1 != 0;
        self.my = (flags >> 1) & 1 != 0;
        if ((flags >> 3) & 1 != 0) {
            self.peer_id = try api.Peer.deserialize(allocator, r);
        } else {
            self.peer_id = null;
        }
        self.stars = try r.readLong();
        return self;
    }
};

pub const groupCallStars = struct {
    pub const constructor_id: u32 = 0x9d1dbd26;
    total_stars: i64,
    top_donors: []api.GroupCallDonor,
    chats: []api.Chat,
    users: []api.User,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.total_stars);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.top_donors.len);
        for (self.top_donors) |elem_1966| {
            try elem_1966.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.chats.len);
        for (self.chats) |elem_1967| {
            try elem_1967.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_1968| {
            try elem_1968.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.total_stars = try r.readLong();
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1969 = try r.readVectorLength();
        const vec_1970 = allocator.alloc(api.GroupCallDonor, len_1969) catch return error.OutOfMemory;
        for (vec_1970) |*elem_1971| {
            elem_1971.* = try api.GroupCallDonor.deserialize(allocator, r);
        }
        self.top_donors = vec_1970;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1972 = try r.readVectorLength();
        const vec_1973 = allocator.alloc(api.Chat, len_1972) catch return error.OutOfMemory;
        for (vec_1973) |*elem_1974| {
            elem_1974.* = try api.Chat.deserialize(allocator, r);
        }
        self.chats = vec_1973;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_1975 = try r.readVectorLength();
        const vec_1976 = allocator.alloc(api.User, len_1975) catch return error.OutOfMemory;
        for (vec_1976) |*elem_1977| {
            elem_1977.* = try api.User.deserialize(allocator, r);
        }
        self.users = vec_1976;
        return self;
    }
};

pub const PhoneCallDiscardReason = union(enum) {
    phoneCallDiscardReasonMissed: api.phoneCallDiscardReasonMissed,
    phoneCallDiscardReasonDisconnect: api.phoneCallDiscardReasonDisconnect,
    phoneCallDiscardReasonHangup: api.phoneCallDiscardReasonHangup,
    phoneCallDiscardReasonBusy: api.phoneCallDiscardReasonBusy,
    phoneCallDiscardReasonMigrateConferenceCall: api.phoneCallDiscardReasonMigrateConferenceCall,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phoneCallDiscardReasonMissed.constructor_id => return .{ .phoneCallDiscardReasonMissed = try api.phoneCallDiscardReasonMissed.deserialize(allocator, r) },
            api.phoneCallDiscardReasonDisconnect.constructor_id => return .{ .phoneCallDiscardReasonDisconnect = try api.phoneCallDiscardReasonDisconnect.deserialize(allocator, r) },
            api.phoneCallDiscardReasonHangup.constructor_id => return .{ .phoneCallDiscardReasonHangup = try api.phoneCallDiscardReasonHangup.deserialize(allocator, r) },
            api.phoneCallDiscardReasonBusy.constructor_id => return .{ .phoneCallDiscardReasonBusy = try api.phoneCallDiscardReasonBusy.deserialize(allocator, r) },
            api.phoneCallDiscardReasonMigrateConferenceCall.constructor_id => return .{ .phoneCallDiscardReasonMigrateConferenceCall = try api.phoneCallDiscardReasonMigrateConferenceCall.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputPhoneCall = union(enum) {
    inputPhoneCall: api.inputPhoneCall,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputPhoneCall.constructor_id => return .{ .inputPhoneCall = try api.inputPhoneCall.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PhoneCall = union(enum) {
    phoneCallEmpty: api.phoneCallEmpty,
    phoneCallWaiting: api.phoneCallWaiting,
    phoneCallRequested: api.phoneCallRequested,
    phoneCallAccepted: api.phoneCallAccepted,
    phoneCall: api.phoneCall,
    phoneCallDiscarded: api.phoneCallDiscarded,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phoneCallEmpty.constructor_id => return .{ .phoneCallEmpty = try api.phoneCallEmpty.deserialize(allocator, r) },
            api.phoneCallWaiting.constructor_id => return .{ .phoneCallWaiting = try api.phoneCallWaiting.deserialize(allocator, r) },
            api.phoneCallRequested.constructor_id => return .{ .phoneCallRequested = try api.phoneCallRequested.deserialize(allocator, r) },
            api.phoneCallAccepted.constructor_id => return .{ .phoneCallAccepted = try api.phoneCallAccepted.deserialize(allocator, r) },
            api.phoneCall.constructor_id => return .{ .phoneCall = try api.phoneCall.deserialize(allocator, r) },
            api.phoneCallDiscarded.constructor_id => return .{ .phoneCallDiscarded = try api.phoneCallDiscarded.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PhoneCallProtocol = union(enum) {
    phoneCallProtocol: api.phoneCallProtocol,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phoneCallProtocol.constructor_id => return .{ .phoneCallProtocol = try api.phoneCallProtocol.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PhoneCall_ = union(enum) {
    phoneCall: api.phone.phoneCall,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.phoneCall.constructor_id => return .{ .phoneCall = try api.phone.phoneCall.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCall = union(enum) {
    groupCallDiscarded: api.groupCallDiscarded,
    groupCall: api.groupCall,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.groupCallDiscarded.constructor_id => return .{ .groupCallDiscarded = try api.groupCallDiscarded.deserialize(allocator, r) },
            api.groupCall.constructor_id => return .{ .groupCall = try api.groupCall.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputGroupCall = union(enum) {
    inputGroupCall: api.inputGroupCall,
    inputGroupCallSlug: api.inputGroupCallSlug,
    inputGroupCallInviteMessage: api.inputGroupCallInviteMessage,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputGroupCall.constructor_id => return .{ .inputGroupCall = try api.inputGroupCall.deserialize(allocator, r) },
            api.inputGroupCallSlug.constructor_id => return .{ .inputGroupCallSlug = try api.inputGroupCallSlug.deserialize(allocator, r) },
            api.inputGroupCallInviteMessage.constructor_id => return .{ .inputGroupCallInviteMessage = try api.inputGroupCallInviteMessage.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallParticipant = union(enum) {
    groupCallParticipant: api.groupCallParticipant,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.groupCallParticipant.constructor_id => return .{ .groupCallParticipant = try api.groupCallParticipant.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCall_ = union(enum) {
    groupCall: api.phone.groupCall,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.groupCall.constructor_id => return .{ .groupCall = try api.phone.groupCall.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupParticipants = union(enum) {
    groupParticipants: api.phone.groupParticipants,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.groupParticipants.constructor_id => return .{ .groupParticipants = try api.phone.groupParticipants.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const JoinAsPeers = union(enum) {
    joinAsPeers: api.phone.joinAsPeers,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.joinAsPeers.constructor_id => return .{ .joinAsPeers = try api.phone.joinAsPeers.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const ExportedGroupCallInvite = union(enum) {
    exportedGroupCallInvite: api.phone.exportedGroupCallInvite,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.exportedGroupCallInvite.constructor_id => return .{ .exportedGroupCallInvite = try api.phone.exportedGroupCallInvite.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallParticipantVideoSourceGroup = union(enum) {
    groupCallParticipantVideoSourceGroup: api.groupCallParticipantVideoSourceGroup,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.groupCallParticipantVideoSourceGroup.constructor_id => return .{ .groupCallParticipantVideoSourceGroup = try api.groupCallParticipantVideoSourceGroup.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallParticipantVideo = union(enum) {
    groupCallParticipantVideo: api.groupCallParticipantVideo,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.groupCallParticipantVideo.constructor_id => return .{ .groupCallParticipantVideo = try api.groupCallParticipantVideo.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallStreamChannel = union(enum) {
    groupCallStreamChannel: api.groupCallStreamChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.groupCallStreamChannel.constructor_id => return .{ .groupCallStreamChannel = try api.groupCallStreamChannel.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallStreamChannels = union(enum) {
    groupCallStreamChannels: api.phone.groupCallStreamChannels,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.groupCallStreamChannels.constructor_id => return .{ .groupCallStreamChannels = try api.phone.groupCallStreamChannels.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallStreamRtmpUrl = union(enum) {
    groupCallStreamRtmpUrl: api.phone.groupCallStreamRtmpUrl,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.groupCallStreamRtmpUrl.constructor_id => return .{ .groupCallStreamRtmpUrl = try api.phone.groupCallStreamRtmpUrl.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallMessage = union(enum) {
    groupCallMessage: api.groupCallMessage,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.groupCallMessage.constructor_id => return .{ .groupCallMessage = try api.groupCallMessage.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallDonor = union(enum) {
    groupCallDonor: api.groupCallDonor,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.groupCallDonor.constructor_id => return .{ .groupCallDonor = try api.groupCallDonor.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const GroupCallStars = union(enum) {
    groupCallStars: api.phone.groupCallStars,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.phone.groupCallStars.constructor_id => return .{ .groupCallStars = try api.phone.groupCallStars.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

