//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const secureFileEmpty = struct {
    pub const constructor_id: u32 = 0x64199744;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureFile = struct {
    pub const constructor_id: u32 = 0x7d09c27e;
    id: i64,
    access_hash: i64,
    size: i64,
    dc_id: i32,
    date: i32,
    file_hash: []const u8,
    secret: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.id);
        try w.writeLong(self.access_hash);
        try w.writeLong(self.size);
        try w.writeInt(self.dc_id);
        try w.writeInt(self.date);
        try w.writeBytes(self.file_hash);
        try w.writeBytes(self.secret);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.id = try r.readLong();
        self.access_hash = try r.readLong();
        self.size = try r.readLong();
        self.dc_id = try r.readInt();
        self.date = try r.readInt();
        self.file_hash = try r.readBytes();
        self.secret = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const secureData = struct {
    pub const constructor_id: u32 = 0x8aeabec3;
    data: []const u8,
    data_hash: []const u8,
    secret: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeBytes(self.data);
        try w.writeBytes(self.data_hash);
        try w.writeBytes(self.secret);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.data = try r.readBytes();
        self.data_hash = try r.readBytes();
        self.secret = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const securePlainPhone = struct {
    pub const constructor_id: u32 = 0x7d6099dd;
    phone: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.phone);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.phone = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const securePlainEmail = struct {
    pub const constructor_id: u32 = 0x21ec5a5f;
    email: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.email);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.email = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const secureValueTypePersonalDetails = struct {
    pub const constructor_id: u32 = 0x9d2a81e3;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypePassport = struct {
    pub const constructor_id: u32 = 0x3dac6a00;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeDriverLicense = struct {
    pub const constructor_id: u32 = 0x06e425c4;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeIdentityCard = struct {
    pub const constructor_id: u32 = 0xa0d0744b;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeInternalPassport = struct {
    pub const constructor_id: u32 = 0x99a48f23;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeAddress = struct {
    pub const constructor_id: u32 = 0xcbe31e26;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeUtilityBill = struct {
    pub const constructor_id: u32 = 0xfc36954e;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeBankStatement = struct {
    pub const constructor_id: u32 = 0x89137c0d;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeRentalAgreement = struct {
    pub const constructor_id: u32 = 0x8b883488;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypePassportRegistration = struct {
    pub const constructor_id: u32 = 0x99e3806a;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeTemporaryRegistration = struct {
    pub const constructor_id: u32 = 0xea02ec33;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypePhone = struct {
    pub const constructor_id: u32 = 0xb320aadb;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValueTypeEmail = struct {
    pub const constructor_id: u32 = 0x8e3ca7ee;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const secureValue = struct {
    pub const constructor_id: u32 = 0x187fa0ca;
    type_: api.SecureValueType,
    data: ?api.SecureData = null,
    front_side: ?api.SecureFile = null,
    reverse_side: ?api.SecureFile = null,
    selfie: ?api.SecureFile = null,
    translation: ?[]api.SecureFile = null,
    files: ?[]api.SecureFile = null,
    plain_data: ?api.SecurePlainData = null,
    hash: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.data != null) flags |= 1 << 0;
        if (self.front_side != null) flags |= 1 << 1;
        if (self.reverse_side != null) flags |= 1 << 2;
        if (self.selfie != null) flags |= 1 << 3;
        if (self.translation != null) flags |= 1 << 6;
        if (self.files != null) flags |= 1 << 4;
        if (self.plain_data != null) flags |= 1 << 5;
        try w.writeUInt(flags);
        try self.type_.serialize(w);
        if (self.data) |v| {
            try v.serialize(w);
        }
        if (self.front_side) |v| {
            try v.serialize(w);
        }
        if (self.reverse_side) |v| {
            try v.serialize(w);
        }
        if (self.selfie) |v| {
            try v.serialize(w);
        }
        if (self.translation) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2202| {
                try elem_2202.serialize(w);
            }
        }
        if (self.files) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2203| {
                try elem_2203.serialize(w);
            }
        }
        if (self.plain_data) |v| {
            try v.serialize(w);
        }
        try w.writeBytes(self.hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        if ((flags >> 0) & 1 != 0) {
            self.data = try api.SecureData.deserialize(allocator, r);
        } else {
            self.data = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.front_side = try api.SecureFile.deserialize(allocator, r);
        } else {
            self.front_side = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.reverse_side = try api.SecureFile.deserialize(allocator, r);
        } else {
            self.reverse_side = null;
        }
        if ((flags >> 3) & 1 != 0) {
            self.selfie = try api.SecureFile.deserialize(allocator, r);
        } else {
            self.selfie = null;
        }
        if ((flags >> 6) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_2204 = try r.readVectorLength();
            const vec_2205 = allocator.alloc(api.SecureFile, len_2204) catch return error.OutOfMemory;
            for (vec_2205) |*elem_2206| {
                elem_2206.* = try api.SecureFile.deserialize(allocator, r);
            }
            self.translation = vec_2205;
        } else {
            self.translation = null;
        }
        if ((flags >> 4) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_2207 = try r.readVectorLength();
            const vec_2208 = allocator.alloc(api.SecureFile, len_2207) catch return error.OutOfMemory;
            for (vec_2208) |*elem_2209| {
                elem_2209.* = try api.SecureFile.deserialize(allocator, r);
            }
            self.files = vec_2208;
        } else {
            self.files = null;
        }
        if ((flags >> 5) & 1 != 0) {
            self.plain_data = try api.SecurePlainData.deserialize(allocator, r);
        } else {
            self.plain_data = null;
        }
        self.hash = try r.readBytes();
        return self;
    }
};

pub const inputSecureValue = struct {
    pub const constructor_id: u32 = 0xdb21d0a7;
    type_: api.SecureValueType,
    data: ?api.SecureData = null,
    front_side: ?api.InputSecureFile = null,
    reverse_side: ?api.InputSecureFile = null,
    selfie: ?api.InputSecureFile = null,
    translation: ?[]api.InputSecureFile = null,
    files: ?[]api.InputSecureFile = null,
    plain_data: ?api.SecurePlainData = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.data != null) flags |= 1 << 0;
        if (self.front_side != null) flags |= 1 << 1;
        if (self.reverse_side != null) flags |= 1 << 2;
        if (self.selfie != null) flags |= 1 << 3;
        if (self.translation != null) flags |= 1 << 6;
        if (self.files != null) flags |= 1 << 4;
        if (self.plain_data != null) flags |= 1 << 5;
        try w.writeUInt(flags);
        try self.type_.serialize(w);
        if (self.data) |v| {
            try v.serialize(w);
        }
        if (self.front_side) |v| {
            try v.serialize(w);
        }
        if (self.reverse_side) |v| {
            try v.serialize(w);
        }
        if (self.selfie) |v| {
            try v.serialize(w);
        }
        if (self.translation) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2210| {
                try elem_2210.serialize(w);
            }
        }
        if (self.files) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2211| {
                try elem_2211.serialize(w);
            }
        }
        if (self.plain_data) |v| {
            try v.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        if ((flags >> 0) & 1 != 0) {
            self.data = try api.SecureData.deserialize(allocator, r);
        } else {
            self.data = null;
        }
        if ((flags >> 1) & 1 != 0) {
            self.front_side = try api.InputSecureFile.deserialize(allocator, r);
        } else {
            self.front_side = null;
        }
        if ((flags >> 2) & 1 != 0) {
            self.reverse_side = try api.InputSecureFile.deserialize(allocator, r);
        } else {
            self.reverse_side = null;
        }
        if ((flags >> 3) & 1 != 0) {
            self.selfie = try api.InputSecureFile.deserialize(allocator, r);
        } else {
            self.selfie = null;
        }
        if ((flags >> 6) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_2212 = try r.readVectorLength();
            const vec_2213 = allocator.alloc(api.InputSecureFile, len_2212) catch return error.OutOfMemory;
            for (vec_2213) |*elem_2214| {
                elem_2214.* = try api.InputSecureFile.deserialize(allocator, r);
            }
            self.translation = vec_2213;
        } else {
            self.translation = null;
        }
        if ((flags >> 4) & 1 != 0) {
            if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
            const len_2215 = try r.readVectorLength();
            const vec_2216 = allocator.alloc(api.InputSecureFile, len_2215) catch return error.OutOfMemory;
            for (vec_2216) |*elem_2217| {
                elem_2217.* = try api.InputSecureFile.deserialize(allocator, r);
            }
            self.files = vec_2216;
        } else {
            self.files = null;
        }
        if ((flags >> 5) & 1 != 0) {
            self.plain_data = try api.SecurePlainData.deserialize(allocator, r);
        } else {
            self.plain_data = null;
        }
        return self;
    }
};

pub const secureValueHash = struct {
    pub const constructor_id: u32 = 0xed1ecdb0;
    type_: api.SecureValueType,
    hash: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.hash);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.hash = try r.readBytes();
        return self;
    }
};

pub const secureValueErrorData = struct {
    pub const constructor_id: u32 = 0xe8a40bd9;
    type_: api.SecureValueType,
    data_hash: []const u8,
    field: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.data_hash);
        try w.writeString(self.field);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.data_hash = try r.readBytes();
        self.field = try r.readString();
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueErrorFrontSide = struct {
    pub const constructor_id: u32 = 0x00be3dfa;
    type_: api.SecureValueType,
    file_hash: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.file_hash);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.file_hash = try r.readBytes();
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueErrorReverseSide = struct {
    pub const constructor_id: u32 = 0x868a2aa5;
    type_: api.SecureValueType,
    file_hash: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.file_hash);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.file_hash = try r.readBytes();
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueErrorSelfie = struct {
    pub const constructor_id: u32 = 0xe537ced6;
    type_: api.SecureValueType,
    file_hash: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.file_hash);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.file_hash = try r.readBytes();
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueErrorFile = struct {
    pub const constructor_id: u32 = 0x7a700873;
    type_: api.SecureValueType,
    file_hash: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.file_hash);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.file_hash = try r.readBytes();
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueErrorFiles = struct {
    pub const constructor_id: u32 = 0x666220e9;
    type_: api.SecureValueType,
    file_hash: [][]const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.file_hash.len);
        for (self.file_hash) |elem_2218| {
            try w.writeBytes(elem_2218);
        }
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2219 = try r.readVectorLength();
        const vec_2220 = allocator.alloc([]const u8, len_2219) catch return error.OutOfMemory;
        for (vec_2220) |*elem_2221| {
            elem_2221.* = try r.readBytes();
        }
        self.file_hash = vec_2220;
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueError = struct {
    pub const constructor_id: u32 = 0x869d758f;
    type_: api.SecureValueType,
    hash: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.hash);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.hash = try r.readBytes();
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueErrorTranslationFile = struct {
    pub const constructor_id: u32 = 0xa1144770;
    type_: api.SecureValueType,
    file_hash: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeBytes(self.file_hash);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        self.file_hash = try r.readBytes();
        self.text = try r.readString();
        return self;
    }
};

pub const secureValueErrorTranslationFiles = struct {
    pub const constructor_id: u32 = 0x34636dd8;
    type_: api.SecureValueType,
    file_hash: [][]const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.type_.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.file_hash.len);
        for (self.file_hash) |elem_2222| {
            try w.writeBytes(elem_2222);
        }
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2223 = try r.readVectorLength();
        const vec_2224 = allocator.alloc([]const u8, len_2223) catch return error.OutOfMemory;
        for (vec_2224) |*elem_2225| {
            elem_2225.* = try r.readBytes();
        }
        self.file_hash = vec_2224;
        self.text = try r.readString();
        return self;
    }
};

pub const secureCredentialsEncrypted = struct {
    pub const constructor_id: u32 = 0x33f0ea47;
    data: []const u8,
    hash: []const u8,
    secret: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeBytes(self.data);
        try w.writeBytes(self.hash);
        try w.writeBytes(self.secret);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.data = try r.readBytes();
        self.hash = try r.readBytes();
        self.secret = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const passwordKdfAlgoUnknown = struct {
    pub const constructor_id: u32 = 0xd45ab096;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow = struct {
    pub const constructor_id: u32 = 0x3a912d4a;
    salt1: []const u8,
    salt2: []const u8,
    g: i32,
    p: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeBytes(self.salt1);
        try w.writeBytes(self.salt2);
        try w.writeInt(self.g);
        try w.writeBytes(self.p);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.salt1 = try r.readBytes();
        self.salt2 = try r.readBytes();
        self.g = try r.readInt();
        self.p = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const securePasswordKdfAlgoUnknown = struct {
    pub const constructor_id: u32 = 0x004a8537;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const securePasswordKdfAlgoPBKDF2HMACSHA512iter100000 = struct {
    pub const constructor_id: u32 = 0xbbf2dda0;
    salt: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeBytes(self.salt);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.salt = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const securePasswordKdfAlgoSHA512 = struct {
    pub const constructor_id: u32 = 0x86471d92;
    salt: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeBytes(self.salt);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.salt = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const secureSecretSettings = struct {
    pub const constructor_id: u32 = 0x1527bcac;
    secure_algo: api.SecurePasswordKdfAlgo,
    secure_secret: []const u8,
    secure_secret_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try self.secure_algo.serialize(w);
        try w.writeBytes(self.secure_secret);
        try w.writeLong(self.secure_secret_id);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.secure_algo = try api.SecurePasswordKdfAlgo.deserialize(allocator, r);
        self.secure_secret = try r.readBytes();
        self.secure_secret_id = try r.readLong();
        return self;
    }
};

pub const inputCheckPasswordEmpty = struct {
    pub const constructor_id: u32 = 0x9880f658;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        _ = self;
        _ = w;
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        _ = allocator;
        _ = r;
        return .{};
    }
};

pub const inputCheckPasswordSRP = struct {
    pub const constructor_id: u32 = 0xd27ff082;
    srp_id: i64,
    A: []const u8,
    M1: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeLong(self.srp_id);
        try w.writeBytes(self.A);
        try w.writeBytes(self.M1);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.srp_id = try r.readLong();
        self.A = try r.readBytes();
        self.M1 = try r.readBytes();
        _ = allocator;
        return self;
    }
};

pub const secureRequiredType = struct {
    pub const constructor_id: u32 = 0x829d99da;
    native_names: bool = false,
    selfie_required: bool = false,
    translation_required: bool = false,
    type_: api.SecureValueType,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.native_names) flags |= 1 << 0;
        if (self.selfie_required) flags |= 1 << 1;
        if (self.translation_required) flags |= 1 << 2;
        try w.writeUInt(flags);
        try self.type_.serialize(w);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.native_names = (flags >> 0) & 1 != 0;
        self.selfie_required = (flags >> 1) & 1 != 0;
        self.translation_required = (flags >> 2) & 1 != 0;
        self.type_ = try api.SecureValueType.deserialize(allocator, r);
        return self;
    }
};

pub const secureRequiredTypeOneOf = struct {
    pub const constructor_id: u32 = 0x027477b4;
    types: []*api.SecureRequiredType,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.types.len);
        for (self.types) |elem_2226| {
            try elem_2226.serialize(w);
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        if ((try r.readUInt()) != vector_constructor_id) return error.InvalidValue;
        const len_2227 = try r.readVectorLength();
        const vec_2228 = allocator.alloc(*api.SecureRequiredType, len_2227) catch return error.OutOfMemory;
        for (vec_2228) |*elem_2229| {
                        const ptr_2230 = allocator.create(api.SecureRequiredType) catch return error.OutOfMemory;
            ptr_2230.* = try api.SecureRequiredType.deserialize(allocator, r);
            elem_2229.* = ptr_2230;
        }
        self.types = vec_2228;
        return self;
    }
};

pub const SecureFile = union(enum) {
    secureFileEmpty: api.secureFileEmpty,
    secureFile: api.secureFile,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureFileEmpty.constructor_id => return .{ .secureFileEmpty = try api.secureFileEmpty.deserialize(allocator, r) },
            api.secureFile.constructor_id => return .{ .secureFile = try api.secureFile.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureData = union(enum) {
    secureData: api.secureData,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureData.constructor_id => return .{ .secureData = try api.secureData.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecurePlainData = union(enum) {
    securePlainPhone: api.securePlainPhone,
    securePlainEmail: api.securePlainEmail,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.securePlainPhone.constructor_id => return .{ .securePlainPhone = try api.securePlainPhone.deserialize(allocator, r) },
            api.securePlainEmail.constructor_id => return .{ .securePlainEmail = try api.securePlainEmail.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureValueType = union(enum) {
    secureValueTypePersonalDetails: api.secureValueTypePersonalDetails,
    secureValueTypePassport: api.secureValueTypePassport,
    secureValueTypeDriverLicense: api.secureValueTypeDriverLicense,
    secureValueTypeIdentityCard: api.secureValueTypeIdentityCard,
    secureValueTypeInternalPassport: api.secureValueTypeInternalPassport,
    secureValueTypeAddress: api.secureValueTypeAddress,
    secureValueTypeUtilityBill: api.secureValueTypeUtilityBill,
    secureValueTypeBankStatement: api.secureValueTypeBankStatement,
    secureValueTypeRentalAgreement: api.secureValueTypeRentalAgreement,
    secureValueTypePassportRegistration: api.secureValueTypePassportRegistration,
    secureValueTypeTemporaryRegistration: api.secureValueTypeTemporaryRegistration,
    secureValueTypePhone: api.secureValueTypePhone,
    secureValueTypeEmail: api.secureValueTypeEmail,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureValueTypePersonalDetails.constructor_id => return .{ .secureValueTypePersonalDetails = try api.secureValueTypePersonalDetails.deserialize(allocator, r) },
            api.secureValueTypePassport.constructor_id => return .{ .secureValueTypePassport = try api.secureValueTypePassport.deserialize(allocator, r) },
            api.secureValueTypeDriverLicense.constructor_id => return .{ .secureValueTypeDriverLicense = try api.secureValueTypeDriverLicense.deserialize(allocator, r) },
            api.secureValueTypeIdentityCard.constructor_id => return .{ .secureValueTypeIdentityCard = try api.secureValueTypeIdentityCard.deserialize(allocator, r) },
            api.secureValueTypeInternalPassport.constructor_id => return .{ .secureValueTypeInternalPassport = try api.secureValueTypeInternalPassport.deserialize(allocator, r) },
            api.secureValueTypeAddress.constructor_id => return .{ .secureValueTypeAddress = try api.secureValueTypeAddress.deserialize(allocator, r) },
            api.secureValueTypeUtilityBill.constructor_id => return .{ .secureValueTypeUtilityBill = try api.secureValueTypeUtilityBill.deserialize(allocator, r) },
            api.secureValueTypeBankStatement.constructor_id => return .{ .secureValueTypeBankStatement = try api.secureValueTypeBankStatement.deserialize(allocator, r) },
            api.secureValueTypeRentalAgreement.constructor_id => return .{ .secureValueTypeRentalAgreement = try api.secureValueTypeRentalAgreement.deserialize(allocator, r) },
            api.secureValueTypePassportRegistration.constructor_id => return .{ .secureValueTypePassportRegistration = try api.secureValueTypePassportRegistration.deserialize(allocator, r) },
            api.secureValueTypeTemporaryRegistration.constructor_id => return .{ .secureValueTypeTemporaryRegistration = try api.secureValueTypeTemporaryRegistration.deserialize(allocator, r) },
            api.secureValueTypePhone.constructor_id => return .{ .secureValueTypePhone = try api.secureValueTypePhone.deserialize(allocator, r) },
            api.secureValueTypeEmail.constructor_id => return .{ .secureValueTypeEmail = try api.secureValueTypeEmail.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureValue = union(enum) {
    secureValue: api.secureValue,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureValue.constructor_id => return .{ .secureValue = try api.secureValue.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputSecureValue = union(enum) {
    inputSecureValue: api.inputSecureValue,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputSecureValue.constructor_id => return .{ .inputSecureValue = try api.inputSecureValue.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureValueHash = union(enum) {
    secureValueHash: api.secureValueHash,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureValueHash.constructor_id => return .{ .secureValueHash = try api.secureValueHash.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureValueError = union(enum) {
    secureValueErrorData: api.secureValueErrorData,
    secureValueErrorFrontSide: api.secureValueErrorFrontSide,
    secureValueErrorReverseSide: api.secureValueErrorReverseSide,
    secureValueErrorSelfie: api.secureValueErrorSelfie,
    secureValueErrorFile: api.secureValueErrorFile,
    secureValueErrorFiles: api.secureValueErrorFiles,
    secureValueError: api.secureValueError,
    secureValueErrorTranslationFile: api.secureValueErrorTranslationFile,
    secureValueErrorTranslationFiles: api.secureValueErrorTranslationFiles,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureValueErrorData.constructor_id => return .{ .secureValueErrorData = try api.secureValueErrorData.deserialize(allocator, r) },
            api.secureValueErrorFrontSide.constructor_id => return .{ .secureValueErrorFrontSide = try api.secureValueErrorFrontSide.deserialize(allocator, r) },
            api.secureValueErrorReverseSide.constructor_id => return .{ .secureValueErrorReverseSide = try api.secureValueErrorReverseSide.deserialize(allocator, r) },
            api.secureValueErrorSelfie.constructor_id => return .{ .secureValueErrorSelfie = try api.secureValueErrorSelfie.deserialize(allocator, r) },
            api.secureValueErrorFile.constructor_id => return .{ .secureValueErrorFile = try api.secureValueErrorFile.deserialize(allocator, r) },
            api.secureValueErrorFiles.constructor_id => return .{ .secureValueErrorFiles = try api.secureValueErrorFiles.deserialize(allocator, r) },
            api.secureValueError.constructor_id => return .{ .secureValueError = try api.secureValueError.deserialize(allocator, r) },
            api.secureValueErrorTranslationFile.constructor_id => return .{ .secureValueErrorTranslationFile = try api.secureValueErrorTranslationFile.deserialize(allocator, r) },
            api.secureValueErrorTranslationFiles.constructor_id => return .{ .secureValueErrorTranslationFiles = try api.secureValueErrorTranslationFiles.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureCredentialsEncrypted = union(enum) {
    secureCredentialsEncrypted: api.secureCredentialsEncrypted,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureCredentialsEncrypted.constructor_id => return .{ .secureCredentialsEncrypted = try api.secureCredentialsEncrypted.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const PasswordKdfAlgo = union(enum) {
    passwordKdfAlgoUnknown: api.passwordKdfAlgoUnknown,
    passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow: api.passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.passwordKdfAlgoUnknown.constructor_id => return .{ .passwordKdfAlgoUnknown = try api.passwordKdfAlgoUnknown.deserialize(allocator, r) },
            api.passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow.constructor_id => return .{ .passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow = try api.passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecurePasswordKdfAlgo = union(enum) {
    securePasswordKdfAlgoUnknown: api.securePasswordKdfAlgoUnknown,
    securePasswordKdfAlgoPBKDF2HMACSHA512iter100000: api.securePasswordKdfAlgoPBKDF2HMACSHA512iter100000,
    securePasswordKdfAlgoSHA512: api.securePasswordKdfAlgoSHA512,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.securePasswordKdfAlgoUnknown.constructor_id => return .{ .securePasswordKdfAlgoUnknown = try api.securePasswordKdfAlgoUnknown.deserialize(allocator, r) },
            api.securePasswordKdfAlgoPBKDF2HMACSHA512iter100000.constructor_id => return .{ .securePasswordKdfAlgoPBKDF2HMACSHA512iter100000 = try api.securePasswordKdfAlgoPBKDF2HMACSHA512iter100000.deserialize(allocator, r) },
            api.securePasswordKdfAlgoSHA512.constructor_id => return .{ .securePasswordKdfAlgoSHA512 = try api.securePasswordKdfAlgoSHA512.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureSecretSettings = union(enum) {
    secureSecretSettings: api.secureSecretSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureSecretSettings.constructor_id => return .{ .secureSecretSettings = try api.secureSecretSettings.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const InputCheckPasswordSRP = union(enum) {
    inputCheckPasswordEmpty: api.inputCheckPasswordEmpty,
    inputCheckPasswordSRP: api.inputCheckPasswordSRP,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.inputCheckPasswordEmpty.constructor_id => return .{ .inputCheckPasswordEmpty = try api.inputCheckPasswordEmpty.deserialize(allocator, r) },
            api.inputCheckPasswordSRP.constructor_id => return .{ .inputCheckPasswordSRP = try api.inputCheckPasswordSRP.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SecureRequiredType = union(enum) {
    secureRequiredType: api.secureRequiredType,
    secureRequiredTypeOneOf: api.secureRequiredTypeOneOf,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.secureRequiredType.constructor_id => return .{ .secureRequiredType = try api.secureRequiredType.deserialize(allocator, r) },
            api.secureRequiredTypeOneOf.constructor_id => return .{ .secureRequiredTypeOneOf = try api.secureRequiredTypeOneOf.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

