//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const eligibleToJoin = struct {
    pub const constructor_id: u32 = 0xdc8b44cf;
    terms_url: []const u8,
    monthly_sent_sms: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.terms_url);
        try w.writeInt(self.monthly_sent_sms);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.terms_url = try r.readString();
        self.monthly_sent_sms = try r.readInt();
        _ = allocator;
        return self;
    }
};

pub const status = struct {
    pub const constructor_id: u32 = 0x2aee9191;
    allow_international: bool = false,
    recent_sent: i32,
    recent_since: i32,
    recent_remains: i32,
    total_sent: i32,
    total_since: i32,
    last_gift_slug: ?[]const u8 = null,
    terms_url: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        var flags: u32 = 0;
        if (self.allow_international) flags |= 1 << 0;
        if (self.last_gift_slug != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeInt(self.recent_sent);
        try w.writeInt(self.recent_since);
        try w.writeInt(self.recent_remains);
        try w.writeInt(self.total_sent);
        try w.writeInt(self.total_since);
        if (self.last_gift_slug) |v| {
            try w.writeString(v);
        }
        try w.writeString(self.terms_url);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        const flags = try r.readUInt();
        self.allow_international = (flags >> 0) & 1 != 0;
        self.recent_sent = try r.readInt();
        self.recent_since = try r.readInt();
        self.recent_remains = try r.readInt();
        self.total_sent = try r.readInt();
        self.total_since = try r.readInt();
        if ((flags >> 1) & 1 != 0) {
            self.last_gift_slug = try r.readString();
        } else {
            self.last_gift_slug = null;
        }
        self.terms_url = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const smsJob = struct {
    pub const constructor_id: u32 = 0xe6a1eeb8;
    job_id: []const u8,
    phone_number: []const u8,
    text: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeString(self.job_id);
        try w.writeString(self.phone_number);
        try w.writeString(self.text);
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        var self: @This() = undefined;
        self.job_id = try r.readString();
        self.phone_number = try r.readString();
        self.text = try r.readString();
        _ = allocator;
        return self;
    }
};

pub const EligibilityToJoin = union(enum) {
    eligibleToJoin: api.smsjobs.eligibleToJoin,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.smsjobs.eligibleToJoin.constructor_id => return .{ .eligibleToJoin = try api.smsjobs.eligibleToJoin.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const Status = union(enum) {
    status: api.smsjobs.status,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.smsjobs.status.constructor_id => return .{ .status = try api.smsjobs.status.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

pub const SmsJob = union(enum) {
    smsJob: api.smsJob,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        switch (self.*) {
            inline else => |v| {
                try w.writeConstructorId(@TypeOf(v).constructor_id);
                try v.serialize(w);
            },
        }
    }

    pub fn deserialize(allocator: std.mem.Allocator, r: *Reader) TlError!@This() {
        const id = try r.readConstructorId();
        switch (id) {
            api.smsJob.constructor_id => return .{ .smsJob = try api.smsJob.deserialize(allocator, r) },
            else => return error.InvalidValue,
        }
    }
};

