//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const registerDevice = struct {
    pub const constructor_id: u32 = 0xec86017a;
    pub const Result = bool;
    no_muted: bool = false,
    token_type: i32,
    token: []const u8,
    app_sandbox: bool,
    secret: []const u8,
    other_uids: []i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.no_muted) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeInt(self.token_type);
        try w.writeString(self.token);
        try w.writeBool(self.app_sandbox);
        try w.writeBytes(self.secret);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.other_uids.len);
        for (self.other_uids) |elem_2606| {
            try w.writeLong(elem_2606);
        }
    }
};

pub const unregisterDevice = struct {
    pub const constructor_id: u32 = 0x6a0d3206;
    pub const Result = bool;
    token_type: i32,
    token: []const u8,
    other_uids: []i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeInt(self.token_type);
        try w.writeString(self.token);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.other_uids.len);
        for (self.other_uids) |elem_2607| {
            try w.writeLong(elem_2607);
        }
    }
};

pub const updateNotifySettings = struct {
    pub const constructor_id: u32 = 0x84be5b93;
    pub const Result = bool;
    peer: api.InputNotifyPeer,
    settings: api.InputPeerNotifySettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.peer.serialize(w);
        try self.settings.serialize(w);
    }
};

pub const getNotifySettings = struct {
    pub const constructor_id: u32 = 0x12b3ad31;
    pub const Result = api.PeerNotifySettings;
    peer: api.InputNotifyPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.peer.serialize(w);
    }
};

pub const resetNotifySettings = struct {
    pub const constructor_id: u32 = 0xdb7e1747;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const updateProfile = struct {
    pub const constructor_id: u32 = 0x78515775;
    pub const Result = api.User;
    first_name: ?[]const u8 = null,
    last_name: ?[]const u8 = null,
    about: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.first_name != null) flags |= 1 << 0;
        if (self.last_name != null) flags |= 1 << 1;
        if (self.about != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        if (self.first_name) |v| {
            try w.writeString(v);
        }
        if (self.last_name) |v| {
            try w.writeString(v);
        }
        if (self.about) |v| {
            try w.writeString(v);
        }
    }
};

pub const updateStatus = struct {
    pub const constructor_id: u32 = 0x6628562c;
    pub const Result = bool;
    offline: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeBool(self.offline);
    }
};

pub const getWallPapers = struct {
    pub const constructor_id: u32 = 0x07967d36;
    pub const Result = api.account.WallPapers;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const reportPeer = struct {
    pub const constructor_id: u32 = 0xc5ba3d86;
    pub const Result = bool;
    peer: *api.InputPeer,
    reason: api.ReportReason,
    message: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.peer.serialize(w);
        try self.reason.serialize(w);
        try w.writeString(self.message);
    }
};

pub const checkUsername = struct {
    pub const constructor_id: u32 = 0x2714d86c;
    pub const Result = bool;
    username: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.username);
    }
};

pub const updateUsername = struct {
    pub const constructor_id: u32 = 0x3e0bdd7c;
    pub const Result = api.User;
    username: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.username);
    }
};

pub const getPrivacy = struct {
    pub const constructor_id: u32 = 0xdadbc950;
    pub const Result = api.account.PrivacyRules;
    key: api.InputPrivacyKey,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.key.serialize(w);
    }
};

pub const setPrivacy = struct {
    pub const constructor_id: u32 = 0xc9f81ce8;
    pub const Result = api.account.PrivacyRules;
    key: api.InputPrivacyKey,
    rules: []api.InputPrivacyRule,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.key.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.rules.len);
        for (self.rules) |elem_2608| {
            try elem_2608.serialize(w);
        }
    }
};

pub const deleteAccount = struct {
    pub const constructor_id: u32 = 0xa2c0cf74;
    pub const Result = bool;
    reason: []const u8,
    password: ?api.InputCheckPasswordSRP = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.password != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeString(self.reason);
        if (self.password) |v| {
            try v.serialize(w);
        }
    }
};

pub const getAccountTTL = struct {
    pub const constructor_id: u32 = 0x08fc711d;
    pub const Result = api.AccountDaysTTL;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const setAccountTTL = struct {
    pub const constructor_id: u32 = 0x2442485e;
    pub const Result = bool;
    ttl: api.AccountDaysTTL,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.ttl.serialize(w);
    }
};

pub const sendChangePhoneCode = struct {
    pub const constructor_id: u32 = 0x82574ae5;
    pub const Result = api.auth.SentCode;
    phone_number: []const u8,
    settings: api.CodeSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.phone_number);
        try self.settings.serialize(w);
    }
};

pub const changePhone = struct {
    pub const constructor_id: u32 = 0x70c32edb;
    pub const Result = api.User;
    phone_number: []const u8,
    phone_code_hash: []const u8,
    phone_code: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.phone_number);
        try w.writeString(self.phone_code_hash);
        try w.writeString(self.phone_code);
    }
};

pub const updateDeviceLocked = struct {
    pub const constructor_id: u32 = 0x38df3532;
    pub const Result = bool;
    period: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeInt(self.period);
    }
};

pub const getAuthorizations = struct {
    pub const constructor_id: u32 = 0xe320c158;
    pub const Result = api.account.Authorizations;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const resetAuthorization = struct {
    pub const constructor_id: u32 = 0xdf77f3bc;
    pub const Result = bool;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getPassword = struct {
    pub const constructor_id: u32 = 0x548a30f5;
    pub const Result = api.account.Password;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getPasswordSettings = struct {
    pub const constructor_id: u32 = 0x9cd4eaf9;
    pub const Result = api.account.PasswordSettings;
    password: api.InputCheckPasswordSRP,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.password.serialize(w);
    }
};

pub const updatePasswordSettings = struct {
    pub const constructor_id: u32 = 0xa59b102f;
    pub const Result = bool;
    password: api.InputCheckPasswordSRP,
    new_settings: api.account.PasswordInputSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.password.serialize(w);
        try self.new_settings.serialize(w);
    }
};

pub const sendConfirmPhoneCode = struct {
    pub const constructor_id: u32 = 0x1b3faa88;
    pub const Result = api.auth.SentCode;
    hash: []const u8,
    settings: api.CodeSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.hash);
        try self.settings.serialize(w);
    }
};

pub const confirmPhone = struct {
    pub const constructor_id: u32 = 0x5f2178c3;
    pub const Result = bool;
    phone_code_hash: []const u8,
    phone_code: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.phone_code_hash);
        try w.writeString(self.phone_code);
    }
};

pub const getTmpPassword = struct {
    pub const constructor_id: u32 = 0x449e0b51;
    pub const Result = api.account.TmpPassword;
    password: api.InputCheckPasswordSRP,
    period: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.password.serialize(w);
        try w.writeInt(self.period);
    }
};

pub const getWebAuthorizations = struct {
    pub const constructor_id: u32 = 0x182e6d6f;
    pub const Result = api.account.WebAuthorizations;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const resetWebAuthorization = struct {
    pub const constructor_id: u32 = 0x2d01b9ef;
    pub const Result = bool;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const resetWebAuthorizations = struct {
    pub const constructor_id: u32 = 0x682d2594;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getAllSecureValues = struct {
    pub const constructor_id: u32 = 0xb288bc7d;
    pub const Result = []api.SecureValue;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getSecureValue = struct {
    pub const constructor_id: u32 = 0x73665bc2;
    pub const Result = []api.SecureValue;
    types: []api.SecureValueType,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.types.len);
        for (self.types) |elem_2609| {
            try elem_2609.serialize(w);
        }
    }
};

pub const saveSecureValue = struct {
    pub const constructor_id: u32 = 0x899fe31d;
    pub const Result = api.SecureValue;
    value: api.InputSecureValue,
    secure_secret_id: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.value.serialize(w);
        try w.writeLong(self.secure_secret_id);
    }
};

pub const deleteSecureValue = struct {
    pub const constructor_id: u32 = 0xb880bc4b;
    pub const Result = bool;
    types: []api.SecureValueType,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.types.len);
        for (self.types) |elem_2610| {
            try elem_2610.serialize(w);
        }
    }
};

pub const getAuthorizationForm = struct {
    pub const constructor_id: u32 = 0xa929597a;
    pub const Result = api.account.AuthorizationForm;
    bot_id: i64,
    scope: []const u8,
    public_key: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.bot_id);
        try w.writeString(self.scope);
        try w.writeString(self.public_key);
    }
};

pub const acceptAuthorization = struct {
    pub const constructor_id: u32 = 0xf3ed4c73;
    pub const Result = bool;
    bot_id: i64,
    scope: []const u8,
    public_key: []const u8,
    value_hashes: []api.SecureValueHash,
    credentials: api.SecureCredentialsEncrypted,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.bot_id);
        try w.writeString(self.scope);
        try w.writeString(self.public_key);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.value_hashes.len);
        for (self.value_hashes) |elem_2611| {
            try elem_2611.serialize(w);
        }
        try self.credentials.serialize(w);
    }
};

pub const sendVerifyPhoneCode = struct {
    pub const constructor_id: u32 = 0xa5a356f9;
    pub const Result = api.auth.SentCode;
    phone_number: []const u8,
    settings: api.CodeSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.phone_number);
        try self.settings.serialize(w);
    }
};

pub const verifyPhone = struct {
    pub const constructor_id: u32 = 0x4dd3a7f6;
    pub const Result = bool;
    phone_number: []const u8,
    phone_code_hash: []const u8,
    phone_code: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.phone_number);
        try w.writeString(self.phone_code_hash);
        try w.writeString(self.phone_code);
    }
};

pub const sendVerifyEmailCode = struct {
    pub const constructor_id: u32 = 0x98e037bb;
    pub const Result = api.account.SentEmailCode;
    purpose: api.EmailVerifyPurpose,
    email: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.purpose.serialize(w);
        try w.writeString(self.email);
    }
};

pub const verifyEmail = struct {
    pub const constructor_id: u32 = 0x032da4cf;
    pub const Result = api.account.EmailVerified;
    purpose: api.EmailVerifyPurpose,
    verification: api.EmailVerification,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.purpose.serialize(w);
        try self.verification.serialize(w);
    }
};

pub const initTakeoutSession = struct {
    pub const constructor_id: u32 = 0x8ef3eab0;
    pub const Result = api.account.Takeout;
    contacts: bool = false,
    message_users: bool = false,
    message_chats: bool = false,
    message_megagroups: bool = false,
    message_channels: bool = false,
    files: bool = false,
    file_max_size: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.contacts) flags |= 1 << 0;
        if (self.message_users) flags |= 1 << 1;
        if (self.message_chats) flags |= 1 << 2;
        if (self.message_megagroups) flags |= 1 << 3;
        if (self.message_channels) flags |= 1 << 4;
        if (self.files) flags |= 1 << 5;
        if (self.file_max_size != null) flags |= 1 << 5;
        try w.writeUInt(flags);
        if (self.file_max_size) |v| {
            try w.writeLong(v);
        }
    }
};

pub const finishTakeoutSession = struct {
    pub const constructor_id: u32 = 0x1d2652ee;
    pub const Result = bool;
    success: bool = false,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.success) flags |= 1 << 0;
        try w.writeUInt(flags);
    }
};

pub const confirmPasswordEmail = struct {
    pub const constructor_id: u32 = 0x8fdf1920;
    pub const Result = bool;
    code: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.code);
    }
};

pub const resendPasswordEmail = struct {
    pub const constructor_id: u32 = 0x7a7f2a15;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const cancelPasswordEmail = struct {
    pub const constructor_id: u32 = 0xc1cbd5b6;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getContactSignUpNotification = struct {
    pub const constructor_id: u32 = 0x9f07c728;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const setContactSignUpNotification = struct {
    pub const constructor_id: u32 = 0xcff43f61;
    pub const Result = bool;
    silent: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeBool(self.silent);
    }
};

pub const getNotifyExceptions = struct {
    pub const constructor_id: u32 = 0x53577479;
    pub const Result = api.Updates;
    compare_sound: bool = false,
    compare_stories: bool = false,
    peer: ?api.InputNotifyPeer = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.compare_sound) flags |= 1 << 1;
        if (self.compare_stories) flags |= 1 << 2;
        if (self.peer != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.peer) |v| {
            try v.serialize(w);
        }
    }
};

pub const getWallPaper = struct {
    pub const constructor_id: u32 = 0xfc8ddbea;
    pub const Result = api.WallPaper;
    wallpaper: api.InputWallPaper,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.wallpaper.serialize(w);
    }
};

pub const uploadWallPaper = struct {
    pub const constructor_id: u32 = 0xe39a8f03;
    pub const Result = api.WallPaper;
    for_chat: bool = false,
    file: api.InputFile,
    mime_type: []const u8,
    settings: api.WallPaperSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.for_chat) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.file.serialize(w);
        try w.writeString(self.mime_type);
        try self.settings.serialize(w);
    }
};

pub const saveWallPaper = struct {
    pub const constructor_id: u32 = 0x6c5a5b37;
    pub const Result = bool;
    wallpaper: api.InputWallPaper,
    unsave: bool,
    settings: api.WallPaperSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.wallpaper.serialize(w);
        try w.writeBool(self.unsave);
        try self.settings.serialize(w);
    }
};

pub const installWallPaper = struct {
    pub const constructor_id: u32 = 0xfeed5769;
    pub const Result = bool;
    wallpaper: api.InputWallPaper,
    settings: api.WallPaperSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.wallpaper.serialize(w);
        try self.settings.serialize(w);
    }
};

pub const resetWallPapers = struct {
    pub const constructor_id: u32 = 0xbb3b9804;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getAutoDownloadSettings = struct {
    pub const constructor_id: u32 = 0x56da0b3f;
    pub const Result = api.account.AutoDownloadSettings_;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const saveAutoDownloadSettings = struct {
    pub const constructor_id: u32 = 0x76f36233;
    pub const Result = bool;
    low: bool = false,
    high: bool = false,
    settings: api.AutoDownloadSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.low) flags |= 1 << 0;
        if (self.high) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.settings.serialize(w);
    }
};

pub const uploadTheme = struct {
    pub const constructor_id: u32 = 0x1c3db333;
    pub const Result = api.Document;
    file: api.InputFile,
    thumb: ?api.InputFile = null,
    file_name: []const u8,
    mime_type: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.thumb != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.file.serialize(w);
        if (self.thumb) |v| {
            try v.serialize(w);
        }
        try w.writeString(self.file_name);
        try w.writeString(self.mime_type);
    }
};

pub const createTheme = struct {
    pub const constructor_id: u32 = 0x652e4400;
    pub const Result = api.Theme;
    slug: []const u8,
    title: []const u8,
    document: ?api.InputDocument = null,
    settings: ?[]api.InputThemeSettings = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.document != null) flags |= 1 << 2;
        if (self.settings != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        try w.writeString(self.slug);
        try w.writeString(self.title);
        if (self.document) |v| {
            try v.serialize(w);
        }
        if (self.settings) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2612| {
                try elem_2612.serialize(w);
            }
        }
    }
};

pub const updateTheme = struct {
    pub const constructor_id: u32 = 0x2bf40ccc;
    pub const Result = api.Theme;
    format: []const u8,
    theme: api.InputTheme,
    slug: ?[]const u8 = null,
    title: ?[]const u8 = null,
    document: ?api.InputDocument = null,
    settings: ?[]api.InputThemeSettings = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.slug != null) flags |= 1 << 0;
        if (self.title != null) flags |= 1 << 1;
        if (self.document != null) flags |= 1 << 2;
        if (self.settings != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        try w.writeString(self.format);
        try self.theme.serialize(w);
        if (self.slug) |v| {
            try w.writeString(v);
        }
        if (self.title) |v| {
            try w.writeString(v);
        }
        if (self.document) |v| {
            try v.serialize(w);
        }
        if (self.settings) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2613| {
                try elem_2613.serialize(w);
            }
        }
    }
};

pub const saveTheme = struct {
    pub const constructor_id: u32 = 0xf257106c;
    pub const Result = bool;
    theme: api.InputTheme,
    unsave: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.theme.serialize(w);
        try w.writeBool(self.unsave);
    }
};

pub const installTheme = struct {
    pub const constructor_id: u32 = 0xc727bb3b;
    pub const Result = bool;
    dark: bool = false,
    theme: ?api.InputTheme = null,
    format: ?[]const u8 = null,
    base_theme: ?api.BaseTheme = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.dark) flags |= 1 << 0;
        if (self.theme != null) flags |= 1 << 1;
        if (self.format != null) flags |= 1 << 2;
        if (self.base_theme != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        if (self.theme) |v| {
            try v.serialize(w);
        }
        if (self.format) |v| {
            try w.writeString(v);
        }
        if (self.base_theme) |v| {
            try v.serialize(w);
        }
    }
};

pub const getTheme = struct {
    pub const constructor_id: u32 = 0x3a5869ec;
    pub const Result = api.Theme;
    format: []const u8,
    theme: api.InputTheme,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.format);
        try self.theme.serialize(w);
    }
};

pub const getThemes = struct {
    pub const constructor_id: u32 = 0x7206e458;
    pub const Result = api.account.Themes;
    format: []const u8,
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.format);
        try w.writeLong(self.hash);
    }
};

pub const setContentSettings = struct {
    pub const constructor_id: u32 = 0xb574b16b;
    pub const Result = bool;
    sensitive_enabled: bool = false,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.sensitive_enabled) flags |= 1 << 0;
        try w.writeUInt(flags);
    }
};

pub const getContentSettings = struct {
    pub const constructor_id: u32 = 0x8b9b4dae;
    pub const Result = api.account.ContentSettings;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getMultiWallPapers = struct {
    pub const constructor_id: u32 = 0x65ad71dc;
    pub const Result = []api.WallPaper;
    wallpapers: []api.InputWallPaper,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.wallpapers.len);
        for (self.wallpapers) |elem_2614| {
            try elem_2614.serialize(w);
        }
    }
};

pub const getGlobalPrivacySettings = struct {
    pub const constructor_id: u32 = 0xeb2b4cf6;
    pub const Result = api.GlobalPrivacySettings;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const setGlobalPrivacySettings = struct {
    pub const constructor_id: u32 = 0x1edaaac2;
    pub const Result = api.GlobalPrivacySettings;
    settings: api.GlobalPrivacySettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.settings.serialize(w);
    }
};

pub const reportProfilePhoto = struct {
    pub const constructor_id: u32 = 0xfa8cc6f5;
    pub const Result = bool;
    peer: *api.InputPeer,
    photo_id: api.InputPhoto,
    reason: api.ReportReason,
    message: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.peer.serialize(w);
        try self.photo_id.serialize(w);
        try self.reason.serialize(w);
        try w.writeString(self.message);
    }
};

pub const resetPassword = struct {
    pub const constructor_id: u32 = 0x9308ce1b;
    pub const Result = api.account.ResetPasswordResult;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const declinePasswordReset = struct {
    pub const constructor_id: u32 = 0x4c9409f6;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getChatThemes = struct {
    pub const constructor_id: u32 = 0xd638de89;
    pub const Result = api.account.Themes;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const setAuthorizationTTL = struct {
    pub const constructor_id: u32 = 0xbf899aa0;
    pub const Result = bool;
    authorization_ttl_days: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeInt(self.authorization_ttl_days);
    }
};

pub const changeAuthorizationSettings = struct {
    pub const constructor_id: u32 = 0x40f48462;
    pub const Result = bool;
    confirmed: bool = false,
    hash: i64,
    encrypted_requests_disabled: ?bool = null,
    call_requests_disabled: ?bool = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.confirmed) flags |= 1 << 3;
        if (self.encrypted_requests_disabled != null) flags |= 1 << 0;
        if (self.call_requests_disabled != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeLong(self.hash);
        if (self.encrypted_requests_disabled) |v| {
            try w.writeBool(v);
        }
        if (self.call_requests_disabled) |v| {
            try w.writeBool(v);
        }
    }
};

pub const getSavedRingtones = struct {
    pub const constructor_id: u32 = 0xe1902288;
    pub const Result = api.account.SavedRingtones;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const saveRingtone = struct {
    pub const constructor_id: u32 = 0x3dea5b03;
    pub const Result = api.account.SavedRingtone;
    id: api.InputDocument,
    unsave: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
        try w.writeBool(self.unsave);
    }
};

pub const uploadRingtone = struct {
    pub const constructor_id: u32 = 0x831a83a2;
    pub const Result = api.Document;
    file: api.InputFile,
    file_name: []const u8,
    mime_type: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.file.serialize(w);
        try w.writeString(self.file_name);
        try w.writeString(self.mime_type);
    }
};

pub const updateEmojiStatus = struct {
    pub const constructor_id: u32 = 0xfbd3de6b;
    pub const Result = bool;
    emoji_status: api.EmojiStatus,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.emoji_status.serialize(w);
    }
};

pub const getDefaultEmojiStatuses = struct {
    pub const constructor_id: u32 = 0xd6753386;
    pub const Result = api.account.EmojiStatuses;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getRecentEmojiStatuses = struct {
    pub const constructor_id: u32 = 0x0f578105;
    pub const Result = api.account.EmojiStatuses;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const clearRecentEmojiStatuses = struct {
    pub const constructor_id: u32 = 0x18201aae;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const reorderUsernames = struct {
    pub const constructor_id: u32 = 0xef500eab;
    pub const Result = bool;
    order: [][]const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.order.len);
        for (self.order) |elem_2615| {
            try w.writeString(elem_2615);
        }
    }
};

pub const toggleUsername = struct {
    pub const constructor_id: u32 = 0x58d6b376;
    pub const Result = bool;
    username: []const u8,
    active: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.username);
        try w.writeBool(self.active);
    }
};

pub const getDefaultProfilePhotoEmojis = struct {
    pub const constructor_id: u32 = 0xe2750328;
    pub const Result = api.EmojiList;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getDefaultGroupPhotoEmojis = struct {
    pub const constructor_id: u32 = 0x915860ae;
    pub const Result = api.EmojiList;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getAutoSaveSettings = struct {
    pub const constructor_id: u32 = 0xadcbbcda;
    pub const Result = api.account.AutoSaveSettings_;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const saveAutoSaveSettings = struct {
    pub const constructor_id: u32 = 0xd69b8361;
    pub const Result = bool;
    users: bool = false,
    chats: bool = false,
    broadcasts: bool = false,
    peer: ?*api.InputPeer = null,
    settings: api.AutoSaveSettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.users) flags |= 1 << 0;
        if (self.chats) flags |= 1 << 1;
        if (self.broadcasts) flags |= 1 << 2;
        if (self.peer != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        if (self.peer) |v| {
            try v.serialize(w);
        }
        try self.settings.serialize(w);
    }
};

pub const deleteAutoSaveExceptions = struct {
    pub const constructor_id: u32 = 0x53bc0020;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const invalidateSignInCodes = struct {
    pub const constructor_id: u32 = 0xca8ae8ba;
    pub const Result = bool;
    codes: [][]const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.codes.len);
        for (self.codes) |elem_2616| {
            try w.writeString(elem_2616);
        }
    }
};

pub const updateColor = struct {
    pub const constructor_id: u32 = 0x684d214e;
    pub const Result = bool;
    for_profile: bool = false,
    color: ?api.PeerColor = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.for_profile) flags |= 1 << 1;
        if (self.color != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        if (self.color) |v| {
            try v.serialize(w);
        }
    }
};

pub const getDefaultBackgroundEmojis = struct {
    pub const constructor_id: u32 = 0xa60ab9ce;
    pub const Result = api.EmojiList;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getChannelDefaultEmojiStatuses = struct {
    pub const constructor_id: u32 = 0x7727a7d5;
    pub const Result = api.account.EmojiStatuses;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getChannelRestrictedStatusEmojis = struct {
    pub const constructor_id: u32 = 0x35a9e0d5;
    pub const Result = api.EmojiList;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const updateBusinessWorkHours = struct {
    pub const constructor_id: u32 = 0x4b00e066;
    pub const Result = bool;
    business_work_hours: ?api.BusinessWorkHours = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.business_work_hours != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.business_work_hours) |v| {
            try v.serialize(w);
        }
    }
};

pub const updateBusinessLocation = struct {
    pub const constructor_id: u32 = 0x9e6b131a;
    pub const Result = bool;
    geo_point: ?api.InputGeoPoint = null,
    address: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.geo_point != null) flags |= 1 << 1;
        if (self.address != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.geo_point) |v| {
            try v.serialize(w);
        }
        if (self.address) |v| {
            try w.writeString(v);
        }
    }
};

pub const updateBusinessGreetingMessage = struct {
    pub const constructor_id: u32 = 0x66cdafc4;
    pub const Result = bool;
    message: ?api.InputBusinessGreetingMessage = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.message != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.message) |v| {
            try v.serialize(w);
        }
    }
};

pub const updateBusinessAwayMessage = struct {
    pub const constructor_id: u32 = 0xa26a7fa5;
    pub const Result = bool;
    message: ?api.InputBusinessAwayMessage = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.message != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.message) |v| {
            try v.serialize(w);
        }
    }
};

pub const updateConnectedBot = struct {
    pub const constructor_id: u32 = 0x66a08c7e;
    pub const Result = api.Updates;
    deleted: bool = false,
    rights: ?api.BusinessBotRights = null,
    bot: api.InputUser,
    recipients: api.InputBusinessBotRecipients,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.deleted) flags |= 1 << 1;
        if (self.rights != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.rights) |v| {
            try v.serialize(w);
        }
        try self.bot.serialize(w);
        try self.recipients.serialize(w);
    }
};

pub const getConnectedBots = struct {
    pub const constructor_id: u32 = 0x4ea4c80f;
    pub const Result = api.account.ConnectedBots;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getBotBusinessConnection = struct {
    pub const constructor_id: u32 = 0x76a86270;
    pub const Result = api.Updates;
    connection_id: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.connection_id);
    }
};

pub const updateBusinessIntro = struct {
    pub const constructor_id: u32 = 0xa614d034;
    pub const Result = bool;
    intro: ?api.InputBusinessIntro = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.intro != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.intro) |v| {
            try v.serialize(w);
        }
    }
};

pub const toggleConnectedBotPaused = struct {
    pub const constructor_id: u32 = 0x646e1097;
    pub const Result = bool;
    peer: *api.InputPeer,
    paused: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.peer.serialize(w);
        try w.writeBool(self.paused);
    }
};

pub const disablePeerConnectedBot = struct {
    pub const constructor_id: u32 = 0x5e437ed9;
    pub const Result = bool;
    peer: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.peer.serialize(w);
    }
};

pub const updateBirthday = struct {
    pub const constructor_id: u32 = 0xcc6e0c11;
    pub const Result = bool;
    birthday: ?api.Birthday = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.birthday != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.birthday) |v| {
            try v.serialize(w);
        }
    }
};

pub const createBusinessChatLink = struct {
    pub const constructor_id: u32 = 0x8851e68e;
    pub const Result = api.BusinessChatLink;
    link: api.InputBusinessChatLink,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.link.serialize(w);
    }
};

pub const editBusinessChatLink = struct {
    pub const constructor_id: u32 = 0x8c3410af;
    pub const Result = api.BusinessChatLink;
    slug: []const u8,
    link: api.InputBusinessChatLink,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.slug);
        try self.link.serialize(w);
    }
};

pub const deleteBusinessChatLink = struct {
    pub const constructor_id: u32 = 0x60073674;
    pub const Result = bool;
    slug: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.slug);
    }
};

pub const getBusinessChatLinks = struct {
    pub const constructor_id: u32 = 0x6f70dde1;
    pub const Result = api.account.BusinessChatLinks;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const resolveBusinessChatLink = struct {
    pub const constructor_id: u32 = 0x5492e5ee;
    pub const Result = api.account.ResolvedBusinessChatLinks;
    slug: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.slug);
    }
};

pub const updatePersonalChannel = struct {
    pub const constructor_id: u32 = 0xd94305e0;
    pub const Result = bool;
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
    }
};

pub const toggleSponsoredMessages = struct {
    pub const constructor_id: u32 = 0xb9d9a38d;
    pub const Result = bool;
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeBool(self.enabled);
    }
};

pub const getReactionsNotifySettings = struct {
    pub const constructor_id: u32 = 0x06dd654c;
    pub const Result = api.ReactionsNotifySettings;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const setReactionsNotifySettings = struct {
    pub const constructor_id: u32 = 0x316ce548;
    pub const Result = api.ReactionsNotifySettings;
    settings: api.ReactionsNotifySettings,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.settings.serialize(w);
    }
};

pub const getCollectibleEmojiStatuses = struct {
    pub const constructor_id: u32 = 0x2e7b4543;
    pub const Result = api.account.EmojiStatuses;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getPaidMessagesRevenue = struct {
    pub const constructor_id: u32 = 0x19ba4a67;
    pub const Result = api.account.PaidMessagesRevenue;
    parent_peer: ?*api.InputPeer = null,
    user_id: api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.parent_peer != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.parent_peer) |v| {
            try v.serialize(w);
        }
        try self.user_id.serialize(w);
    }
};

pub const toggleNoPaidMessagesException = struct {
    pub const constructor_id: u32 = 0xfe2eda76;
    pub const Result = bool;
    refund_charged: bool = false,
    require_payment: bool = false,
    parent_peer: ?*api.InputPeer = null,
    user_id: api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.refund_charged) flags |= 1 << 0;
        if (self.require_payment) flags |= 1 << 2;
        if (self.parent_peer != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        if (self.parent_peer) |v| {
            try v.serialize(w);
        }
        try self.user_id.serialize(w);
    }
};

pub const setMainProfileTab = struct {
    pub const constructor_id: u32 = 0x5dee78b0;
    pub const Result = bool;
    tab: api.ProfileTab,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.tab.serialize(w);
    }
};

pub const saveMusic = struct {
    pub const constructor_id: u32 = 0xb26732a9;
    pub const Result = bool;
    unsave: bool = false,
    id: api.InputDocument,
    after_id: ?api.InputDocument = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.unsave) flags |= 1 << 0;
        if (self.after_id != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.id.serialize(w);
        if (self.after_id) |v| {
            try v.serialize(w);
        }
    }
};

pub const getSavedMusicIds = struct {
    pub const constructor_id: u32 = 0xe09d5faf;
    pub const Result = api.account.SavedMusicIds;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getUniqueGiftChatThemes = struct {
    pub const constructor_id: u32 = 0xe42ce9c9;
    pub const Result = api.account.ChatThemes;
    offset: []const u8,
    limit: i32,
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.offset);
        try w.writeInt(self.limit);
        try w.writeLong(self.hash);
    }
};

pub const initPasskeyRegistration = struct {
    pub const constructor_id: u32 = 0x429547e8;
    pub const Result = api.account.PasskeyRegistrationOptions;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const registerPasskey = struct {
    pub const constructor_id: u32 = 0x55b41fd6;
    pub const Result = api.Passkey;
    credential: api.InputPasskeyCredential,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.credential.serialize(w);
    }
};

pub const getPasskeys = struct {
    pub const constructor_id: u32 = 0xea1f0c52;
    pub const Result = api.account.Passkeys;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const deletePasskey = struct {
    pub const constructor_id: u32 = 0xf5b5563f;
    pub const Result = bool;
    id: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.id);
    }
};

pub const confirmBotConnection = struct {
    pub const constructor_id: u32 = 0x67ed1f68;
    pub const Result = bool;
    bot_id: api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.bot_id.serialize(w);
    }
};

pub const getWebBrowserSettings = struct {
    pub const constructor_id: u32 = 0x56655768;
    pub const Result = api.account.WebBrowserSettings;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const updateWebBrowserSettings = struct {
    pub const constructor_id: u32 = 0x9adf82fe;
    pub const Result = api.account.WebBrowserSettings;
    open_external_browser: bool = false,
    display_close_button: bool = false,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.open_external_browser) flags |= 1 << 0;
        if (self.display_close_button) flags |= 1 << 1;
        try w.writeUInt(flags);
    }
};

pub const toggleWebBrowserSettingsException = struct {
    pub const constructor_id: u32 = 0x60ed4229;
    pub const Result = api.Updates;
    delete: bool = false,
    open_external_browser: ?bool = null,
    url: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.delete) flags |= 1 << 1;
        if (self.open_external_browser != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.open_external_browser) |v| {
            try w.writeBool(v);
        }
        try w.writeString(self.url);
    }
};

pub const deleteWebBrowserSettingsExceptions = struct {
    pub const constructor_id: u32 = 0x86a0765d;
    pub const Result = api.account.WebBrowserSettings;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

