//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const readHistory = struct {
    pub const constructor_id: u32 = 0xcc104937;
    pub const Result = bool;
    channel: api.InputChannel,
    max_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeInt(self.max_id);
    }
};

pub const deleteMessages = struct {
    pub const constructor_id: u32 = 0x84c1fd4e;
    pub const Result = api.messages.AffectedMessages;
    channel: api.InputChannel,
    id: []i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2686| {
            try w.writeInt(elem_2686);
        }
    }
};

pub const reportSpam = struct {
    pub const constructor_id: u32 = 0xf44a8315;
    pub const Result = bool;
    channel: api.InputChannel,
    participant: *api.InputPeer,
    id: []i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.participant.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2687| {
            try w.writeInt(elem_2687);
        }
    }
};

pub const getMessages = struct {
    pub const constructor_id: u32 = 0xad8c9a23;
    pub const Result = api.messages.Messages;
    channel: api.InputChannel,
    id: []api.InputMessage,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2688| {
            try elem_2688.serialize(w);
        }
    }
};

pub const getParticipants = struct {
    pub const constructor_id: u32 = 0x77ced9d0;
    pub const Result = api.channels.ChannelParticipants;
    channel: api.InputChannel,
    filter: api.ChannelParticipantsFilter,
    offset: i32,
    limit: i32,
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.filter.serialize(w);
        try w.writeInt(self.offset);
        try w.writeInt(self.limit);
        try w.writeLong(self.hash);
    }
};

pub const getParticipant = struct {
    pub const constructor_id: u32 = 0xa0ab6cc6;
    pub const Result = api.channels.ChannelParticipant_;
    channel: api.InputChannel,
    participant: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.participant.serialize(w);
    }
};

pub const getChannels = struct {
    pub const constructor_id: u32 = 0x0a7f6bbb;
    pub const Result = api.messages.Chats;
    id: []api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2689| {
            try elem_2689.serialize(w);
        }
    }
};

pub const getFullChannel = struct {
    pub const constructor_id: u32 = 0x08736a09;
    pub const Result = api.messages.ChatFull_;
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
    }
};

pub const createChannel = struct {
    pub const constructor_id: u32 = 0x91006707;
    pub const Result = api.Updates;
    broadcast: bool = false,
    megagroup: bool = false,
    for_import: bool = false,
    forum: bool = false,
    title: []const u8,
    about: []const u8,
    geo_point: ?api.InputGeoPoint = null,
    address: ?[]const u8 = null,
    ttl_period: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.broadcast) flags |= 1 << 0;
        if (self.megagroup) flags |= 1 << 1;
        if (self.for_import) flags |= 1 << 3;
        if (self.forum) flags |= 1 << 5;
        if (self.geo_point != null) flags |= 1 << 2;
        if (self.address != null) flags |= 1 << 2;
        if (self.ttl_period != null) flags |= 1 << 4;
        try w.writeUInt(flags);
        try w.writeString(self.title);
        try w.writeString(self.about);
        if (self.geo_point) |v| {
            try v.serialize(w);
        }
        if (self.address) |v| {
            try w.writeString(v);
        }
        if (self.ttl_period) |v| {
            try w.writeInt(v);
        }
    }
};

pub const editAdmin = struct {
    pub const constructor_id: u32 = 0x9a98ad68;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    user_id: api.InputUser,
    admin_rights: api.ChatAdminRights,
    rank: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.rank != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
        try self.user_id.serialize(w);
        try self.admin_rights.serialize(w);
        if (self.rank) |v| {
            try w.writeString(v);
        }
    }
};

pub const editTitle = struct {
    pub const constructor_id: u32 = 0x566decd0;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    title: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeString(self.title);
    }
};

pub const editPhoto = struct {
    pub const constructor_id: u32 = 0xf12e57c9;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    photo: api.InputChatPhoto,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.photo.serialize(w);
    }
};

pub const checkUsername = struct {
    pub const constructor_id: u32 = 0x10e6bd2c;
    pub const Result = bool;
    channel: api.InputChannel,
    username: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeString(self.username);
    }
};

pub const updateUsername = struct {
    pub const constructor_id: u32 = 0x3514b3de;
    pub const Result = bool;
    channel: api.InputChannel,
    username: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeString(self.username);
    }
};

pub const joinChannel = struct {
    pub const constructor_id: u32 = 0x7f6a1e22;
    pub const Result = api.messages.ChatInviteJoinResult;
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
    }
};

pub const leaveChannel = struct {
    pub const constructor_id: u32 = 0xf836aa95;
    pub const Result = api.Updates;
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
    }
};

pub const inviteToChannel = struct {
    pub const constructor_id: u32 = 0xc9e33d54;
    pub const Result = api.messages.InvitedUsers;
    channel: api.InputChannel,
    users: []api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.users.len);
        for (self.users) |elem_2690| {
            try elem_2690.serialize(w);
        }
    }
};

pub const deleteChannel = struct {
    pub const constructor_id: u32 = 0xc0111fe3;
    pub const Result = api.Updates;
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
    }
};

pub const exportMessageLink = struct {
    pub const constructor_id: u32 = 0xe63fadeb;
    pub const Result = api.ExportedMessageLink;
    grouped: bool = false,
    thread: bool = false,
    channel: api.InputChannel,
    id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.grouped) flags |= 1 << 0;
        if (self.thread) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
        try w.writeInt(self.id);
    }
};

pub const toggleSignatures = struct {
    pub const constructor_id: u32 = 0x418d549c;
    pub const Result = api.Updates;
    signatures_enabled: bool = false,
    profiles_enabled: bool = false,
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.signatures_enabled) flags |= 1 << 0;
        if (self.profiles_enabled) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
    }
};

pub const getAdminedPublicChannels = struct {
    pub const constructor_id: u32 = 0xf8b036af;
    pub const Result = api.messages.Chats;
    by_location: bool = false,
    check_limit: bool = false,
    for_personal: bool = false,
    for_community_peer: bool = false,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.by_location) flags |= 1 << 0;
        if (self.check_limit) flags |= 1 << 1;
        if (self.for_personal) flags |= 1 << 2;
        if (self.for_community_peer) flags |= 1 << 3;
        try w.writeUInt(flags);
    }
};

pub const editBanned = struct {
    pub const constructor_id: u32 = 0x96e6cd81;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    participant: *api.InputPeer,
    banned_rights: api.ChatBannedRights,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.participant.serialize(w);
        try self.banned_rights.serialize(w);
    }
};

pub const getAdminLog = struct {
    pub const constructor_id: u32 = 0x33ddf480;
    pub const Result = api.channels.AdminLogResults;
    channel: api.InputChannel,
    q: []const u8,
    events_filter: ?api.ChannelAdminLogEventsFilter = null,
    admins: ?[]api.InputUser = null,
    max_id: i64,
    min_id: i64,
    limit: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.events_filter != null) flags |= 1 << 0;
        if (self.admins != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
        try w.writeString(self.q);
        if (self.events_filter) |v| {
            try v.serialize(w);
        }
        if (self.admins) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2691| {
                try elem_2691.serialize(w);
            }
        }
        try w.writeLong(self.max_id);
        try w.writeLong(self.min_id);
        try w.writeInt(self.limit);
    }
};

pub const setStickers = struct {
    pub const constructor_id: u32 = 0xea8ca4f9;
    pub const Result = bool;
    channel: api.InputChannel,
    stickerset: api.InputStickerSet,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.stickerset.serialize(w);
    }
};

pub const readMessageContents = struct {
    pub const constructor_id: u32 = 0xeab5dc38;
    pub const Result = bool;
    channel: api.InputChannel,
    id: []i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2692| {
            try w.writeInt(elem_2692);
        }
    }
};

pub const deleteHistory = struct {
    pub const constructor_id: u32 = 0x9baa9647;
    pub const Result = api.Updates;
    for_everyone: bool = false,
    channel: api.InputChannel,
    max_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.for_everyone) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
        try w.writeInt(self.max_id);
    }
};

pub const togglePreHistoryHidden = struct {
    pub const constructor_id: u32 = 0xeabbb94c;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
    }
};

pub const getLeftChannels = struct {
    pub const constructor_id: u32 = 0x8341ecc0;
    pub const Result = api.messages.Chats;
    offset: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeInt(self.offset);
    }
};

pub const getGroupsForDiscussion = struct {
    pub const constructor_id: u32 = 0xf5dad378;
    pub const Result = api.messages.Chats;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const setDiscussionGroup = struct {
    pub const constructor_id: u32 = 0x40582bb2;
    pub const Result = bool;
    broadcast: api.InputChannel,
    group: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.broadcast.serialize(w);
        try self.group.serialize(w);
    }
};

pub const editLocation = struct {
    pub const constructor_id: u32 = 0x58e63f6d;
    pub const Result = bool;
    channel: api.InputChannel,
    geo_point: api.InputGeoPoint,
    address: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.geo_point.serialize(w);
        try w.writeString(self.address);
    }
};

pub const toggleSlowMode = struct {
    pub const constructor_id: u32 = 0xedd49ef0;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    seconds: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeInt(self.seconds);
    }
};

pub const getInactiveChannels = struct {
    pub const constructor_id: u32 = 0x11e831ee;
    pub const Result = api.messages.InactiveChats;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const convertToGigagroup = struct {
    pub const constructor_id: u32 = 0x0b290c69;
    pub const Result = api.Updates;
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
    }
};

pub const getSendAs = struct {
    pub const constructor_id: u32 = 0xe785a43f;
    pub const Result = api.channels.SendAsPeers;
    for_paid_reactions: bool = false,
    for_live_stories: bool = false,
    peer: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.for_paid_reactions) flags |= 1 << 0;
        if (self.for_live_stories) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.peer.serialize(w);
    }
};

pub const deleteParticipantHistory = struct {
    pub const constructor_id: u32 = 0x367544db;
    pub const Result = api.messages.AffectedHistory;
    channel: api.InputChannel,
    participant: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.participant.serialize(w);
    }
};

pub const toggleJoinToSend = struct {
    pub const constructor_id: u32 = 0xe4cb9580;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
    }
};

pub const toggleJoinRequest = struct {
    pub const constructor_id: u32 = 0x0ecc2618;
    pub const Result = api.Updates;
    apply_to_invites: bool = false,
    channel: api.InputChannel,
    enabled: bool,
    guard_bot: ?api.InputUser = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.apply_to_invites) flags |= 1 << 1;
        if (self.guard_bot != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
        if (self.guard_bot) |v| {
            try v.serialize(w);
        }
    }
};

pub const reorderUsernames = struct {
    pub const constructor_id: u32 = 0xb45ced1d;
    pub const Result = bool;
    channel: api.InputChannel,
    order: [][]const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.order.len);
        for (self.order) |elem_2693| {
            try w.writeString(elem_2693);
        }
    }
};

pub const toggleUsername = struct {
    pub const constructor_id: u32 = 0x50f24105;
    pub const Result = bool;
    channel: api.InputChannel,
    username: []const u8,
    active: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeString(self.username);
        try w.writeBool(self.active);
    }
};

pub const deactivateAllUsernames = struct {
    pub const constructor_id: u32 = 0x0a245dd3;
    pub const Result = bool;
    channel: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
    }
};

pub const toggleForum = struct {
    pub const constructor_id: u32 = 0x3ff75734;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    enabled: bool,
    tabs: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
        try w.writeBool(self.tabs);
    }
};

pub const toggleAntiSpam = struct {
    pub const constructor_id: u32 = 0x68f3e4eb;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
    }
};

pub const reportAntiSpamFalsePositive = struct {
    pub const constructor_id: u32 = 0xa850a693;
    pub const Result = bool;
    channel: api.InputChannel,
    msg_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeInt(self.msg_id);
    }
};

pub const toggleParticipantsHidden = struct {
    pub const constructor_id: u32 = 0x6a6e7854;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
    }
};

pub const updateColor = struct {
    pub const constructor_id: u32 = 0xd8aa3671;
    pub const Result = api.Updates;
    for_profile: bool = false,
    channel: api.InputChannel,
    color: ?i32 = null,
    background_emoji_id: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.for_profile) flags |= 1 << 1;
        if (self.color != null) flags |= 1 << 2;
        if (self.background_emoji_id != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
        if (self.color) |v| {
            try w.writeInt(v);
        }
        if (self.background_emoji_id) |v| {
            try w.writeLong(v);
        }
    }
};

pub const toggleViewForumAsMessages = struct {
    pub const constructor_id: u32 = 0x9738bb15;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
    }
};

pub const getChannelRecommendations = struct {
    pub const constructor_id: u32 = 0x25a71742;
    pub const Result = api.messages.Chats;
    channel: ?api.InputChannel = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.channel != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.channel) |v| {
            try v.serialize(w);
        }
    }
};

pub const updateEmojiStatus = struct {
    pub const constructor_id: u32 = 0xf0d3e6a8;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    emoji_status: api.EmojiStatus,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.emoji_status.serialize(w);
    }
};

pub const setBoostsToUnblockRestrictions = struct {
    pub const constructor_id: u32 = 0xad399cee;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    boosts: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeInt(self.boosts);
    }
};

pub const setEmojiStickers = struct {
    pub const constructor_id: u32 = 0x3cd930b7;
    pub const Result = bool;
    channel: api.InputChannel,
    stickerset: api.InputStickerSet,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.stickerset.serialize(w);
    }
};

pub const restrictSponsoredMessages = struct {
    pub const constructor_id: u32 = 0x9ae91519;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    restricted: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.restricted);
    }
};

pub const searchPosts = struct {
    pub const constructor_id: u32 = 0xf2c4f24d;
    pub const Result = api.messages.Messages;
    hashtag: ?[]const u8 = null,
    query: ?[]const u8 = null,
    offset_rate: i32,
    offset_peer: *api.InputPeer,
    offset_id: i32,
    limit: i32,
    allow_paid_stars: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.hashtag != null) flags |= 1 << 0;
        if (self.query != null) flags |= 1 << 1;
        if (self.allow_paid_stars != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        if (self.hashtag) |v| {
            try w.writeString(v);
        }
        if (self.query) |v| {
            try w.writeString(v);
        }
        try w.writeInt(self.offset_rate);
        try self.offset_peer.serialize(w);
        try w.writeInt(self.offset_id);
        try w.writeInt(self.limit);
        if (self.allow_paid_stars) |v| {
            try w.writeLong(v);
        }
    }
};

pub const updatePaidMessagesPrice = struct {
    pub const constructor_id: u32 = 0x4b12327b;
    pub const Result = api.Updates;
    broadcast_messages_allowed: bool = false,
    channel: api.InputChannel,
    send_paid_messages_stars: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.broadcast_messages_allowed) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.channel.serialize(w);
        try w.writeLong(self.send_paid_messages_stars);
    }
};

pub const toggleAutotranslation = struct {
    pub const constructor_id: u32 = 0x167fc0a1;
    pub const Result = api.Updates;
    channel: api.InputChannel,
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeBool(self.enabled);
    }
};

pub const getMessageAuthor = struct {
    pub const constructor_id: u32 = 0xece2a0e6;
    pub const Result = api.User;
    channel: api.InputChannel,
    id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try w.writeInt(self.id);
    }
};

pub const checkSearchPostsFlood = struct {
    pub const constructor_id: u32 = 0x22567115;
    pub const Result = api.SearchPostsFlood;
    query: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.query != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        if (self.query) |v| {
            try w.writeString(v);
        }
    }
};

pub const setMainProfileTab = struct {
    pub const constructor_id: u32 = 0x3583fcb1;
    pub const Result = bool;
    channel: api.InputChannel,
    tab: api.ProfileTab,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.channel.serialize(w);
        try self.tab.serialize(w);
    }
};

