//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const exportChatlistInvite = struct {
    pub const constructor_id: u32 = 0x8472478e;
    pub const Result = api.chatlists.ExportedChatlistInvite_;
    chatlist: api.InputChatlist,
    title: []const u8,
    peers: []*api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
        try w.writeString(self.title);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.peers.len);
        for (self.peers) |elem_2718| {
            try elem_2718.serialize(w);
        }
    }
};

pub const deleteExportedInvite = struct {
    pub const constructor_id: u32 = 0x719c5c5e;
    pub const Result = bool;
    chatlist: api.InputChatlist,
    slug: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
        try w.writeString(self.slug);
    }
};

pub const editExportedInvite = struct {
    pub const constructor_id: u32 = 0x653db63d;
    pub const Result = api.ExportedChatlistInvite;
    chatlist: api.InputChatlist,
    slug: []const u8,
    title: ?[]const u8 = null,
    peers: ?[]*api.InputPeer = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.title != null) flags |= 1 << 1;
        if (self.peers != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        try self.chatlist.serialize(w);
        try w.writeString(self.slug);
        if (self.title) |v| {
            try w.writeString(v);
        }
        if (self.peers) |v| {
            try w.writeUInt(vector_constructor_id);
            try w.writeVectorLength(v.len);
            for (v) |elem_2719| {
                try elem_2719.serialize(w);
            }
        }
    }
};

pub const getExportedInvites = struct {
    pub const constructor_id: u32 = 0xce03da83;
    pub const Result = api.chatlists.ExportedInvites;
    chatlist: api.InputChatlist,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
    }
};

pub const checkChatlistInvite = struct {
    pub const constructor_id: u32 = 0x41c10fff;
    pub const Result = api.chatlists.ChatlistInvite;
    slug: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.slug);
    }
};

pub const joinChatlistInvite = struct {
    pub const constructor_id: u32 = 0xa6b1e39a;
    pub const Result = api.Updates;
    slug: []const u8,
    peers: []*api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.slug);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.peers.len);
        for (self.peers) |elem_2720| {
            try elem_2720.serialize(w);
        }
    }
};

pub const getChatlistUpdates = struct {
    pub const constructor_id: u32 = 0x89419521;
    pub const Result = api.chatlists.ChatlistUpdates;
    chatlist: api.InputChatlist,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
    }
};

pub const joinChatlistUpdates = struct {
    pub const constructor_id: u32 = 0xe089f8f5;
    pub const Result = api.Updates;
    chatlist: api.InputChatlist,
    peers: []*api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.peers.len);
        for (self.peers) |elem_2721| {
            try elem_2721.serialize(w);
        }
    }
};

pub const hideChatlistUpdates = struct {
    pub const constructor_id: u32 = 0x66e486fb;
    pub const Result = bool;
    chatlist: api.InputChatlist,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
    }
};

pub const getLeaveChatlistSuggestions = struct {
    pub const constructor_id: u32 = 0xfdbcd714;
    pub const Result = []api.Peer;
    chatlist: api.InputChatlist,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
    }
};

pub const leaveChatlist = struct {
    pub const constructor_id: u32 = 0x74fae13a;
    pub const Result = api.Updates;
    chatlist: api.InputChatlist,
    peers: []*api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.chatlist.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.peers.len);
        for (self.peers) |elem_2722| {
            try elem_2722.serialize(w);
        }
    }
};

