//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const create = struct {
    pub const constructor_id: u32 = 0xa63859ec;
    pub const Result = api.Updates;
    hidden: bool = false,
    title: []const u8,
    about: ?[]const u8 = null,
    peer: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.hidden) flags |= 1 << 1;
        if (self.about != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeString(self.title);
        if (self.about) |v| {
            try w.writeString(v);
        }
        try self.peer.serialize(w);
    }
};

pub const togglePeerLink = struct {
    pub const constructor_id: u32 = 0x736dcfea;
    pub const Result = bool;
    visible: bool = false,
    hidden: bool = false,
    deleted: bool = false,
    community: api.InputChannel,
    peer: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.visible) flags |= 1 << 0;
        if (self.hidden) flags |= 1 << 1;
        if (self.deleted) flags |= 1 << 2;
        try w.writeUInt(flags);
        try self.community.serialize(w);
        try self.peer.serialize(w);
    }
};

pub const getJoinedCommunities = struct {
    pub const constructor_id: u32 = 0xa663e830;
    pub const Result = api.messages.Chats;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const toggleCommunityCollapsedInDialogs = struct {
    pub const constructor_id: u32 = 0xd766e3ea;
    pub const Result = api.Updates;
    collapsed: bool = false,
    community: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.collapsed) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.community.serialize(w);
    }
};

pub const getPeerLinkRequests = struct {
    pub const constructor_id: u32 = 0x93773344;
    pub const Result = api.communities.PeerLinkRequests;
    community: api.InputChannel,
    offset: []const u8,
    limit: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.community.serialize(w);
        try w.writeString(self.offset);
        try w.writeInt(self.limit);
    }
};

pub const togglePeerLinkRequestApproval = struct {
    pub const constructor_id: u32 = 0x8c8219a8;
    pub const Result = bool;
    reject: bool = false,
    community: api.InputChannel,
    peer: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.reject) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.community.serialize(w);
        try self.peer.serialize(w);
    }
};

pub const toggleAllPeerLinkRequestApproval = struct {
    pub const constructor_id: u32 = 0xbfe3dd3d;
    pub const Result = bool;
    reject: bool = false,
    community: api.InputChannel,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.reject) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.community.serialize(w);
    }
};

pub const toggleParticipantBanned = struct {
    pub const constructor_id: u32 = 0x9967ad0f;
    pub const Result = bool;
    unban: bool = false,
    community: api.InputChannel,
    participant: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.unban) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.community.serialize(w);
        try self.participant.serialize(w);
    }
};

pub const getParticipantJoinedChats = struct {
    pub const constructor_id: u32 = 0xf87eabab;
    pub const Result = api.communities.ParticipantJoinedChats;
    community: api.InputChannel,
    participant: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.community.serialize(w);
        try self.participant.serialize(w);
    }
};

