//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const getContactIDs = struct {
    pub const constructor_id: u32 = 0x7adc669d;
    pub const Result = []i32;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const getStatuses = struct {
    pub const constructor_id: u32 = 0xc4a353ee;
    pub const Result = []api.ContactStatus;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getContacts = struct {
    pub const constructor_id: u32 = 0x5dd69e12;
    pub const Result = api.contacts.Contacts;
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeLong(self.hash);
    }
};

pub const importContacts = struct {
    pub const constructor_id: u32 = 0x2c800be5;
    pub const Result = api.contacts.ImportedContacts;
    contacts: []api.InputContact,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.contacts.len);
        for (self.contacts) |elem_2621| {
            try elem_2621.serialize(w);
        }
    }
};

pub const deleteContacts = struct {
    pub const constructor_id: u32 = 0x096a0e00;
    pub const Result = api.Updates;
    id: []api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2622| {
            try elem_2622.serialize(w);
        }
    }
};

pub const deleteByPhones = struct {
    pub const constructor_id: u32 = 0x1013fd9e;
    pub const Result = bool;
    phones: [][]const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.phones.len);
        for (self.phones) |elem_2623| {
            try w.writeString(elem_2623);
        }
    }
};

pub const block = struct {
    pub const constructor_id: u32 = 0x2e2e8734;
    pub const Result = bool;
    my_stories_from: bool = false,
    id: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.my_stories_from) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.id.serialize(w);
    }
};

pub const unblock = struct {
    pub const constructor_id: u32 = 0xb550d328;
    pub const Result = bool;
    my_stories_from: bool = false,
    id: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.my_stories_from) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.id.serialize(w);
    }
};

pub const getBlocked = struct {
    pub const constructor_id: u32 = 0x9a868f80;
    pub const Result = api.contacts.Blocked;
    my_stories_from: bool = false,
    offset: i32,
    limit: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.my_stories_from) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeInt(self.offset);
        try w.writeInt(self.limit);
    }
};

pub const search = struct {
    pub const constructor_id: u32 = 0x05f58d0f;
    pub const Result = api.contacts.Found;
    broadcasts: bool = false,
    bots: bool = false,
    q: []const u8,
    limit: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.broadcasts) flags |= 1 << 0;
        if (self.bots) flags |= 1 << 1;
        try w.writeUInt(flags);
        try w.writeString(self.q);
        try w.writeInt(self.limit);
    }
};

pub const resolveUsername = struct {
    pub const constructor_id: u32 = 0x725afbbc;
    pub const Result = api.contacts.ResolvedPeer;
    username: []const u8,
    referer: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.referer != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeString(self.username);
        if (self.referer) |v| {
            try w.writeString(v);
        }
    }
};

pub const getTopPeers = struct {
    pub const constructor_id: u32 = 0x973478b6;
    pub const Result = api.contacts.TopPeers;
    correspondents: bool = false,
    bots_pm: bool = false,
    bots_inline: bool = false,
    phone_calls: bool = false,
    forward_users: bool = false,
    forward_chats: bool = false,
    groups: bool = false,
    channels: bool = false,
    bots_app: bool = false,
    bots_guestchat: bool = false,
    offset: i32,
    limit: i32,
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.correspondents) flags |= 1 << 0;
        if (self.bots_pm) flags |= 1 << 1;
        if (self.bots_inline) flags |= 1 << 2;
        if (self.phone_calls) flags |= 1 << 3;
        if (self.forward_users) flags |= 1 << 4;
        if (self.forward_chats) flags |= 1 << 5;
        if (self.groups) flags |= 1 << 10;
        if (self.channels) flags |= 1 << 15;
        if (self.bots_app) flags |= 1 << 16;
        if (self.bots_guestchat) flags |= 1 << 17;
        try w.writeUInt(flags);
        try w.writeInt(self.offset);
        try w.writeInt(self.limit);
        try w.writeLong(self.hash);
    }
};

pub const resetTopPeerRating = struct {
    pub const constructor_id: u32 = 0x1ae373ac;
    pub const Result = bool;
    category: api.TopPeerCategory,
    peer: *api.InputPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.category.serialize(w);
        try self.peer.serialize(w);
    }
};

pub const resetSaved = struct {
    pub const constructor_id: u32 = 0x879537f1;
    pub const Result = bool;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getSaved = struct {
    pub const constructor_id: u32 = 0x82f1e39f;
    pub const Result = []api.SavedContact;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const toggleTopPeers = struct {
    pub const constructor_id: u32 = 0x8514bdda;
    pub const Result = bool;
    enabled: bool,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeBool(self.enabled);
    }
};

pub const addContact = struct {
    pub const constructor_id: u32 = 0xd9ba2e54;
    pub const Result = api.Updates;
    add_phone_privacy_exception: bool = false,
    id: api.InputUser,
    first_name: []const u8,
    last_name: []const u8,
    phone: []const u8,
    note: ?api.TextWithEntities = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.add_phone_privacy_exception) flags |= 1 << 0;
        if (self.note != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.id.serialize(w);
        try w.writeString(self.first_name);
        try w.writeString(self.last_name);
        try w.writeString(self.phone);
        if (self.note) |v| {
            try v.serialize(w);
        }
    }
};

pub const acceptContact = struct {
    pub const constructor_id: u32 = 0xf831a20f;
    pub const Result = api.Updates;
    id: api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
    }
};

pub const getLocated = struct {
    pub const constructor_id: u32 = 0xd348bc44;
    pub const Result = api.Updates;
    background: bool = false,
    geo_point: api.InputGeoPoint,
    self_expires: ?i32 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.background) flags |= 1 << 1;
        if (self.self_expires != null) flags |= 1 << 0;
        try w.writeUInt(flags);
        try self.geo_point.serialize(w);
        if (self.self_expires) |v| {
            try w.writeInt(v);
        }
    }
};

pub const blockFromReplies = struct {
    pub const constructor_id: u32 = 0x29a8962c;
    pub const Result = api.Updates;
    delete_message: bool = false,
    delete_history: bool = false,
    report_spam: bool = false,
    msg_id: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.delete_message) flags |= 1 << 0;
        if (self.delete_history) flags |= 1 << 1;
        if (self.report_spam) flags |= 1 << 2;
        try w.writeUInt(flags);
        try w.writeInt(self.msg_id);
    }
};

pub const resolvePhone = struct {
    pub const constructor_id: u32 = 0x8af94344;
    pub const Result = api.contacts.ResolvedPeer;
    phone: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.phone);
    }
};

pub const exportContactToken = struct {
    pub const constructor_id: u32 = 0xf8654027;
    pub const Result = api.ExportedContactToken;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const importContactToken = struct {
    pub const constructor_id: u32 = 0x13005788;
    pub const Result = api.User;
    token: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.token);
    }
};

pub const editCloseFriends = struct {
    pub const constructor_id: u32 = 0xba6705f0;
    pub const Result = bool;
    id: []i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2624| {
            try w.writeLong(elem_2624);
        }
    }
};

pub const setBlocked = struct {
    pub const constructor_id: u32 = 0x94c65c76;
    pub const Result = bool;
    my_stories_from: bool = false,
    id: []*api.InputPeer,
    limit: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.my_stories_from) flags |= 1 << 0;
        try w.writeUInt(flags);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2625| {
            try elem_2625.serialize(w);
        }
        try w.writeInt(self.limit);
    }
};

pub const getBirthdays = struct {
    pub const constructor_id: u32 = 0xdaeda864;
    pub const Result = api.contacts.ContactBirthdays;

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        _ = self;
    }
};

pub const getSponsoredPeers = struct {
    pub const constructor_id: u32 = 0xb6c8c393;
    pub const Result = api.contacts.SponsoredPeers;
    q: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.q);
    }
};

pub const updateContactNote = struct {
    pub const constructor_id: u32 = 0x139f63fb;
    pub const Result = bool;
    id: api.InputUser,
    note: api.TextWithEntities,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
        try self.note.serialize(w);
    }
};

