//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const editPeerFolders = struct {
    pub const constructor_id: u32 = 0x6847d0ab;
    pub const Result = api.Updates;
    folder_peers: []api.InputFolderPeer,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.folder_peers.len);
        for (self.folder_peers) |elem_2717| {
            try elem_2717.serialize(w);
        }
    }
};

