//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const getCollectibleInfo = struct {
    pub const constructor_id: u32 = 0xbe1e85ba;
    pub const Result = api.fragment.CollectibleInfo;
    collectible: api.InputCollectible,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.collectible.serialize(w);
    }
};

