//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const getLangPack = struct {
    pub const constructor_id: u32 = 0xf2f2330a;
    pub const Result = api.LangPackDifference;
    lang_pack: []const u8,
    lang_code: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.lang_pack);
        try w.writeString(self.lang_code);
    }
};

pub const getStrings = struct {
    pub const constructor_id: u32 = 0xefea3803;
    pub const Result = []api.LangPackString;
    lang_pack: []const u8,
    lang_code: []const u8,
    keys: [][]const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.lang_pack);
        try w.writeString(self.lang_code);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.keys.len);
        for (self.keys) |elem_2716| {
            try w.writeString(elem_2716);
        }
    }
};

pub const getDifference = struct {
    pub const constructor_id: u32 = 0xcd984aa5;
    pub const Result = api.LangPackDifference;
    lang_pack: []const u8,
    lang_code: []const u8,
    from_version: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.lang_pack);
        try w.writeString(self.lang_code);
        try w.writeInt(self.from_version);
    }
};

pub const getLanguages = struct {
    pub const constructor_id: u32 = 0x42c6978f;
    pub const Result = []api.LangPackLanguage;
    lang_pack: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.lang_pack);
    }
};

pub const getLanguage = struct {
    pub const constructor_id: u32 = 0x6a596502;
    pub const Result = api.LangPackLanguage;
    lang_pack: []const u8,
    lang_code: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.lang_pack);
        try w.writeString(self.lang_code);
    }
};

