//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const createStickerSet = struct {
    pub const constructor_id: u32 = 0x9021ab67;
    pub const Result = api.messages.StickerSet_;
    masks: bool = false,
    emojis: bool = false,
    text_color: bool = false,
    user_id: api.InputUser,
    title: []const u8,
    short_name: []const u8,
    thumb: ?api.InputDocument = null,
    stickers: []api.InputStickerSetItem,
    software: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.masks) flags |= 1 << 0;
        if (self.emojis) flags |= 1 << 5;
        if (self.text_color) flags |= 1 << 6;
        if (self.thumb != null) flags |= 1 << 2;
        if (self.software != null) flags |= 1 << 3;
        try w.writeUInt(flags);
        try self.user_id.serialize(w);
        try w.writeString(self.title);
        try w.writeString(self.short_name);
        if (self.thumb) |v| {
            try v.serialize(w);
        }
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.stickers.len);
        for (self.stickers) |elem_2709| {
            try elem_2709.serialize(w);
        }
        if (self.software) |v| {
            try w.writeString(v);
        }
    }
};

pub const removeStickerFromSet = struct {
    pub const constructor_id: u32 = 0xf7760f51;
    pub const Result = api.messages.StickerSet_;
    sticker: api.InputDocument,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.sticker.serialize(w);
    }
};

pub const changeStickerPosition = struct {
    pub const constructor_id: u32 = 0xffb6d4ca;
    pub const Result = api.messages.StickerSet_;
    sticker: api.InputDocument,
    position: i32,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.sticker.serialize(w);
        try w.writeInt(self.position);
    }
};

pub const addStickerToSet = struct {
    pub const constructor_id: u32 = 0x8653febe;
    pub const Result = api.messages.StickerSet_;
    stickerset: api.InputStickerSet,
    sticker: api.InputStickerSetItem,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.stickerset.serialize(w);
        try self.sticker.serialize(w);
    }
};

pub const setStickerSetThumb = struct {
    pub const constructor_id: u32 = 0xa76a5392;
    pub const Result = api.messages.StickerSet_;
    stickerset: api.InputStickerSet,
    thumb: ?api.InputDocument = null,
    thumb_document_id: ?i64 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.thumb != null) flags |= 1 << 0;
        if (self.thumb_document_id != null) flags |= 1 << 1;
        try w.writeUInt(flags);
        try self.stickerset.serialize(w);
        if (self.thumb) |v| {
            try v.serialize(w);
        }
        if (self.thumb_document_id) |v| {
            try w.writeLong(v);
        }
    }
};

pub const checkShortName = struct {
    pub const constructor_id: u32 = 0x284b3639;
    pub const Result = bool;
    short_name: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.short_name);
    }
};

pub const suggestShortName = struct {
    pub const constructor_id: u32 = 0x4dafc503;
    pub const Result = api.stickers.SuggestedShortName;
    title: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeString(self.title);
    }
};

pub const changeSticker = struct {
    pub const constructor_id: u32 = 0xf5537ebc;
    pub const Result = api.messages.StickerSet_;
    sticker: api.InputDocument,
    emoji: ?[]const u8 = null,
    mask_coords: ?api.MaskCoords = null,
    keywords: ?[]const u8 = null,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        var flags: u32 = 0;
        if (self.emoji != null) flags |= 1 << 0;
        if (self.mask_coords != null) flags |= 1 << 1;
        if (self.keywords != null) flags |= 1 << 2;
        try w.writeUInt(flags);
        try self.sticker.serialize(w);
        if (self.emoji) |v| {
            try w.writeString(v);
        }
        if (self.mask_coords) |v| {
            try v.serialize(w);
        }
        if (self.keywords) |v| {
            try w.writeString(v);
        }
    }
};

pub const renameStickerSet = struct {
    pub const constructor_id: u32 = 0x124b1c00;
    pub const Result = api.messages.StickerSet_;
    stickerset: api.InputStickerSet,
    title: []const u8,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.stickerset.serialize(w);
        try w.writeString(self.title);
    }
};

pub const deleteStickerSet = struct {
    pub const constructor_id: u32 = 0x87704394;
    pub const Result = bool;
    stickerset: api.InputStickerSet,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.stickerset.serialize(w);
    }
};

pub const replaceSticker = struct {
    pub const constructor_id: u32 = 0x4696459a;
    pub const Result = api.messages.StickerSet_;
    sticker: api.InputDocument,
    new_sticker: api.InputStickerSetItem,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.sticker.serialize(w);
        try self.new_sticker.serialize(w);
    }
};

