//! GENERATED by td TL code generator from "api.tl".
//! Do not edit by hand; regenerate with td-gen.

const std = @import("std");
const td = @import("../../root.zig");
const Writer = td.tl.Writer;
const Reader = td.tl.Reader;
const TlError = td.TlError;
const vector_constructor_id = td.tl.vector_constructor_id;

const api = @import("../mod.zig");

pub const getUsers = struct {
    pub const constructor_id: u32 = 0x0d91a548;
    pub const Result = []api.User;
    id: []api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2617| {
            try elem_2617.serialize(w);
        }
    }
};

pub const getFullUser = struct {
    pub const constructor_id: u32 = 0xb60f5918;
    pub const Result = api.users.UserFull_;
    id: api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
    }
};

pub const setSecureValueErrors = struct {
    pub const constructor_id: u32 = 0x90c894b5;
    pub const Result = bool;
    id: api.InputUser,
    errors: []api.SecureValueError,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.errors.len);
        for (self.errors) |elem_2618| {
            try elem_2618.serialize(w);
        }
    }
};

pub const getRequirementsToContact = struct {
    pub const constructor_id: u32 = 0xd89a83a3;
    pub const Result = []api.RequirementToContact;
    id: []api.InputUser,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.id.len);
        for (self.id) |elem_2619| {
            try elem_2619.serialize(w);
        }
    }
};

pub const getSavedMusic = struct {
    pub const constructor_id: u32 = 0x788d7fe3;
    pub const Result = api.users.SavedMusic;
    id: api.InputUser,
    offset: i32,
    limit: i32,
    hash: i64,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
        try w.writeInt(self.offset);
        try w.writeInt(self.limit);
        try w.writeLong(self.hash);
    }
};

pub const getSavedMusicByID = struct {
    pub const constructor_id: u32 = 0x7573a4e9;
    pub const Result = api.users.SavedMusic;
    id: api.InputUser,
    documents: []api.InputDocument,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
        try w.writeUInt(vector_constructor_id);
        try w.writeVectorLength(self.documents.len);
        for (self.documents) |elem_2620| {
            try elem_2620.serialize(w);
        }
    }
};

pub const suggestBirthday = struct {
    pub const constructor_id: u32 = 0xfc533372;
    pub const Result = api.Updates;
    id: api.InputUser,
    birthday: api.Birthday,

    pub fn serialize(self: *const @This(), w: *Writer) TlError!void {
        try w.writeConstructorId(constructor_id);
        try self.id.serialize(w);
        try self.birthday.serialize(w);
    }
};

