//! Generator for the Telegram RPC error catalog: turns the vendored TSV
//! catalogs (one per HTTP-style status code, `id<TAB>message` rows) into
//! the committed module `src/rpc/errors_gen.zig`.
//!
//! Mirrors mtgo's `cmd/errgen` (Apache-2.0, inherited from gotd/td):
//! ids must match `^[A-Z0-9][A-Z0-9_]*$` — anything else is skipped; an
//! `_X` suffix marks a parameterized error whose wire form carries a
//! numeric suffix (`FLOOD_WAIT_X` ← `FLOOD_WAIT_60`) and whose
//! description contains a `{value}` placeholder. The same id may appear
//! under several status codes; the first source wins.
//!
//! Like the TL generator this is deterministic: the same sources and
//! options always produce byte-identical output (entries sorted by wire
//! id). The generated module is self-contained — it imports only `std`
//! and never allocates at runtime.

const std = @import("std");

/// One catalog entry as parsed from a TSV row.
pub const Entry = struct {
    /// Wire id exactly as cataloged (uppercase; `_X` suffix when the
    /// error is parameterized).
    wire: []const u8,
    /// Human-oriented description; `{value}` marks the parameter.
    description: []const u8,
    /// Whether the wire form carries a numeric suffix.
    parameterized: bool,
};

/// One TSV source file, in memory.
pub const Source = struct {
    name: []const u8,
    text: []const u8,
};

pub const Options = struct {
    /// Source label quoted in the generated header comment.
    source_name: []const u8 = "rpc_errors/*.tsv",
};

pub const Error = error{ OutOfMemory, InvalidData };

/// Parses the sources in the order given (the first occurrence of an id
/// wins), sorts the entries by wire id, and emits the catalog module.
pub fn generate(allocator: std.mem.Allocator, sources: []const Source, opts: Options) Error![]u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var entries: std.ArrayList(Entry) = .empty;
    var seen = std.StringHashMap(void).init(arena);
    for (sources) |src| try parseTsv(arena, src, &entries, &seen);

    const items = entries.items;
    std.mem.sort(Entry, items, {}, wireLessThan);

    var out: std.ArrayList(u8) = .empty;
    try line(arena, &out, "//! GENERATED by td error-catalog generator from \"{s}\".", .{opts.source_name});
    try line(arena, &out, "//! Do not edit by hand; regenerate with td-errgen (`just errors`).", .{});
    try line(arena, &out, "//!", .{});
    try line(arena, &out, "//! {d} Telegram RPC error identifiers with descriptions, sorted by wire", .{items.len});
    try line(arena, &out, "//! id. Tag names are the lowercased wire ids (`FLOOD_WAIT_X` ->", .{});
    try line(arena, &out, "//! `.flood_wait_x`); parameterized ids keep their `_x` suffix and the", .{});
    try line(arena, &out, "//! runtime number is reported separately by `classify`. Provenance:", .{});
    try line(arena, &out, "//! tests/data/rpc_errors/README.md.", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "const std = @import(\"std\");", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "/// Telegram RPC error identifiers: the normalized wire form of the", .{});
    try line(arena, &out, "/// `rpc_error` message string. Parameterized errors keep their `_x`", .{});
    try line(arena, &out, "/// suffix — the runtime number is reported separately by `classify`.", .{});
    try line(arena, &out, "pub const Id = enum {{", .{});
    for (items) |e| {
        const tag = try lowerTag(arena, e.wire);
        try line(arena, &out, "    {s},", .{tag});
    }
    try line(arena, &out, "", .{});
    try line(arena, &out, "    /// The cataloged wire id (uppercase; `_X` suffix for", .{});
    try line(arena, &out, "    /// parameterized errors).", .{});
    try line(arena, &out, "    pub fn wire(self: Id) []const u8 {{", .{});
    try line(arena, &out, "        return entries[@intFromEnum(self)].wire;", .{});
    try line(arena, &out, "    }}", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "    /// Human-oriented description; `{{value}}` marks the parameter.", .{});
    try line(arena, &out, "    pub fn description(self: Id) []const u8 {{", .{});
    try line(arena, &out, "        return entries[@intFromEnum(self)].description;", .{});
    try line(arena, &out, "    }}", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "    /// Whether the wire form carries a numeric suffix", .{});
    try line(arena, &out, "    /// (`FLOOD_WAIT_60`).", .{});
    try line(arena, &out, "    pub fn parameterized(self: Id) bool {{", .{});
    try line(arena, &out, "        return entries[@intFromEnum(self)].parameterized;", .{});
    try line(arena, &out, "    }}", .{});
    try line(arena, &out, "}};", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "/// Number of cataloged error identifiers.", .{});
    try line(arena, &out, "pub const count: usize = {d};", .{items.len});
    try line(arena, &out, "", .{});
    try line(arena, &out, "/// A classified `rpc_error` message.", .{});
    try line(arena, &out, "pub const Classified = struct {{", .{});
    try line(arena, &out, "    id: Id,", .{});
    try line(arena, &out, "    /// Numeric suffix of a parameterized id (`FLOOD_WAIT_60` -> 60).", .{});
    try line(arena, &out, "    value: ?u32,", .{});
    try line(arena, &out, "}};", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "/// Maps a wire `rpc_error` message to its catalog entry: exact match", .{});
    try line(arena, &out, "/// first, then a trailing `_<digits>` suffix is normalized to `_X`", .{});
    try line(arena, &out, "/// (the digits become `value`). Returns null for unknown messages —", .{});
    try line(arena, &out, "/// the raw string stays available in `RpcErrorInfo.message`.", .{});
    try line(arena, &out, "pub fn classify(message: []const u8) ?Classified {{", .{});
    try line(arena, &out, "    if (lookup(message)) |id| return .{{ .id = id, .value = null }};", .{});
    try line(arena, &out, "    const us = std.mem.lastIndexOfScalar(u8, message, '_') orelse return null;", .{});
    try line(arena, &out, "    const digits = message[us + 1 ..];", .{});
    try line(arena, &out, "    if (digits.len == 0 or digits.len > 9) return null;", .{});
    try line(arena, &out, "    for (digits) |c| {{", .{});
    try line(arena, &out, "        if (c < '0' or c > '9') return null;", .{});
    try line(arena, &out, "    }}", .{});
    try line(arena, &out, "    if (us + 2 > lookup_buf.len) return null;", .{});
    try line(arena, &out, "    @memcpy(lookup_buf[0..us], message[0..us]);", .{});
    try line(arena, &out, "    lookup_buf[us] = '_';", .{});
    try line(arena, &out, "    lookup_buf[us + 1] = 'X';", .{});
    try line(arena, &out, "    const id = lookup(lookup_buf[0 .. us + 2]) orelse return null;", .{});
    try line(arena, &out, "    return .{{ .id = id, .value = std.fmt.parseInt(u32, digits, 10) catch null }};", .{});
    try line(arena, &out, "}}", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "const Entry = struct {{", .{});
    try line(arena, &out, "    wire: []const u8,", .{});
    try line(arena, &out, "    description: []const u8,", .{});
    try line(arena, &out, "    parameterized: bool,", .{});
    try line(arena, &out, "}};", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "/// Catalog entries in `Id` declaration order (sorted by wire id).", .{});
    try line(arena, &out, "const entries = [_]Entry{{", .{});
    var max_wire: usize = 0;
    for (items) |e| {
        max_wire = @max(max_wire, e.wire.len);
        try appendSlice(arena, &out, "    .{ .wire = \"");
        try escapeInto(arena, &out, e.wire);
        try appendSlice(arena, &out, "\", .description = \"");
        try escapeInto(arena, &out, e.description);
        try line(arena, &out, "\", .parameterized = {} }},", .{e.parameterized});
    }
    try line(arena, &out, "}};", .{});
    try line(arena, &out, "", .{});
    try line(arena, &out, "/// Scratch for `classify`'s normalized candidate: no catalog id is", .{});
    try line(arena, &out, "/// longer than the longest wire id, so overlong messages (which", .{});
    try line(arena, &out, "/// cannot match anything) are rejected instead of copied.", .{});
    try line(arena, &out, "var lookup_buf: [{d}]u8 = undefined;", .{max_wire});
    try line(arena, &out, "", .{});
    try line(arena, &out, "/// Binary search over `entries` (sorted by wire id).", .{});
    try line(arena, &out, "fn lookup(message: []const u8) ?Id {{", .{});
    try line(arena, &out, "    var lo: usize = 0;", .{});
    try line(arena, &out, "    var hi: usize = entries.len;", .{});
    try line(arena, &out, "    while (lo < hi) {{", .{});
    try line(arena, &out, "        const mid = lo + (hi - lo) / 2;", .{});
    try line(arena, &out, "        switch (std.mem.order(u8, entries[mid].wire, message)) {{", .{});
    try line(arena, &out, "            .eq => {{", .{});
    try line(arena, &out, "                const id: Id = @enumFromInt(mid);", .{});
    try line(arena, &out, "                return id;", .{});
    try line(arena, &out, "            }},", .{});
    try line(arena, &out, "            .gt => hi = mid,", .{});
    try line(arena, &out, "            .lt => lo = mid + 1,", .{});
    try line(arena, &out, "        }}", .{});
    try line(arena, &out, "    }}", .{});
    try line(arena, &out, "    return null;", .{});
    try line(arena, &out, "}}", .{});

    return allocator.dupe(u8, out.items);
}

fn parseTsv(
    arena: std.mem.Allocator,
    src: Source,
    entries: *std.ArrayList(Entry),
    seen: *std.StringHashMap(void),
) Error!void {
    var it = std.mem.splitScalar(u8, src.text, '\n');
    var first = true;
    while (it.next()) |raw_line| {
        const l = std.mem.trimEnd(u8, raw_line, "\r"); // CRLF tolerated
        if (first) {
            first = false;
            if (std.mem.startsWith(u8, l, "id\t")) continue; // header row
        }
        if (l.len == 0) continue;
        const tab = std.mem.indexOfScalar(u8, l, '\t') orelse continue;
        const id = l[0..tab];
        if (!validId(id)) continue;
        if (seen.contains(id)) continue; // first source wins
        try seen.put(try arena.dupe(u8, id), {});
        try entries.append(arena, .{
            .wire = try arena.dupe(u8, id),
            .description = try arena.dupe(u8, l[tab + 1 ..]),
            .parameterized = std.mem.endsWith(u8, id, "_X"),
        });
    }
}

/// `^[A-Z0-9][A-Z0-9_]*$` — same acceptance rule as mtgo's errgen.
fn validId(id: []const u8) bool {
    if (id.len == 0) return false;
    for (id, 0..) |c, i| {
        const ok = (c >= 'A' and c <= 'Z') or
            (c >= '0' and c <= '9') or
            (c == '_' and i > 0);
        if (!ok) return false;
    }
    return true;
}

fn wireLessThan(_: void, a: Entry, b: Entry) bool {
    return std.mem.order(u8, a.wire, b.wire) == .lt;
}

/// Lowercased wire id as an enum tag, quoted when it starts with a digit
/// (`2FA_CONFIRM_WAIT_X` -> `@"2fa_confirm_wait_x"`).
fn lowerTag(arena: std.mem.Allocator, wire_id: []const u8) Error![]const u8 {
    const tag = try arena.alloc(u8, wire_id.len);
    for (wire_id, 0..) |c, i| tag[i] = std.ascii.toLower(c);
    if (tag[0] >= '0' and tag[0] <= '9') {
        return std.fmt.allocPrint(arena, "@\"{s}\"", .{tag});
    }
    return tag;
}

fn line(
    arena: std.mem.Allocator,
    out: *std.ArrayList(u8),
    comptime fmt: []const u8,
    args: anytype,
) Error!void {
    const s = try std.fmt.allocPrint(arena, fmt ++ "\n", args);
    try out.appendSlice(arena, s);
}

fn appendSlice(arena: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) Error!void {
    try out.appendSlice(arena, s);
}

/// Appends `s` as the body of a Zig string literal: `"` and `\` are
/// backslash-escaped, control and non-ASCII bytes are re-emitted as
/// `\u{...}` code points (invalid UTF-8 is rejected).
fn escapeInto(arena: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) Error!void {
    var i: usize = 0;
    while (i < s.len) {
        const c = s[i];
        if (c == '"' or c == '\\') {
            try out.appendSlice(arena, &[_]u8{ '\\', c });
            i += 1;
        } else if (c < 0x20 or c == 0x7f) {
            const esc = try std.fmt.allocPrint(arena, "\\u{{{x}}}", .{c});
            try out.appendSlice(arena, esc);
            i += 1;
        } else if (c < 0x80) {
            try out.append(arena, c);
            i += 1;
        } else {
            const len = std.unicode.utf8ByteSequenceLength(c) catch return error.InvalidData;
            if (i + len > s.len) return error.InvalidData;
            const cp = std.unicode.utf8Decode(s[i .. i + len]) catch return error.InvalidData;
            const esc = try std.fmt.allocPrint(arena, "\\u{{{x}}}", .{cp});
            try out.appendSlice(arena, esc);
            i += len;
        }
    }
}

// ---------------------------------------------------------------- tests

const sample_a = "id\tmessage\n" ++
    "2FA_CONFIRM_WAIT_X\tReset in {value} seconds.\n" ++
    "ABOUT_TOO_LONG\tAbout string too long.\n" ++
    "AUTH_RESTART\tRestart the authorization.\n" ++
    "AUTH_RESTART_X\tRestart after {value}.\n" ++
    "FLOOD_WAIT_X\tPlease wait {value} seconds before repeating \"the\" action.\n" ++
    "apiCallError\tTelegram is having internal problems. (skipped: lowercase)\n";

const sample_b = "id\tmessage\n" ++
    "ABOUT_TOO_LONG\tAbout is too long. (skipped: first source wins)\n" ++
    "PHONE_CODE_INVALID\tThe provided phone code is invalid.\n";

test "parses TSV rows: header skip, CRLF, junk ids, first-source dedupe" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var entries: std.ArrayList(Entry) = .empty;
    var seen = std.StringHashMap(void).init(arena);

    // CRLF line endings must be tolerated.
    const crlf = "id\tmessage\r\nABOUT_TOO_LONG\tAbout string too long.\r\n";
    try parseTsv(arena, .{ .name = "a.tsv", .text = crlf }, &entries, &seen);
    try std.testing.expectEqual(@as(usize, 1), entries.items.len);
    try std.testing.expectEqualStrings("ABOUT_TOO_LONG", entries.items[0].wire);
    try std.testing.expectEqualStrings("About string too long.", entries.items[0].description);

    // Full merge across two sources: 6 valid unique ids, lowercase junk
    // skipped, the duplicate ABOUT_TOO_LONG keeps its first description.
    var merged: std.ArrayList(Entry) = .empty;
    var seen2 = std.StringHashMap(void).init(arena);
    try parseTsv(arena, .{ .name = "a.tsv", .text = sample_a }, &merged, &seen2);
    try parseTsv(arena, .{ .name = "b.tsv", .text = sample_b }, &merged, &seen2);
    try std.testing.expectEqual(@as(usize, 6), merged.items.len);
    var about: ?Entry = null;
    for (merged.items) |e| {
        if (std.mem.eql(u8, e.wire, "ABOUT_TOO_LONG")) about = e;
    }
    try std.testing.expectEqualStrings("About string too long.", about.?.description);

    // Parameterized flag follows the `_X` suffix.
    var flags: usize = 0;
    for (merged.items) |e| {
        if (e.parameterized) flags += 1;
    }
    // 2FA_CONFIRM_WAIT_X, AUTH_RESTART_X, FLOOD_WAIT_X.
    try std.testing.expectEqual(@as(usize, 3), flags);
}

test "generate is deterministic and sorted by wire id" {
    const sources = [_]Source{
        .{ .name = "b.tsv", .text = sample_b },
        .{ .name = "a.tsv", .text = sample_a },
    };
    const a = try generate(std.testing.allocator, &sources, .{ .source_name = "sample_errors.tsv" });
    defer std.testing.allocator.free(a);
    const b = try generate(std.testing.allocator, &sources, .{ .source_name = "sample_errors.tsv" });
    defer std.testing.allocator.free(b);
    try std.testing.expectEqualStrings(a, b);

    // Byte-order sorting regardless of input order: digits < letters.
    const digit_tag = std.mem.indexOf(u8, a, "    @\"2fa_confirm_wait_x\",").?;
    const about_tag = std.mem.indexOf(u8, a, "    about_too_long,").?;
    const flood_tag = std.mem.indexOf(u8, a, "    flood_wait_x,").?;
    try std.testing.expect(digit_tag < about_tag);
    try std.testing.expect(about_tag < flood_tag);

    // Wire strings land in the table with quotes escaped; digit-leading
    // ids are quoted tags.
    try std.testing.expect(std.mem.indexOf(u8, a, "    @\"2fa_confirm_wait_x\",") != null);
    try std.testing.expect(std.mem.indexOf(u8, a, ".wire = \"FLOOD_WAIT_X\", .description = \"Please wait {value} seconds before repeating \\\"the\\\" action.\", .parameterized = true") != null);
}

test "descriptions escape quotes, backslashes and non-ASCII" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    var out: std.ArrayList(u8) = .empty;
    try escapeInto(arena, &out, "a\"b\\c\u{e9}\u{1f600}\t");
    try std.testing.expectEqualStrings("a\\\"b\\\\c\\u{e9}\\u{1f600}\\u{9}", out.items);
}
